// Code generated by ent, DO NOT EDIT.

package relaychain

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the relaychain type in the database.
	Label = "relay_chain"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldLogoURL holds the string denoting the logo_url field in the database.
	FieldLogoURL = "logo_url"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldVMType holds the string denoting the vm_type field in the database.
	FieldVMType = "vm_type"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldBaseChainID holds the string denoting the base_chain_id field in the database.
	FieldBaseChainID = "base_chain_id"
	// FieldExplorerURL holds the string denoting the explorer_url field in the database.
	FieldExplorerURL = "explorer_url"
	// FieldExplorerName holds the string denoting the explorer_name field in the database.
	FieldExplorerName = "explorer_name"
	// FieldRPCURL holds the string denoting the rpc_url field in the database.
	FieldRPCURL = "rpc_url"
	// FieldWsRPCURL holds the string denoting the ws_rpc_url field in the database.
	FieldWsRPCURL = "ws_rpc_url"
	// FieldNativeSymbol holds the string denoting the native_symbol field in the database.
	FieldNativeSymbol = "native_symbol"
	// FieldNativeDecimals holds the string denoting the native_decimals field in the database.
	FieldNativeDecimals = "native_decimals"
	// FieldDepositEnabled holds the string denoting the deposit_enabled field in the database.
	FieldDepositEnabled = "deposit_enabled"
	// FieldTokenSupport holds the string denoting the token_support field in the database.
	FieldTokenSupport = "token_support"
	// FieldDisabled holds the string denoting the disabled field in the database.
	FieldDisabled = "disabled"
	// FieldSupported holds the string denoting the supported field in the database.
	FieldSupported = "supported"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldRawData holds the string denoting the raw_data field in the database.
	FieldRawData = "raw_data"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTokens holds the string denoting the tokens edge name in mutations.
	EdgeTokens = "tokens"
	// Table holds the table name of the relaychain in the database.
	Table = "relay_chain"
	// TokensTable is the table that holds the tokens relation/edge.
	TokensTable = "relay_token"
	// TokensInverseTable is the table name for the RelayToken entity.
	// It exists in this package in order to avoid circular dependency with the "relaytoken" package.
	TokensInverseTable = "relay_token"
	// TokensColumn is the table column denoting the tokens relation/edge.
	TokensColumn = "chain_id"
)

// Columns holds all SQL columns for relaychain fields.
var Columns = []string{
	FieldID,
	FieldSlug,
	FieldName,
	FieldLogoURL,
	FieldType,
	FieldVMType,
	FieldProtocol,
	FieldBaseChainID,
	FieldExplorerURL,
	FieldExplorerName,
	FieldRPCURL,
	FieldWsRPCURL,
	FieldNativeSymbol,
	FieldNativeDecimals,
	FieldDepositEnabled,
	FieldTokenSupport,
	FieldDisabled,
	FieldSupported,
	FieldEnabled,
	FieldRawData,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType string
	// DefaultNativeDecimals holds the default value on creation for the "native_decimals" field.
	DefaultNativeDecimals int
	// DefaultDepositEnabled holds the default value on creation for the "deposit_enabled" field.
	DefaultDepositEnabled bool
	// DefaultDisabled holds the default value on creation for the "disabled" field.
	DefaultDisabled bool
	// DefaultSupported holds the default value on creation for the "supported" field.
	DefaultSupported bool
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the RelayChain queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByLogoURL orders the results by the logo_url field.
func ByLogoURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogoURL, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByVMType orders the results by the vm_type field.
func ByVMType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVMType, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByBaseChainID orders the results by the base_chain_id field.
func ByBaseChainID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseChainID, opts...).ToFunc()
}

// ByExplorerURL orders the results by the explorer_url field.
func ByExplorerURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExplorerURL, opts...).ToFunc()
}

// ByExplorerName orders the results by the explorer_name field.
func ByExplorerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExplorerName, opts...).ToFunc()
}

// ByRPCURL orders the results by the rpc_url field.
func ByRPCURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRPCURL, opts...).ToFunc()
}

// ByWsRPCURL orders the results by the ws_rpc_url field.
func ByWsRPCURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWsRPCURL, opts...).ToFunc()
}

// ByNativeSymbol orders the results by the native_symbol field.
func ByNativeSymbol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNativeSymbol, opts...).ToFunc()
}

// ByNativeDecimals orders the results by the native_decimals field.
func ByNativeDecimals(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNativeDecimals, opts...).ToFunc()
}

// ByDepositEnabled orders the results by the deposit_enabled field.
func ByDepositEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepositEnabled, opts...).ToFunc()
}

// ByTokenSupport orders the results by the token_support field.
func ByTokenSupport(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenSupport, opts...).ToFunc()
}

// ByDisabled orders the results by the disabled field.
func ByDisabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisabled, opts...).ToFunc()
}

// BySupported orders the results by the supported field.
func BySupported(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupported, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByRawData orders the results by the raw_data field.
func ByRawData(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawData, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTokensCount orders the results by tokens count.
func ByTokensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTokensStep(), opts...)
	}
}

// ByTokens orders the results by tokens terms.
func ByTokens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTokensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTokensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TokensInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TokensTable, TokensColumn),
	)
}
