// Code generated by ent, DO NOT EDIT.

package relaychain

import (
	"github.com/wf-platform/wf-account-job/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldID, id))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldSlug, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldName, v))
}

// LogoURL applies equality check predicate on the "logo_url" field. It's identical to LogoURLEQ.
func LogoURL(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldLogoURL, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldType, v))
}

// VMType applies equality check predicate on the "vm_type" field. It's identical to VMTypeEQ.
func VMType(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldVMType, v))
}

// Protocol applies equality check predicate on the "protocol" field. It's identical to ProtocolEQ.
func Protocol(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldProtocol, v))
}

// BaseChainID applies equality check predicate on the "base_chain_id" field. It's identical to BaseChainIDEQ.
func BaseChainID(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldBaseChainID, v))
}

// ExplorerURL applies equality check predicate on the "explorer_url" field. It's identical to ExplorerURLEQ.
func ExplorerURL(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldExplorerURL, v))
}

// ExplorerName applies equality check predicate on the "explorer_name" field. It's identical to ExplorerNameEQ.
func ExplorerName(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldExplorerName, v))
}

// RPCURL applies equality check predicate on the "rpc_url" field. It's identical to RPCURLEQ.
func RPCURL(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldRPCURL, v))
}

// WsRPCURL applies equality check predicate on the "ws_rpc_url" field. It's identical to WsRPCURLEQ.
func WsRPCURL(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldWsRPCURL, v))
}

// NativeSymbol applies equality check predicate on the "native_symbol" field. It's identical to NativeSymbolEQ.
func NativeSymbol(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldNativeSymbol, v))
}

// NativeDecimals applies equality check predicate on the "native_decimals" field. It's identical to NativeDecimalsEQ.
func NativeDecimals(v int) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldNativeDecimals, v))
}

// DepositEnabled applies equality check predicate on the "deposit_enabled" field. It's identical to DepositEnabledEQ.
func DepositEnabled(v bool) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldDepositEnabled, v))
}

// TokenSupport applies equality check predicate on the "token_support" field. It's identical to TokenSupportEQ.
func TokenSupport(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldTokenSupport, v))
}

// Disabled applies equality check predicate on the "disabled" field. It's identical to DisabledEQ.
func Disabled(v bool) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldDisabled, v))
}

// Supported applies equality check predicate on the "supported" field. It's identical to SupportedEQ.
func Supported(v bool) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldSupported, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldEnabled, v))
}

// RawData applies equality check predicate on the "raw_data" field. It's identical to RawDataEQ.
func RawData(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldRawData, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldUpdatedAt, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugIsNil applies the IsNil predicate on the "slug" field.
func SlugIsNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIsNull(FieldSlug))
}

// SlugNotNil applies the NotNil predicate on the "slug" field.
func SlugNotNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotNull(FieldSlug))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContainsFold(FieldSlug, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContainsFold(FieldName, v))
}

// LogoURLEQ applies the EQ predicate on the "logo_url" field.
func LogoURLEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldLogoURL, v))
}

// LogoURLNEQ applies the NEQ predicate on the "logo_url" field.
func LogoURLNEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldLogoURL, v))
}

// LogoURLIn applies the In predicate on the "logo_url" field.
func LogoURLIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldLogoURL, vs...))
}

// LogoURLNotIn applies the NotIn predicate on the "logo_url" field.
func LogoURLNotIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldLogoURL, vs...))
}

// LogoURLGT applies the GT predicate on the "logo_url" field.
func LogoURLGT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldLogoURL, v))
}

// LogoURLGTE applies the GTE predicate on the "logo_url" field.
func LogoURLGTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldLogoURL, v))
}

// LogoURLLT applies the LT predicate on the "logo_url" field.
func LogoURLLT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldLogoURL, v))
}

// LogoURLLTE applies the LTE predicate on the "logo_url" field.
func LogoURLLTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldLogoURL, v))
}

// LogoURLContains applies the Contains predicate on the "logo_url" field.
func LogoURLContains(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContains(FieldLogoURL, v))
}

// LogoURLHasPrefix applies the HasPrefix predicate on the "logo_url" field.
func LogoURLHasPrefix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasPrefix(FieldLogoURL, v))
}

// LogoURLHasSuffix applies the HasSuffix predicate on the "logo_url" field.
func LogoURLHasSuffix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasSuffix(FieldLogoURL, v))
}

// LogoURLIsNil applies the IsNil predicate on the "logo_url" field.
func LogoURLIsNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIsNull(FieldLogoURL))
}

// LogoURLNotNil applies the NotNil predicate on the "logo_url" field.
func LogoURLNotNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotNull(FieldLogoURL))
}

// LogoURLEqualFold applies the EqualFold predicate on the "logo_url" field.
func LogoURLEqualFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEqualFold(FieldLogoURL, v))
}

// LogoURLContainsFold applies the ContainsFold predicate on the "logo_url" field.
func LogoURLContainsFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContainsFold(FieldLogoURL, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContainsFold(FieldType, v))
}

// VMTypeEQ applies the EQ predicate on the "vm_type" field.
func VMTypeEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldVMType, v))
}

// VMTypeNEQ applies the NEQ predicate on the "vm_type" field.
func VMTypeNEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldVMType, v))
}

// VMTypeIn applies the In predicate on the "vm_type" field.
func VMTypeIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldVMType, vs...))
}

// VMTypeNotIn applies the NotIn predicate on the "vm_type" field.
func VMTypeNotIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldVMType, vs...))
}

// VMTypeGT applies the GT predicate on the "vm_type" field.
func VMTypeGT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldVMType, v))
}

// VMTypeGTE applies the GTE predicate on the "vm_type" field.
func VMTypeGTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldVMType, v))
}

// VMTypeLT applies the LT predicate on the "vm_type" field.
func VMTypeLT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldVMType, v))
}

// VMTypeLTE applies the LTE predicate on the "vm_type" field.
func VMTypeLTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldVMType, v))
}

// VMTypeContains applies the Contains predicate on the "vm_type" field.
func VMTypeContains(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContains(FieldVMType, v))
}

// VMTypeHasPrefix applies the HasPrefix predicate on the "vm_type" field.
func VMTypeHasPrefix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasPrefix(FieldVMType, v))
}

// VMTypeHasSuffix applies the HasSuffix predicate on the "vm_type" field.
func VMTypeHasSuffix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasSuffix(FieldVMType, v))
}

// VMTypeIsNil applies the IsNil predicate on the "vm_type" field.
func VMTypeIsNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIsNull(FieldVMType))
}

// VMTypeNotNil applies the NotNil predicate on the "vm_type" field.
func VMTypeNotNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotNull(FieldVMType))
}

// VMTypeEqualFold applies the EqualFold predicate on the "vm_type" field.
func VMTypeEqualFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEqualFold(FieldVMType, v))
}

// VMTypeContainsFold applies the ContainsFold predicate on the "vm_type" field.
func VMTypeContainsFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContainsFold(FieldVMType, v))
}

// ProtocolEQ applies the EQ predicate on the "protocol" field.
func ProtocolEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldProtocol, v))
}

// ProtocolNEQ applies the NEQ predicate on the "protocol" field.
func ProtocolNEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldProtocol, v))
}

// ProtocolIn applies the In predicate on the "protocol" field.
func ProtocolIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldProtocol, vs...))
}

// ProtocolNotIn applies the NotIn predicate on the "protocol" field.
func ProtocolNotIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldProtocol, vs...))
}

// ProtocolGT applies the GT predicate on the "protocol" field.
func ProtocolGT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldProtocol, v))
}

// ProtocolGTE applies the GTE predicate on the "protocol" field.
func ProtocolGTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldProtocol, v))
}

// ProtocolLT applies the LT predicate on the "protocol" field.
func ProtocolLT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldProtocol, v))
}

// ProtocolLTE applies the LTE predicate on the "protocol" field.
func ProtocolLTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldProtocol, v))
}

// ProtocolContains applies the Contains predicate on the "protocol" field.
func ProtocolContains(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContains(FieldProtocol, v))
}

// ProtocolHasPrefix applies the HasPrefix predicate on the "protocol" field.
func ProtocolHasPrefix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasPrefix(FieldProtocol, v))
}

// ProtocolHasSuffix applies the HasSuffix predicate on the "protocol" field.
func ProtocolHasSuffix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasSuffix(FieldProtocol, v))
}

// ProtocolIsNil applies the IsNil predicate on the "protocol" field.
func ProtocolIsNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIsNull(FieldProtocol))
}

// ProtocolNotNil applies the NotNil predicate on the "protocol" field.
func ProtocolNotNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotNull(FieldProtocol))
}

// ProtocolEqualFold applies the EqualFold predicate on the "protocol" field.
func ProtocolEqualFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEqualFold(FieldProtocol, v))
}

// ProtocolContainsFold applies the ContainsFold predicate on the "protocol" field.
func ProtocolContainsFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContainsFold(FieldProtocol, v))
}

// BaseChainIDEQ applies the EQ predicate on the "base_chain_id" field.
func BaseChainIDEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldBaseChainID, v))
}

// BaseChainIDNEQ applies the NEQ predicate on the "base_chain_id" field.
func BaseChainIDNEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldBaseChainID, v))
}

// BaseChainIDIn applies the In predicate on the "base_chain_id" field.
func BaseChainIDIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldBaseChainID, vs...))
}

// BaseChainIDNotIn applies the NotIn predicate on the "base_chain_id" field.
func BaseChainIDNotIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldBaseChainID, vs...))
}

// BaseChainIDGT applies the GT predicate on the "base_chain_id" field.
func BaseChainIDGT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldBaseChainID, v))
}

// BaseChainIDGTE applies the GTE predicate on the "base_chain_id" field.
func BaseChainIDGTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldBaseChainID, v))
}

// BaseChainIDLT applies the LT predicate on the "base_chain_id" field.
func BaseChainIDLT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldBaseChainID, v))
}

// BaseChainIDLTE applies the LTE predicate on the "base_chain_id" field.
func BaseChainIDLTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldBaseChainID, v))
}

// BaseChainIDContains applies the Contains predicate on the "base_chain_id" field.
func BaseChainIDContains(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContains(FieldBaseChainID, v))
}

// BaseChainIDHasPrefix applies the HasPrefix predicate on the "base_chain_id" field.
func BaseChainIDHasPrefix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasPrefix(FieldBaseChainID, v))
}

// BaseChainIDHasSuffix applies the HasSuffix predicate on the "base_chain_id" field.
func BaseChainIDHasSuffix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasSuffix(FieldBaseChainID, v))
}

// BaseChainIDIsNil applies the IsNil predicate on the "base_chain_id" field.
func BaseChainIDIsNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIsNull(FieldBaseChainID))
}

// BaseChainIDNotNil applies the NotNil predicate on the "base_chain_id" field.
func BaseChainIDNotNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotNull(FieldBaseChainID))
}

// BaseChainIDEqualFold applies the EqualFold predicate on the "base_chain_id" field.
func BaseChainIDEqualFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEqualFold(FieldBaseChainID, v))
}

// BaseChainIDContainsFold applies the ContainsFold predicate on the "base_chain_id" field.
func BaseChainIDContainsFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContainsFold(FieldBaseChainID, v))
}

// ExplorerURLEQ applies the EQ predicate on the "explorer_url" field.
func ExplorerURLEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldExplorerURL, v))
}

// ExplorerURLNEQ applies the NEQ predicate on the "explorer_url" field.
func ExplorerURLNEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldExplorerURL, v))
}

// ExplorerURLIn applies the In predicate on the "explorer_url" field.
func ExplorerURLIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldExplorerURL, vs...))
}

// ExplorerURLNotIn applies the NotIn predicate on the "explorer_url" field.
func ExplorerURLNotIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldExplorerURL, vs...))
}

// ExplorerURLGT applies the GT predicate on the "explorer_url" field.
func ExplorerURLGT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldExplorerURL, v))
}

// ExplorerURLGTE applies the GTE predicate on the "explorer_url" field.
func ExplorerURLGTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldExplorerURL, v))
}

// ExplorerURLLT applies the LT predicate on the "explorer_url" field.
func ExplorerURLLT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldExplorerURL, v))
}

// ExplorerURLLTE applies the LTE predicate on the "explorer_url" field.
func ExplorerURLLTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldExplorerURL, v))
}

// ExplorerURLContains applies the Contains predicate on the "explorer_url" field.
func ExplorerURLContains(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContains(FieldExplorerURL, v))
}

// ExplorerURLHasPrefix applies the HasPrefix predicate on the "explorer_url" field.
func ExplorerURLHasPrefix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasPrefix(FieldExplorerURL, v))
}

// ExplorerURLHasSuffix applies the HasSuffix predicate on the "explorer_url" field.
func ExplorerURLHasSuffix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasSuffix(FieldExplorerURL, v))
}

// ExplorerURLIsNil applies the IsNil predicate on the "explorer_url" field.
func ExplorerURLIsNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIsNull(FieldExplorerURL))
}

// ExplorerURLNotNil applies the NotNil predicate on the "explorer_url" field.
func ExplorerURLNotNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotNull(FieldExplorerURL))
}

// ExplorerURLEqualFold applies the EqualFold predicate on the "explorer_url" field.
func ExplorerURLEqualFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEqualFold(FieldExplorerURL, v))
}

// ExplorerURLContainsFold applies the ContainsFold predicate on the "explorer_url" field.
func ExplorerURLContainsFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContainsFold(FieldExplorerURL, v))
}

// ExplorerNameEQ applies the EQ predicate on the "explorer_name" field.
func ExplorerNameEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldExplorerName, v))
}

// ExplorerNameNEQ applies the NEQ predicate on the "explorer_name" field.
func ExplorerNameNEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldExplorerName, v))
}

// ExplorerNameIn applies the In predicate on the "explorer_name" field.
func ExplorerNameIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldExplorerName, vs...))
}

// ExplorerNameNotIn applies the NotIn predicate on the "explorer_name" field.
func ExplorerNameNotIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldExplorerName, vs...))
}

// ExplorerNameGT applies the GT predicate on the "explorer_name" field.
func ExplorerNameGT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldExplorerName, v))
}

// ExplorerNameGTE applies the GTE predicate on the "explorer_name" field.
func ExplorerNameGTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldExplorerName, v))
}

// ExplorerNameLT applies the LT predicate on the "explorer_name" field.
func ExplorerNameLT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldExplorerName, v))
}

// ExplorerNameLTE applies the LTE predicate on the "explorer_name" field.
func ExplorerNameLTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldExplorerName, v))
}

// ExplorerNameContains applies the Contains predicate on the "explorer_name" field.
func ExplorerNameContains(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContains(FieldExplorerName, v))
}

// ExplorerNameHasPrefix applies the HasPrefix predicate on the "explorer_name" field.
func ExplorerNameHasPrefix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasPrefix(FieldExplorerName, v))
}

// ExplorerNameHasSuffix applies the HasSuffix predicate on the "explorer_name" field.
func ExplorerNameHasSuffix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasSuffix(FieldExplorerName, v))
}

// ExplorerNameIsNil applies the IsNil predicate on the "explorer_name" field.
func ExplorerNameIsNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIsNull(FieldExplorerName))
}

// ExplorerNameNotNil applies the NotNil predicate on the "explorer_name" field.
func ExplorerNameNotNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotNull(FieldExplorerName))
}

// ExplorerNameEqualFold applies the EqualFold predicate on the "explorer_name" field.
func ExplorerNameEqualFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEqualFold(FieldExplorerName, v))
}

// ExplorerNameContainsFold applies the ContainsFold predicate on the "explorer_name" field.
func ExplorerNameContainsFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContainsFold(FieldExplorerName, v))
}

// RPCURLEQ applies the EQ predicate on the "rpc_url" field.
func RPCURLEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldRPCURL, v))
}

// RPCURLNEQ applies the NEQ predicate on the "rpc_url" field.
func RPCURLNEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldRPCURL, v))
}

// RPCURLIn applies the In predicate on the "rpc_url" field.
func RPCURLIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldRPCURL, vs...))
}

// RPCURLNotIn applies the NotIn predicate on the "rpc_url" field.
func RPCURLNotIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldRPCURL, vs...))
}

// RPCURLGT applies the GT predicate on the "rpc_url" field.
func RPCURLGT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldRPCURL, v))
}

// RPCURLGTE applies the GTE predicate on the "rpc_url" field.
func RPCURLGTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldRPCURL, v))
}

// RPCURLLT applies the LT predicate on the "rpc_url" field.
func RPCURLLT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldRPCURL, v))
}

// RPCURLLTE applies the LTE predicate on the "rpc_url" field.
func RPCURLLTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldRPCURL, v))
}

// RPCURLContains applies the Contains predicate on the "rpc_url" field.
func RPCURLContains(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContains(FieldRPCURL, v))
}

// RPCURLHasPrefix applies the HasPrefix predicate on the "rpc_url" field.
func RPCURLHasPrefix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasPrefix(FieldRPCURL, v))
}

// RPCURLHasSuffix applies the HasSuffix predicate on the "rpc_url" field.
func RPCURLHasSuffix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasSuffix(FieldRPCURL, v))
}

// RPCURLIsNil applies the IsNil predicate on the "rpc_url" field.
func RPCURLIsNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIsNull(FieldRPCURL))
}

// RPCURLNotNil applies the NotNil predicate on the "rpc_url" field.
func RPCURLNotNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotNull(FieldRPCURL))
}

// RPCURLEqualFold applies the EqualFold predicate on the "rpc_url" field.
func RPCURLEqualFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEqualFold(FieldRPCURL, v))
}

// RPCURLContainsFold applies the ContainsFold predicate on the "rpc_url" field.
func RPCURLContainsFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContainsFold(FieldRPCURL, v))
}

// WsRPCURLEQ applies the EQ predicate on the "ws_rpc_url" field.
func WsRPCURLEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldWsRPCURL, v))
}

// WsRPCURLNEQ applies the NEQ predicate on the "ws_rpc_url" field.
func WsRPCURLNEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldWsRPCURL, v))
}

// WsRPCURLIn applies the In predicate on the "ws_rpc_url" field.
func WsRPCURLIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldWsRPCURL, vs...))
}

// WsRPCURLNotIn applies the NotIn predicate on the "ws_rpc_url" field.
func WsRPCURLNotIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldWsRPCURL, vs...))
}

// WsRPCURLGT applies the GT predicate on the "ws_rpc_url" field.
func WsRPCURLGT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldWsRPCURL, v))
}

// WsRPCURLGTE applies the GTE predicate on the "ws_rpc_url" field.
func WsRPCURLGTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldWsRPCURL, v))
}

// WsRPCURLLT applies the LT predicate on the "ws_rpc_url" field.
func WsRPCURLLT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldWsRPCURL, v))
}

// WsRPCURLLTE applies the LTE predicate on the "ws_rpc_url" field.
func WsRPCURLLTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldWsRPCURL, v))
}

// WsRPCURLContains applies the Contains predicate on the "ws_rpc_url" field.
func WsRPCURLContains(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContains(FieldWsRPCURL, v))
}

// WsRPCURLHasPrefix applies the HasPrefix predicate on the "ws_rpc_url" field.
func WsRPCURLHasPrefix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasPrefix(FieldWsRPCURL, v))
}

// WsRPCURLHasSuffix applies the HasSuffix predicate on the "ws_rpc_url" field.
func WsRPCURLHasSuffix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasSuffix(FieldWsRPCURL, v))
}

// WsRPCURLIsNil applies the IsNil predicate on the "ws_rpc_url" field.
func WsRPCURLIsNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIsNull(FieldWsRPCURL))
}

// WsRPCURLNotNil applies the NotNil predicate on the "ws_rpc_url" field.
func WsRPCURLNotNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotNull(FieldWsRPCURL))
}

// WsRPCURLEqualFold applies the EqualFold predicate on the "ws_rpc_url" field.
func WsRPCURLEqualFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEqualFold(FieldWsRPCURL, v))
}

// WsRPCURLContainsFold applies the ContainsFold predicate on the "ws_rpc_url" field.
func WsRPCURLContainsFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContainsFold(FieldWsRPCURL, v))
}

// NativeSymbolEQ applies the EQ predicate on the "native_symbol" field.
func NativeSymbolEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldNativeSymbol, v))
}

// NativeSymbolNEQ applies the NEQ predicate on the "native_symbol" field.
func NativeSymbolNEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldNativeSymbol, v))
}

// NativeSymbolIn applies the In predicate on the "native_symbol" field.
func NativeSymbolIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldNativeSymbol, vs...))
}

// NativeSymbolNotIn applies the NotIn predicate on the "native_symbol" field.
func NativeSymbolNotIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldNativeSymbol, vs...))
}

// NativeSymbolGT applies the GT predicate on the "native_symbol" field.
func NativeSymbolGT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldNativeSymbol, v))
}

// NativeSymbolGTE applies the GTE predicate on the "native_symbol" field.
func NativeSymbolGTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldNativeSymbol, v))
}

// NativeSymbolLT applies the LT predicate on the "native_symbol" field.
func NativeSymbolLT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldNativeSymbol, v))
}

// NativeSymbolLTE applies the LTE predicate on the "native_symbol" field.
func NativeSymbolLTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldNativeSymbol, v))
}

// NativeSymbolContains applies the Contains predicate on the "native_symbol" field.
func NativeSymbolContains(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContains(FieldNativeSymbol, v))
}

// NativeSymbolHasPrefix applies the HasPrefix predicate on the "native_symbol" field.
func NativeSymbolHasPrefix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasPrefix(FieldNativeSymbol, v))
}

// NativeSymbolHasSuffix applies the HasSuffix predicate on the "native_symbol" field.
func NativeSymbolHasSuffix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasSuffix(FieldNativeSymbol, v))
}

// NativeSymbolIsNil applies the IsNil predicate on the "native_symbol" field.
func NativeSymbolIsNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIsNull(FieldNativeSymbol))
}

// NativeSymbolNotNil applies the NotNil predicate on the "native_symbol" field.
func NativeSymbolNotNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotNull(FieldNativeSymbol))
}

// NativeSymbolEqualFold applies the EqualFold predicate on the "native_symbol" field.
func NativeSymbolEqualFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEqualFold(FieldNativeSymbol, v))
}

// NativeSymbolContainsFold applies the ContainsFold predicate on the "native_symbol" field.
func NativeSymbolContainsFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContainsFold(FieldNativeSymbol, v))
}

// NativeDecimalsEQ applies the EQ predicate on the "native_decimals" field.
func NativeDecimalsEQ(v int) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldNativeDecimals, v))
}

// NativeDecimalsNEQ applies the NEQ predicate on the "native_decimals" field.
func NativeDecimalsNEQ(v int) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldNativeDecimals, v))
}

// NativeDecimalsIn applies the In predicate on the "native_decimals" field.
func NativeDecimalsIn(vs ...int) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldNativeDecimals, vs...))
}

// NativeDecimalsNotIn applies the NotIn predicate on the "native_decimals" field.
func NativeDecimalsNotIn(vs ...int) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldNativeDecimals, vs...))
}

// NativeDecimalsGT applies the GT predicate on the "native_decimals" field.
func NativeDecimalsGT(v int) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldNativeDecimals, v))
}

// NativeDecimalsGTE applies the GTE predicate on the "native_decimals" field.
func NativeDecimalsGTE(v int) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldNativeDecimals, v))
}

// NativeDecimalsLT applies the LT predicate on the "native_decimals" field.
func NativeDecimalsLT(v int) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldNativeDecimals, v))
}

// NativeDecimalsLTE applies the LTE predicate on the "native_decimals" field.
func NativeDecimalsLTE(v int) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldNativeDecimals, v))
}

// DepositEnabledEQ applies the EQ predicate on the "deposit_enabled" field.
func DepositEnabledEQ(v bool) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldDepositEnabled, v))
}

// DepositEnabledNEQ applies the NEQ predicate on the "deposit_enabled" field.
func DepositEnabledNEQ(v bool) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldDepositEnabled, v))
}

// TokenSupportEQ applies the EQ predicate on the "token_support" field.
func TokenSupportEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldTokenSupport, v))
}

// TokenSupportNEQ applies the NEQ predicate on the "token_support" field.
func TokenSupportNEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldTokenSupport, v))
}

// TokenSupportIn applies the In predicate on the "token_support" field.
func TokenSupportIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldTokenSupport, vs...))
}

// TokenSupportNotIn applies the NotIn predicate on the "token_support" field.
func TokenSupportNotIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldTokenSupport, vs...))
}

// TokenSupportGT applies the GT predicate on the "token_support" field.
func TokenSupportGT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldTokenSupport, v))
}

// TokenSupportGTE applies the GTE predicate on the "token_support" field.
func TokenSupportGTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldTokenSupport, v))
}

// TokenSupportLT applies the LT predicate on the "token_support" field.
func TokenSupportLT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldTokenSupport, v))
}

// TokenSupportLTE applies the LTE predicate on the "token_support" field.
func TokenSupportLTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldTokenSupport, v))
}

// TokenSupportContains applies the Contains predicate on the "token_support" field.
func TokenSupportContains(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContains(FieldTokenSupport, v))
}

// TokenSupportHasPrefix applies the HasPrefix predicate on the "token_support" field.
func TokenSupportHasPrefix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasPrefix(FieldTokenSupport, v))
}

// TokenSupportHasSuffix applies the HasSuffix predicate on the "token_support" field.
func TokenSupportHasSuffix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasSuffix(FieldTokenSupport, v))
}

// TokenSupportIsNil applies the IsNil predicate on the "token_support" field.
func TokenSupportIsNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIsNull(FieldTokenSupport))
}

// TokenSupportNotNil applies the NotNil predicate on the "token_support" field.
func TokenSupportNotNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotNull(FieldTokenSupport))
}

// TokenSupportEqualFold applies the EqualFold predicate on the "token_support" field.
func TokenSupportEqualFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEqualFold(FieldTokenSupport, v))
}

// TokenSupportContainsFold applies the ContainsFold predicate on the "token_support" field.
func TokenSupportContainsFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContainsFold(FieldTokenSupport, v))
}

// DisabledEQ applies the EQ predicate on the "disabled" field.
func DisabledEQ(v bool) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldDisabled, v))
}

// DisabledNEQ applies the NEQ predicate on the "disabled" field.
func DisabledNEQ(v bool) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldDisabled, v))
}

// SupportedEQ applies the EQ predicate on the "supported" field.
func SupportedEQ(v bool) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldSupported, v))
}

// SupportedNEQ applies the NEQ predicate on the "supported" field.
func SupportedNEQ(v bool) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldSupported, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldEnabled, v))
}

// RawDataEQ applies the EQ predicate on the "raw_data" field.
func RawDataEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldRawData, v))
}

// RawDataNEQ applies the NEQ predicate on the "raw_data" field.
func RawDataNEQ(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldRawData, v))
}

// RawDataIn applies the In predicate on the "raw_data" field.
func RawDataIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldRawData, vs...))
}

// RawDataNotIn applies the NotIn predicate on the "raw_data" field.
func RawDataNotIn(vs ...string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldRawData, vs...))
}

// RawDataGT applies the GT predicate on the "raw_data" field.
func RawDataGT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldRawData, v))
}

// RawDataGTE applies the GTE predicate on the "raw_data" field.
func RawDataGTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldRawData, v))
}

// RawDataLT applies the LT predicate on the "raw_data" field.
func RawDataLT(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldRawData, v))
}

// RawDataLTE applies the LTE predicate on the "raw_data" field.
func RawDataLTE(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldRawData, v))
}

// RawDataContains applies the Contains predicate on the "raw_data" field.
func RawDataContains(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContains(FieldRawData, v))
}

// RawDataHasPrefix applies the HasPrefix predicate on the "raw_data" field.
func RawDataHasPrefix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasPrefix(FieldRawData, v))
}

// RawDataHasSuffix applies the HasSuffix predicate on the "raw_data" field.
func RawDataHasSuffix(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldHasSuffix(FieldRawData, v))
}

// RawDataIsNil applies the IsNil predicate on the "raw_data" field.
func RawDataIsNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIsNull(FieldRawData))
}

// RawDataNotNil applies the NotNil predicate on the "raw_data" field.
func RawDataNotNil() predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotNull(FieldRawData))
}

// RawDataEqualFold applies the EqualFold predicate on the "raw_data" field.
func RawDataEqualFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEqualFold(FieldRawData, v))
}

// RawDataContainsFold applies the ContainsFold predicate on the "raw_data" field.
func RawDataContainsFold(v string) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldContainsFold(FieldRawData, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RelayChain {
	return predicate.RelayChain(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTokens applies the HasEdge predicate on the "tokens" edge.
func HasTokens() predicate.RelayChain {
	return predicate.RelayChain(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TokensTable, TokensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTokensWith applies the HasEdge predicate on the "tokens" edge with a given conditions (other predicates).
func HasTokensWith(preds ...predicate.RelayToken) predicate.RelayChain {
	return predicate.RelayChain(func(s *sql.Selector) {
		step := newTokensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelayChain) predicate.RelayChain {
	return predicate.RelayChain(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelayChain) predicate.RelayChain {
	return predicate.RelayChain(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelayChain) predicate.RelayChain {
	return predicate.RelayChain(sql.NotPredicates(p))
}
