// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: job.proto

package job

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseIDResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseIDResp) Reset() {
	*x = BaseIDResp{}
	mi := &file_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseIDResp) ProtoMessage() {}

func (x *BaseIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseIDResp.ProtoReflect.Descriptor instead.
func (*BaseIDResp) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{0}
}

func (x *BaseIDResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseIDResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{1}
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BaseUUIDResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseUUIDResp) Reset() {
	*x = BaseUUIDResp{}
	mi := &file_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseUUIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseUUIDResp) ProtoMessage() {}

func (x *BaseUUIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseUUIDResp.ProtoReflect.Descriptor instead.
func (*BaseUUIDResp) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{2}
}

func (x *BaseUUIDResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseUUIDResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// base message
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{3}
}

type IDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDReq) Reset() {
	*x = IDReq{}
	mi := &file_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDReq) ProtoMessage() {}

func (x *IDReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDReq.ProtoReflect.Descriptor instead.
func (*IDReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{4}
}

func (x *IDReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IDsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDsReq) Reset() {
	*x = IDsReq{}
	mi := &file_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDsReq) ProtoMessage() {}

func (x *IDsReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDsReq.ProtoReflect.Descriptor instead.
func (*IDsReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{5}
}

func (x *IDsReq) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type PageInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfoReq) Reset() {
	*x = PageInfoReq{}
	mi := &file_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfoReq) ProtoMessage() {}

func (x *PageInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfoReq.ProtoReflect.Descriptor instead.
func (*PageInfoReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{6}
}

func (x *PageInfoReq) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfoReq) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type TaskInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *uint64                `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	CreatedAt      *int64                 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	UpdatedAt      *int64                 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	Status         *uint32                `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Name           *string                `protobuf:"bytes,5,opt,name=name,proto3,oneof" json:"name,omitempty"`
	TaskGroup      *string                `protobuf:"bytes,6,opt,name=task_group,json=taskGroup,proto3,oneof" json:"task_group,omitempty"`
	CronExpression *string                `protobuf:"bytes,7,opt,name=cron_expression,json=cronExpression,proto3,oneof" json:"cron_expression,omitempty"`
	Pattern        *string                `protobuf:"bytes,8,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"`
	Payload        *string                `protobuf:"bytes,9,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_job_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{7}
}

func (x *TaskInfo) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TaskInfo) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *TaskInfo) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *TaskInfo) GetStatus() uint32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *TaskInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TaskInfo) GetTaskGroup() string {
	if x != nil && x.TaskGroup != nil {
		return *x.TaskGroup
	}
	return ""
}

func (x *TaskInfo) GetCronExpression() string {
	if x != nil && x.CronExpression != nil {
		return *x.CronExpression
	}
	return ""
}

func (x *TaskInfo) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

func (x *TaskInfo) GetPayload() string {
	if x != nil && x.Payload != nil {
		return *x.Payload
	}
	return ""
}

type TaskListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	TaskGroup     *string                `protobuf:"bytes,4,opt,name=task_group,json=taskGroup,proto3,oneof" json:"task_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskListReq) Reset() {
	*x = TaskListReq{}
	mi := &file_job_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskListReq) ProtoMessage() {}

func (x *TaskListReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskListReq.ProtoReflect.Descriptor instead.
func (*TaskListReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{8}
}

func (x *TaskListReq) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TaskListReq) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *TaskListReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TaskListReq) GetTaskGroup() string {
	if x != nil && x.TaskGroup != nil {
		return *x.TaskGroup
	}
	return ""
}

type TaskListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*TaskInfo            `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskListResp) Reset() {
	*x = TaskListResp{}
	mi := &file_job_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskListResp) ProtoMessage() {}

func (x *TaskListResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskListResp.ProtoReflect.Descriptor instead.
func (*TaskListResp) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{9}
}

func (x *TaskListResp) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TaskListResp) GetData() []*TaskInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type TaskLogInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	CreatedAt     *int64                 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	UpdatedAt     *int64                 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	StartedAt     *int64                 `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	FinishedAt    *int64                 `protobuf:"varint,5,opt,name=finished_at,json=finishedAt,proto3,oneof" json:"finished_at,omitempty"`
	Result        *uint32                `protobuf:"varint,6,opt,name=result,proto3,oneof" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogInfo) Reset() {
	*x = TaskLogInfo{}
	mi := &file_job_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogInfo) ProtoMessage() {}

func (x *TaskLogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogInfo.ProtoReflect.Descriptor instead.
func (*TaskLogInfo) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{10}
}

func (x *TaskLogInfo) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TaskLogInfo) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *TaskLogInfo) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *TaskLogInfo) GetStartedAt() int64 {
	if x != nil && x.StartedAt != nil {
		return *x.StartedAt
	}
	return 0
}

func (x *TaskLogInfo) GetFinishedAt() int64 {
	if x != nil && x.FinishedAt != nil {
		return *x.FinishedAt
	}
	return 0
}

func (x *TaskLogInfo) GetResult() uint32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type TaskLogListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TaskId        *uint64                `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"`
	Result        *uint32                `protobuf:"varint,4,opt,name=result,proto3,oneof" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogListReq) Reset() {
	*x = TaskLogListReq{}
	mi := &file_job_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogListReq) ProtoMessage() {}

func (x *TaskLogListReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogListReq.ProtoReflect.Descriptor instead.
func (*TaskLogListReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{11}
}

func (x *TaskLogListReq) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TaskLogListReq) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *TaskLogListReq) GetTaskId() uint64 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return 0
}

func (x *TaskLogListReq) GetResult() uint32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type TaskLogListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*TaskLogInfo         `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogListResp) Reset() {
	*x = TaskLogListResp{}
	mi := &file_job_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogListResp) ProtoMessage() {}

func (x *TaskLogListResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogListResp.ProtoReflect.Descriptor instead.
func (*TaskLogListResp) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{12}
}

func (x *TaskLogListResp) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TaskLogListResp) GetData() []*TaskLogInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type UUIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUIDReq) Reset() {
	*x = UUIDReq{}
	mi := &file_job_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDReq) ProtoMessage() {}

func (x *UUIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDReq.ProtoReflect.Descriptor instead.
func (*UUIDReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{13}
}

func (x *UUIDReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UUIDsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUIDsReq) Reset() {
	*x = UUIDsReq{}
	mi := &file_job_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUIDsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDsReq) ProtoMessage() {}

func (x *UUIDsReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDsReq.ProtoReflect.Descriptor instead.
func (*UUIDsReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{14}
}

func (x *UUIDsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type RelayChainIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayChainIDReq) Reset() {
	*x = RelayChainIDReq{}
	mi := &file_job_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayChainIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayChainIDReq) ProtoMessage() {}

func (x *RelayChainIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayChainIDReq.ProtoReflect.Descriptor instead.
func (*RelayChainIDReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{15}
}

func (x *RelayChainIDReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RelayTokenKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayTokenKeyReq) Reset() {
	*x = RelayTokenKeyReq{}
	mi := &file_job_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayTokenKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayTokenKeyReq) ProtoMessage() {}

func (x *RelayTokenKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayTokenKeyReq.ProtoReflect.Descriptor instead.
func (*RelayTokenKeyReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{16}
}

func (x *RelayTokenKeyReq) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *RelayTokenKeyReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RelayChainInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt      *int64                 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	UpdatedAt      *int64                 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	Slug           *string                `protobuf:"bytes,4,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	Name           *string                `protobuf:"bytes,5,opt,name=name,proto3,oneof" json:"name,omitempty"`
	LogoUrl        *string                `protobuf:"bytes,6,opt,name=logo_url,json=logoUrl,proto3,oneof" json:"logo_url,omitempty"`
	Type           *string                `protobuf:"bytes,7,opt,name=type,proto3,oneof" json:"type,omitempty"`
	VmType         *string                `protobuf:"bytes,8,opt,name=vm_type,json=vmType,proto3,oneof" json:"vm_type,omitempty"`
	Protocol       *string                `protobuf:"bytes,9,opt,name=protocol,proto3,oneof" json:"protocol,omitempty"`
	BaseChainId    *string                `protobuf:"bytes,10,opt,name=base_chain_id,json=baseChainId,proto3,oneof" json:"base_chain_id,omitempty"`
	ExplorerUrl    *string                `protobuf:"bytes,11,opt,name=explorer_url,json=explorerUrl,proto3,oneof" json:"explorer_url,omitempty"`
	ExplorerName   *string                `protobuf:"bytes,12,opt,name=explorer_name,json=explorerName,proto3,oneof" json:"explorer_name,omitempty"`
	RpcUrl         *string                `protobuf:"bytes,13,opt,name=rpc_url,json=rpcUrl,proto3,oneof" json:"rpc_url,omitempty"`
	WsRpcUrl       *string                `protobuf:"bytes,14,opt,name=ws_rpc_url,json=wsRpcUrl,proto3,oneof" json:"ws_rpc_url,omitempty"`
	NativeSymbol   *string                `protobuf:"bytes,15,opt,name=native_symbol,json=nativeSymbol,proto3,oneof" json:"native_symbol,omitempty"`
	NativeDecimals *int64                 `protobuf:"varint,16,opt,name=native_decimals,json=nativeDecimals,proto3,oneof" json:"native_decimals,omitempty"`
	DepositEnabled *bool                  `protobuf:"varint,17,opt,name=deposit_enabled,json=depositEnabled,proto3,oneof" json:"deposit_enabled,omitempty"`
	TokenSupport   *string                `protobuf:"bytes,18,opt,name=token_support,json=tokenSupport,proto3,oneof" json:"token_support,omitempty"`
	Disabled       *bool                  `protobuf:"varint,19,opt,name=disabled,proto3,oneof" json:"disabled,omitempty"`
	Supported      *bool                  `protobuf:"varint,20,opt,name=supported,proto3,oneof" json:"supported,omitempty"`
	Enabled        *bool                  `protobuf:"varint,21,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	RawData        *string                `protobuf:"bytes,22,opt,name=raw_data,json=rawData,proto3,oneof" json:"raw_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RelayChainInfo) Reset() {
	*x = RelayChainInfo{}
	mi := &file_job_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayChainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayChainInfo) ProtoMessage() {}

func (x *RelayChainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayChainInfo.ProtoReflect.Descriptor instead.
func (*RelayChainInfo) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{17}
}

func (x *RelayChainInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RelayChainInfo) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *RelayChainInfo) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *RelayChainInfo) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *RelayChainInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RelayChainInfo) GetLogoUrl() string {
	if x != nil && x.LogoUrl != nil {
		return *x.LogoUrl
	}
	return ""
}

func (x *RelayChainInfo) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *RelayChainInfo) GetVmType() string {
	if x != nil && x.VmType != nil {
		return *x.VmType
	}
	return ""
}

func (x *RelayChainInfo) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

func (x *RelayChainInfo) GetBaseChainId() string {
	if x != nil && x.BaseChainId != nil {
		return *x.BaseChainId
	}
	return ""
}

func (x *RelayChainInfo) GetExplorerUrl() string {
	if x != nil && x.ExplorerUrl != nil {
		return *x.ExplorerUrl
	}
	return ""
}

func (x *RelayChainInfo) GetExplorerName() string {
	if x != nil && x.ExplorerName != nil {
		return *x.ExplorerName
	}
	return ""
}

func (x *RelayChainInfo) GetRpcUrl() string {
	if x != nil && x.RpcUrl != nil {
		return *x.RpcUrl
	}
	return ""
}

func (x *RelayChainInfo) GetWsRpcUrl() string {
	if x != nil && x.WsRpcUrl != nil {
		return *x.WsRpcUrl
	}
	return ""
}

func (x *RelayChainInfo) GetNativeSymbol() string {
	if x != nil && x.NativeSymbol != nil {
		return *x.NativeSymbol
	}
	return ""
}

func (x *RelayChainInfo) GetNativeDecimals() int64 {
	if x != nil && x.NativeDecimals != nil {
		return *x.NativeDecimals
	}
	return 0
}

func (x *RelayChainInfo) GetDepositEnabled() bool {
	if x != nil && x.DepositEnabled != nil {
		return *x.DepositEnabled
	}
	return false
}

func (x *RelayChainInfo) GetTokenSupport() string {
	if x != nil && x.TokenSupport != nil {
		return *x.TokenSupport
	}
	return ""
}

func (x *RelayChainInfo) GetDisabled() bool {
	if x != nil && x.Disabled != nil {
		return *x.Disabled
	}
	return false
}

func (x *RelayChainInfo) GetSupported() bool {
	if x != nil && x.Supported != nil {
		return *x.Supported
	}
	return false
}

func (x *RelayChainInfo) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *RelayChainInfo) GetRawData() string {
	if x != nil && x.RawData != nil {
		return *x.RawData
	}
	return ""
}

type RelayChainListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Ids           []int64                `protobuf:"varint,3,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Type          *string                `protobuf:"bytes,5,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Enabled       *bool                  `protobuf:"varint,6,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	Supported     *bool                  `protobuf:"varint,7,opt,name=supported,proto3,oneof" json:"supported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayChainListReq) Reset() {
	*x = RelayChainListReq{}
	mi := &file_job_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayChainListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayChainListReq) ProtoMessage() {}

func (x *RelayChainListReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayChainListReq.ProtoReflect.Descriptor instead.
func (*RelayChainListReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{18}
}

func (x *RelayChainListReq) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RelayChainListReq) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *RelayChainListReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *RelayChainListReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RelayChainListReq) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *RelayChainListReq) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *RelayChainListReq) GetSupported() bool {
	if x != nil && x.Supported != nil {
		return *x.Supported
	}
	return false
}

type RelayChainListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*RelayChainInfo      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayChainListResp) Reset() {
	*x = RelayChainListResp{}
	mi := &file_job_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayChainListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayChainListResp) ProtoMessage() {}

func (x *RelayChainListResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayChainListResp.ProtoReflect.Descriptor instead.
func (*RelayChainListResp) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{19}
}

func (x *RelayChainListResp) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RelayChainListResp) GetData() []*RelayChainInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type RelayTokenInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChainId          int64                  `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	CreatedAt        *int64                 `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	UpdatedAt        *int64                 `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	Address          *string                `protobuf:"bytes,5,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Name             *string                `protobuf:"bytes,6,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Symbol           *string                `protobuf:"bytes,7,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	LogoUrl          *string                `protobuf:"bytes,8,opt,name=logo_url,json=logoUrl,proto3,oneof" json:"logo_url,omitempty"`
	Decimals         *int64                 `protobuf:"varint,9,opt,name=decimals,proto3,oneof" json:"decimals,omitempty"`
	Native           *bool                  `protobuf:"varint,10,opt,name=native,proto3,oneof" json:"native,omitempty"`
	Stablecoin       *bool                  `protobuf:"varint,11,opt,name=stablecoin,proto3,oneof" json:"stablecoin,omitempty"`
	SupportsBridging *bool                  `protobuf:"varint,12,opt,name=supports_bridging,json=supportsBridging,proto3,oneof" json:"supports_bridging,omitempty"`
	SupportsPermit   *bool                  `protobuf:"varint,13,opt,name=supports_permit,json=supportsPermit,proto3,oneof" json:"supports_permit,omitempty"`
	IsFeatured       *bool                  `protobuf:"varint,14,opt,name=is_featured,json=isFeatured,proto3,oneof" json:"is_featured,omitempty"`
	IsSolver         *bool                  `protobuf:"varint,15,opt,name=is_solver,json=isSolver,proto3,oneof" json:"is_solver,omitempty"`
	IsErc20          *bool                  `protobuf:"varint,16,opt,name=is_erc20,json=isErc20,proto3,oneof" json:"is_erc20,omitempty"`
	Supported        *bool                  `protobuf:"varint,17,opt,name=supported,proto3,oneof" json:"supported,omitempty"`
	RawData          *string                `protobuf:"bytes,18,opt,name=raw_data,json=rawData,proto3,oneof" json:"raw_data,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RelayTokenInfo) Reset() {
	*x = RelayTokenInfo{}
	mi := &file_job_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayTokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayTokenInfo) ProtoMessage() {}

func (x *RelayTokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayTokenInfo.ProtoReflect.Descriptor instead.
func (*RelayTokenInfo) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{20}
}

func (x *RelayTokenInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RelayTokenInfo) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *RelayTokenInfo) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *RelayTokenInfo) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *RelayTokenInfo) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *RelayTokenInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RelayTokenInfo) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *RelayTokenInfo) GetLogoUrl() string {
	if x != nil && x.LogoUrl != nil {
		return *x.LogoUrl
	}
	return ""
}

func (x *RelayTokenInfo) GetDecimals() int64 {
	if x != nil && x.Decimals != nil {
		return *x.Decimals
	}
	return 0
}

func (x *RelayTokenInfo) GetNative() bool {
	if x != nil && x.Native != nil {
		return *x.Native
	}
	return false
}

func (x *RelayTokenInfo) GetStablecoin() bool {
	if x != nil && x.Stablecoin != nil {
		return *x.Stablecoin
	}
	return false
}

func (x *RelayTokenInfo) GetSupportsBridging() bool {
	if x != nil && x.SupportsBridging != nil {
		return *x.SupportsBridging
	}
	return false
}

func (x *RelayTokenInfo) GetSupportsPermit() bool {
	if x != nil && x.SupportsPermit != nil {
		return *x.SupportsPermit
	}
	return false
}

func (x *RelayTokenInfo) GetIsFeatured() bool {
	if x != nil && x.IsFeatured != nil {
		return *x.IsFeatured
	}
	return false
}

func (x *RelayTokenInfo) GetIsSolver() bool {
	if x != nil && x.IsSolver != nil {
		return *x.IsSolver
	}
	return false
}

func (x *RelayTokenInfo) GetIsErc20() bool {
	if x != nil && x.IsErc20 != nil {
		return *x.IsErc20
	}
	return false
}

func (x *RelayTokenInfo) GetSupported() bool {
	if x != nil && x.Supported != nil {
		return *x.Supported
	}
	return false
}

func (x *RelayTokenInfo) GetRawData() string {
	if x != nil && x.RawData != nil {
		return *x.RawData
	}
	return ""
}

type RelayTokenListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ChainIds      []int64                `protobuf:"varint,3,rep,packed,name=chain_ids,json=chainIds,proto3" json:"chain_ids,omitempty"`
	Ids           []string               `protobuf:"bytes,4,rep,name=ids,proto3" json:"ids,omitempty"`
	Name          *string                `protobuf:"bytes,5,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Symbol        *string                `protobuf:"bytes,6,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	Address       *string                `protobuf:"bytes,7,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Supported     *bool                  `protobuf:"varint,8,opt,name=supported,proto3,oneof" json:"supported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayTokenListReq) Reset() {
	*x = RelayTokenListReq{}
	mi := &file_job_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayTokenListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayTokenListReq) ProtoMessage() {}

func (x *RelayTokenListReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayTokenListReq.ProtoReflect.Descriptor instead.
func (*RelayTokenListReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{21}
}

func (x *RelayTokenListReq) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RelayTokenListReq) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *RelayTokenListReq) GetChainIds() []int64 {
	if x != nil {
		return x.ChainIds
	}
	return nil
}

func (x *RelayTokenListReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *RelayTokenListReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RelayTokenListReq) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *RelayTokenListReq) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *RelayTokenListReq) GetSupported() bool {
	if x != nil && x.Supported != nil {
		return *x.Supported
	}
	return false
}

type RelayTokenListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*RelayTokenInfo      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayTokenListResp) Reset() {
	*x = RelayTokenListResp{}
	mi := &file_job_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayTokenListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayTokenListResp) ProtoMessage() {}

func (x *RelayTokenListResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayTokenListResp.ProtoReflect.Descriptor instead.
func (*RelayTokenListResp) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{22}
}

func (x *RelayTokenListResp) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RelayTokenListResp) GetData() []*RelayTokenInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_job_proto protoreflect.FileDescriptor

const file_job_proto_rawDesc = "" +
	"\n" +
	"\tjob.proto\x12\x03job\".\n" +
	"\n" +
	"BaseIDResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x1c\n" +
	"\bBaseResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"0\n" +
	"\fBaseUUIDResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\a\n" +
	"\x05Empty\"\x17\n" +
	"\x05IDReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x1a\n" +
	"\x06IDsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\">\n" +
	"\vPageInfoReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\"\xa1\x03\n" +
	"\bTaskInfo\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x04H\x00R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03H\x01R\tcreatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03H\x02R\tupdatedAt\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\rH\x03R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x05 \x01(\tH\x04R\x04name\x88\x01\x01\x12\"\n" +
	"\n" +
	"task_group\x18\x06 \x01(\tH\x05R\ttaskGroup\x88\x01\x01\x12,\n" +
	"\x0fcron_expression\x18\a \x01(\tH\x06R\x0ecronExpression\x88\x01\x01\x12\x1d\n" +
	"\apattern\x18\b \x01(\tH\aR\apattern\x88\x01\x01\x12\x1d\n" +
	"\apayload\x18\t \x01(\tH\bR\apayload\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_atB\t\n" +
	"\a_statusB\a\n" +
	"\x05_nameB\r\n" +
	"\v_task_groupB\x12\n" +
	"\x10_cron_expressionB\n" +
	"\n" +
	"\b_patternB\n" +
	"\n" +
	"\b_payload\"\x93\x01\n" +
	"\vTaskListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\"\n" +
	"\n" +
	"task_group\x18\x04 \x01(\tH\x01R\ttaskGroup\x88\x01\x01B\a\n" +
	"\x05_nameB\r\n" +
	"\v_task_group\"G\n" +
	"\fTaskListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12!\n" +
	"\x04data\x18\x02 \x03(\v2\r.job.TaskInfoR\x04data\"\xa0\x02\n" +
	"\vTaskLogInfo\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x04H\x00R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03H\x01R\tcreatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03H\x02R\tupdatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03H\x03R\tstartedAt\x88\x01\x01\x12$\n" +
	"\vfinished_at\x18\x05 \x01(\x03H\x04R\n" +
	"finishedAt\x88\x01\x01\x12\x1b\n" +
	"\x06result\x18\x06 \x01(\rH\x05R\x06result\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_atB\r\n" +
	"\v_started_atB\x0e\n" +
	"\f_finished_atB\t\n" +
	"\a_result\"\x93\x01\n" +
	"\x0eTaskLogListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\x12\x1c\n" +
	"\atask_id\x18\x03 \x01(\x04H\x00R\x06taskId\x88\x01\x01\x12\x1b\n" +
	"\x06result\x18\x04 \x01(\rH\x01R\x06result\x88\x01\x01B\n" +
	"\n" +
	"\b_task_idB\t\n" +
	"\a_result\"M\n" +
	"\x0fTaskLogListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12$\n" +
	"\x04data\x18\x02 \x03(\v2\x10.job.TaskLogInfoR\x04data\"\x19\n" +
	"\aUUIDReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\bUUIDsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"!\n" +
	"\x0fRelayChainIDReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"=\n" +
	"\x10RelayTokenKeyReq\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xb0\b\n" +
	"\x0eRelayChainInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\"\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03H\x00R\tcreatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03H\x01R\tupdatedAt\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x04 \x01(\tH\x02R\x04slug\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x05 \x01(\tH\x03R\x04name\x88\x01\x01\x12\x1e\n" +
	"\blogo_url\x18\x06 \x01(\tH\x04R\alogoUrl\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\a \x01(\tH\x05R\x04type\x88\x01\x01\x12\x1c\n" +
	"\avm_type\x18\b \x01(\tH\x06R\x06vmType\x88\x01\x01\x12\x1f\n" +
	"\bprotocol\x18\t \x01(\tH\aR\bprotocol\x88\x01\x01\x12'\n" +
	"\rbase_chain_id\x18\n" +
	" \x01(\tH\bR\vbaseChainId\x88\x01\x01\x12&\n" +
	"\fexplorer_url\x18\v \x01(\tH\tR\vexplorerUrl\x88\x01\x01\x12(\n" +
	"\rexplorer_name\x18\f \x01(\tH\n" +
	"R\fexplorerName\x88\x01\x01\x12\x1c\n" +
	"\arpc_url\x18\r \x01(\tH\vR\x06rpcUrl\x88\x01\x01\x12!\n" +
	"\n" +
	"ws_rpc_url\x18\x0e \x01(\tH\fR\bwsRpcUrl\x88\x01\x01\x12(\n" +
	"\rnative_symbol\x18\x0f \x01(\tH\rR\fnativeSymbol\x88\x01\x01\x12,\n" +
	"\x0fnative_decimals\x18\x10 \x01(\x03H\x0eR\x0enativeDecimals\x88\x01\x01\x12,\n" +
	"\x0fdeposit_enabled\x18\x11 \x01(\bH\x0fR\x0edepositEnabled\x88\x01\x01\x12(\n" +
	"\rtoken_support\x18\x12 \x01(\tH\x10R\ftokenSupport\x88\x01\x01\x12\x1f\n" +
	"\bdisabled\x18\x13 \x01(\bH\x11R\bdisabled\x88\x01\x01\x12!\n" +
	"\tsupported\x18\x14 \x01(\bH\x12R\tsupported\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x15 \x01(\bH\x13R\aenabled\x88\x01\x01\x12\x1e\n" +
	"\braw_data\x18\x16 \x01(\tH\x14R\arawData\x88\x01\x01B\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_atB\a\n" +
	"\x05_slugB\a\n" +
	"\x05_nameB\v\n" +
	"\t_logo_urlB\a\n" +
	"\x05_typeB\n" +
	"\n" +
	"\b_vm_typeB\v\n" +
	"\t_protocolB\x10\n" +
	"\x0e_base_chain_idB\x0f\n" +
	"\r_explorer_urlB\x10\n" +
	"\x0e_explorer_nameB\n" +
	"\n" +
	"\b_rpc_urlB\r\n" +
	"\v_ws_rpc_urlB\x10\n" +
	"\x0e_native_symbolB\x12\n" +
	"\x10_native_decimalsB\x12\n" +
	"\x10_deposit_enabledB\x10\n" +
	"\x0e_token_supportB\v\n" +
	"\t_disabledB\f\n" +
	"\n" +
	"_supportedB\n" +
	"\n" +
	"\b_enabledB\v\n" +
	"\t_raw_data\"\xf6\x01\n" +
	"\x11RelayChainListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\x03R\x03ids\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x05 \x01(\tH\x01R\x04type\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x06 \x01(\bH\x02R\aenabled\x88\x01\x01\x12!\n" +
	"\tsupported\x18\a \x01(\bH\x03R\tsupported\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_typeB\n" +
	"\n" +
	"\b_enabledB\f\n" +
	"\n" +
	"_supported\"S\n" +
	"\x12RelayChainListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12'\n" +
	"\x04data\x18\x02 \x03(\v2\x13.job.RelayChainInfoR\x04data\"\xc8\x06\n" +
	"\x0eRelayTokenInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x03R\achainId\x12\"\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03H\x00R\tcreatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03H\x01R\tupdatedAt\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x05 \x01(\tH\x02R\aaddress\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x06 \x01(\tH\x03R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\a \x01(\tH\x04R\x06symbol\x88\x01\x01\x12\x1e\n" +
	"\blogo_url\x18\b \x01(\tH\x05R\alogoUrl\x88\x01\x01\x12\x1f\n" +
	"\bdecimals\x18\t \x01(\x03H\x06R\bdecimals\x88\x01\x01\x12\x1b\n" +
	"\x06native\x18\n" +
	" \x01(\bH\aR\x06native\x88\x01\x01\x12#\n" +
	"\n" +
	"stablecoin\x18\v \x01(\bH\bR\n" +
	"stablecoin\x88\x01\x01\x120\n" +
	"\x11supports_bridging\x18\f \x01(\bH\tR\x10supportsBridging\x88\x01\x01\x12,\n" +
	"\x0fsupports_permit\x18\r \x01(\bH\n" +
	"R\x0esupportsPermit\x88\x01\x01\x12$\n" +
	"\vis_featured\x18\x0e \x01(\bH\vR\n" +
	"isFeatured\x88\x01\x01\x12 \n" +
	"\tis_solver\x18\x0f \x01(\bH\fR\bisSolver\x88\x01\x01\x12\x1e\n" +
	"\bis_erc20\x18\x10 \x01(\bH\rR\aisErc20\x88\x01\x01\x12!\n" +
	"\tsupported\x18\x11 \x01(\bH\x0eR\tsupported\x88\x01\x01\x12\x1e\n" +
	"\braw_data\x18\x12 \x01(\tH\x0fR\arawData\x88\x01\x01B\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_atB\n" +
	"\n" +
	"\b_addressB\a\n" +
	"\x05_nameB\t\n" +
	"\a_symbolB\v\n" +
	"\t_logo_urlB\v\n" +
	"\t_decimalsB\t\n" +
	"\a_nativeB\r\n" +
	"\v_stablecoinB\x14\n" +
	"\x12_supports_bridgingB\x12\n" +
	"\x10_supports_permitB\x0e\n" +
	"\f_is_featuredB\f\n" +
	"\n" +
	"_is_solverB\v\n" +
	"\t_is_erc20B\f\n" +
	"\n" +
	"_supportedB\v\n" +
	"\t_raw_data\"\x99\x02\n" +
	"\x11RelayTokenListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\x12\x1b\n" +
	"\tchain_ids\x18\x03 \x03(\x03R\bchainIds\x12\x10\n" +
	"\x03ids\x18\x04 \x03(\tR\x03ids\x12\x17\n" +
	"\x04name\x18\x05 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\x06 \x01(\tH\x01R\x06symbol\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\a \x01(\tH\x02R\aaddress\x88\x01\x01\x12!\n" +
	"\tsupported\x18\b \x01(\bH\x03R\tsupported\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_symbolB\n" +
	"\n" +
	"\b_addressB\f\n" +
	"\n" +
	"_supported\"S\n" +
	"\x12RelayTokenListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12'\n" +
	"\x04data\x18\x02 \x03(\v2\x13.job.RelayTokenInfoR\x04data2\xd5\x06\n" +
	"\x03Job\x12)\n" +
	"\finitDatabase\x12\n" +
	".job.Empty\x1a\r.job.BaseResp\x12,\n" +
	"\x0finitRelayTables\x12\n" +
	".job.Empty\x1a\r.job.BaseResp\x12,\n" +
	"\n" +
	"createTask\x12\r.job.TaskInfo\x1a\x0f.job.BaseIDResp\x12*\n" +
	"\n" +
	"updateTask\x12\r.job.TaskInfo\x1a\r.job.BaseResp\x122\n" +
	"\vgetTaskList\x12\x10.job.TaskListReq\x1a\x11.job.TaskListResp\x12(\n" +
	"\vgetTaskById\x12\n" +
	".job.IDReq\x1a\r.job.TaskInfo\x12(\n" +
	"\n" +
	"deleteTask\x12\v.job.IDsReq\x1a\r.job.BaseResp\x122\n" +
	"\rcreateTaskLog\x12\x10.job.TaskLogInfo\x1a\x0f.job.BaseIDResp\x120\n" +
	"\rupdateTaskLog\x12\x10.job.TaskLogInfo\x1a\r.job.BaseResp\x12;\n" +
	"\x0egetTaskLogList\x12\x13.job.TaskLogListReq\x1a\x14.job.TaskLogListResp\x12.\n" +
	"\x0egetTaskLogById\x12\n" +
	".job.IDReq\x1a\x10.job.TaskLogInfo\x12+\n" +
	"\rdeleteTaskLog\x12\v.job.IDsReq\x1a\r.job.BaseResp\x12D\n" +
	"\x11getRelayChainList\x12\x16.job.RelayChainListReq\x1a\x17.job.RelayChainListResp\x12>\n" +
	"\x11getRelayChainById\x12\x14.job.RelayChainIDReq\x1a\x13.job.RelayChainInfo\x12D\n" +
	"\x11getRelayTokenList\x12\x16.job.RelayTokenListReq\x1a\x17.job.RelayTokenListResp\x12G\n" +
	"\x19getRelayTokenByChainAndId\x12\x15.job.RelayTokenKeyReq\x1a\x13.job.RelayTokenInfoB\aZ\x05./jobb\x06proto3"

var (
	file_job_proto_rawDescOnce sync.Once
	file_job_proto_rawDescData []byte
)

func file_job_proto_rawDescGZIP() []byte {
	file_job_proto_rawDescOnce.Do(func() {
		file_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)))
	})
	return file_job_proto_rawDescData
}

var file_job_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_job_proto_goTypes = []any{
	(*BaseIDResp)(nil),         // 0: job.BaseIDResp
	(*BaseResp)(nil),           // 1: job.BaseResp
	(*BaseUUIDResp)(nil),       // 2: job.BaseUUIDResp
	(*Empty)(nil),              // 3: job.Empty
	(*IDReq)(nil),              // 4: job.IDReq
	(*IDsReq)(nil),             // 5: job.IDsReq
	(*PageInfoReq)(nil),        // 6: job.PageInfoReq
	(*TaskInfo)(nil),           // 7: job.TaskInfo
	(*TaskListReq)(nil),        // 8: job.TaskListReq
	(*TaskListResp)(nil),       // 9: job.TaskListResp
	(*TaskLogInfo)(nil),        // 10: job.TaskLogInfo
	(*TaskLogListReq)(nil),     // 11: job.TaskLogListReq
	(*TaskLogListResp)(nil),    // 12: job.TaskLogListResp
	(*UUIDReq)(nil),            // 13: job.UUIDReq
	(*UUIDsReq)(nil),           // 14: job.UUIDsReq
	(*RelayChainIDReq)(nil),    // 15: job.RelayChainIDReq
	(*RelayTokenKeyReq)(nil),   // 16: job.RelayTokenKeyReq
	(*RelayChainInfo)(nil),     // 17: job.RelayChainInfo
	(*RelayChainListReq)(nil),  // 18: job.RelayChainListReq
	(*RelayChainListResp)(nil), // 19: job.RelayChainListResp
	(*RelayTokenInfo)(nil),     // 20: job.RelayTokenInfo
	(*RelayTokenListReq)(nil),  // 21: job.RelayTokenListReq
	(*RelayTokenListResp)(nil), // 22: job.RelayTokenListResp
}
var file_job_proto_depIdxs = []int32{
	7,  // 0: job.TaskListResp.data:type_name -> job.TaskInfo
	10, // 1: job.TaskLogListResp.data:type_name -> job.TaskLogInfo
	17, // 2: job.RelayChainListResp.data:type_name -> job.RelayChainInfo
	20, // 3: job.RelayTokenListResp.data:type_name -> job.RelayTokenInfo
	3,  // 4: job.Job.initDatabase:input_type -> job.Empty
	3,  // 5: job.Job.initRelayTables:input_type -> job.Empty
	7,  // 6: job.Job.createTask:input_type -> job.TaskInfo
	7,  // 7: job.Job.updateTask:input_type -> job.TaskInfo
	8,  // 8: job.Job.getTaskList:input_type -> job.TaskListReq
	4,  // 9: job.Job.getTaskById:input_type -> job.IDReq
	5,  // 10: job.Job.deleteTask:input_type -> job.IDsReq
	10, // 11: job.Job.createTaskLog:input_type -> job.TaskLogInfo
	10, // 12: job.Job.updateTaskLog:input_type -> job.TaskLogInfo
	11, // 13: job.Job.getTaskLogList:input_type -> job.TaskLogListReq
	4,  // 14: job.Job.getTaskLogById:input_type -> job.IDReq
	5,  // 15: job.Job.deleteTaskLog:input_type -> job.IDsReq
	18, // 16: job.Job.getRelayChainList:input_type -> job.RelayChainListReq
	15, // 17: job.Job.getRelayChainById:input_type -> job.RelayChainIDReq
	21, // 18: job.Job.getRelayTokenList:input_type -> job.RelayTokenListReq
	16, // 19: job.Job.getRelayTokenByChainAndId:input_type -> job.RelayTokenKeyReq
	1,  // 20: job.Job.initDatabase:output_type -> job.BaseResp
	1,  // 21: job.Job.initRelayTables:output_type -> job.BaseResp
	0,  // 22: job.Job.createTask:output_type -> job.BaseIDResp
	1,  // 23: job.Job.updateTask:output_type -> job.BaseResp
	9,  // 24: job.Job.getTaskList:output_type -> job.TaskListResp
	7,  // 25: job.Job.getTaskById:output_type -> job.TaskInfo
	1,  // 26: job.Job.deleteTask:output_type -> job.BaseResp
	0,  // 27: job.Job.createTaskLog:output_type -> job.BaseIDResp
	1,  // 28: job.Job.updateTaskLog:output_type -> job.BaseResp
	12, // 29: job.Job.getTaskLogList:output_type -> job.TaskLogListResp
	10, // 30: job.Job.getTaskLogById:output_type -> job.TaskLogInfo
	1,  // 31: job.Job.deleteTaskLog:output_type -> job.BaseResp
	19, // 32: job.Job.getRelayChainList:output_type -> job.RelayChainListResp
	17, // 33: job.Job.getRelayChainById:output_type -> job.RelayChainInfo
	22, // 34: job.Job.getRelayTokenList:output_type -> job.RelayTokenListResp
	20, // 35: job.Job.getRelayTokenByChainAndId:output_type -> job.RelayTokenInfo
	20, // [20:36] is the sub-list for method output_type
	4,  // [4:20] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_job_proto_init() }
func file_job_proto_init() {
	if File_job_proto != nil {
		return
	}
	file_job_proto_msgTypes[7].OneofWrappers = []any{}
	file_job_proto_msgTypes[8].OneofWrappers = []any{}
	file_job_proto_msgTypes[10].OneofWrappers = []any{}
	file_job_proto_msgTypes[11].OneofWrappers = []any{}
	file_job_proto_msgTypes[17].OneofWrappers = []any{}
	file_job_proto_msgTypes[18].OneofWrappers = []any{}
	file_job_proto_msgTypes[20].OneofWrappers = []any{}
	file_job_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_proto_goTypes,
		DependencyIndexes: file_job_proto_depIdxs,
		MessageInfos:      file_job_proto_msgTypes,
	}.Build()
	File_job_proto = out.File
	file_job_proto_goTypes = nil
	file_job_proto_depIdxs = nil
}
