// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: job.proto

package job

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Job_InitDatabase_FullMethodName              = "/job.Job/initDatabase"
	Job_InitRelayTables_FullMethodName           = "/job.Job/initRelayTables"
	Job_CreateTask_FullMethodName                = "/job.Job/createTask"
	Job_UpdateTask_FullMethodName                = "/job.Job/updateTask"
	Job_GetTaskList_FullMethodName               = "/job.Job/getTaskList"
	Job_GetTaskById_FullMethodName               = "/job.Job/getTaskById"
	Job_DeleteTask_FullMethodName                = "/job.Job/deleteTask"
	Job_CreateTaskLog_FullMethodName             = "/job.Job/createTaskLog"
	Job_UpdateTaskLog_FullMethodName             = "/job.Job/updateTaskLog"
	Job_GetTaskLogList_FullMethodName            = "/job.Job/getTaskLogList"
	Job_GetTaskLogById_FullMethodName            = "/job.Job/getTaskLogById"
	Job_DeleteTaskLog_FullMethodName             = "/job.Job/deleteTaskLog"
	Job_GetRelayChainList_FullMethodName         = "/job.Job/getRelayChainList"
	Job_GetRelayChainById_FullMethodName         = "/job.Job/getRelayChainById"
	Job_GetRelayTokenList_FullMethodName         = "/job.Job/getRelayTokenList"
	Job_GetRelayTokenByChainAndId_FullMethodName = "/job.Job/getRelayTokenByChainAndId"
	Job_GetClientRelayChainList_FullMethodName   = "/job.Job/getClientRelayChainList"
	Job_GetClientRelayTokenList_FullMethodName   = "/job.Job/getClientRelayTokenList"
)

// JobClient is the client API for Job service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobClient interface {
	// group: base
	InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
	// group: base
	InitRelayTables(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
	// Task management
	// group: task
	CreateTask(ctx context.Context, in *TaskInfo, opts ...grpc.CallOption) (*BaseIDResp, error)
	// group: task
	UpdateTask(ctx context.Context, in *TaskInfo, opts ...grpc.CallOption) (*BaseResp, error)
	// group: task
	GetTaskList(ctx context.Context, in *TaskListReq, opts ...grpc.CallOption) (*TaskListResp, error)
	// group: task
	GetTaskById(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*TaskInfo, error)
	// group: task
	DeleteTask(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseResp, error)
	// TaskLog management
	// group: tasklog
	CreateTaskLog(ctx context.Context, in *TaskLogInfo, opts ...grpc.CallOption) (*BaseIDResp, error)
	// group: tasklog
	UpdateTaskLog(ctx context.Context, in *TaskLogInfo, opts ...grpc.CallOption) (*BaseResp, error)
	// group: tasklog
	GetTaskLogList(ctx context.Context, in *TaskLogListReq, opts ...grpc.CallOption) (*TaskLogListResp, error)
	// group: tasklog
	GetTaskLogById(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*TaskLogInfo, error)
	// group: tasklog
	DeleteTaskLog(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseResp, error)
	// RelayChain query
	// group: relay
	GetRelayChainList(ctx context.Context, in *RelayChainListReq, opts ...grpc.CallOption) (*RelayChainListResp, error)
	// group: relay
	GetRelayChainById(ctx context.Context, in *RelayChainIDReq, opts ...grpc.CallOption) (*RelayChainInfo, error)
	// RelayToken query
	// group: relay
	GetRelayTokenList(ctx context.Context, in *RelayTokenListReq, opts ...grpc.CallOption) (*RelayTokenListResp, error)
	// group: relay
	GetRelayTokenByChainAndId(ctx context.Context, in *RelayTokenKeyReq, opts ...grpc.CallOption) (*RelayTokenInfo, error)
	// Client RelayChain query
	// group: relay
	GetClientRelayChainList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ClientRelayChainListResp, error)
	// Client RelayToken query
	// group: relay
	GetClientRelayTokenList(ctx context.Context, in *ClientRelayTokenListReq, opts ...grpc.CallOption) (*ClientRelayTokenListResp, error)
}

type jobClient struct {
	cc grpc.ClientConnInterface
}

func NewJobClient(cc grpc.ClientConnInterface) JobClient {
	return &jobClient{cc}
}

func (c *jobClient) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Job_InitDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) InitRelayTables(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Job_InitRelayTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) CreateTask(ctx context.Context, in *TaskInfo, opts ...grpc.CallOption) (*BaseIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseIDResp)
	err := c.cc.Invoke(ctx, Job_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) UpdateTask(ctx context.Context, in *TaskInfo, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Job_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) GetTaskList(ctx context.Context, in *TaskListReq, opts ...grpc.CallOption) (*TaskListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskListResp)
	err := c.cc.Invoke(ctx, Job_GetTaskList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) GetTaskById(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*TaskInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskInfo)
	err := c.cc.Invoke(ctx, Job_GetTaskById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) DeleteTask(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Job_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) CreateTaskLog(ctx context.Context, in *TaskLogInfo, opts ...grpc.CallOption) (*BaseIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseIDResp)
	err := c.cc.Invoke(ctx, Job_CreateTaskLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) UpdateTaskLog(ctx context.Context, in *TaskLogInfo, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Job_UpdateTaskLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) GetTaskLogList(ctx context.Context, in *TaskLogListReq, opts ...grpc.CallOption) (*TaskLogListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskLogListResp)
	err := c.cc.Invoke(ctx, Job_GetTaskLogList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) GetTaskLogById(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*TaskLogInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskLogInfo)
	err := c.cc.Invoke(ctx, Job_GetTaskLogById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) DeleteTaskLog(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Job_DeleteTaskLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) GetRelayChainList(ctx context.Context, in *RelayChainListReq, opts ...grpc.CallOption) (*RelayChainListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayChainListResp)
	err := c.cc.Invoke(ctx, Job_GetRelayChainList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) GetRelayChainById(ctx context.Context, in *RelayChainIDReq, opts ...grpc.CallOption) (*RelayChainInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayChainInfo)
	err := c.cc.Invoke(ctx, Job_GetRelayChainById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) GetRelayTokenList(ctx context.Context, in *RelayTokenListReq, opts ...grpc.CallOption) (*RelayTokenListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayTokenListResp)
	err := c.cc.Invoke(ctx, Job_GetRelayTokenList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) GetRelayTokenByChainAndId(ctx context.Context, in *RelayTokenKeyReq, opts ...grpc.CallOption) (*RelayTokenInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayTokenInfo)
	err := c.cc.Invoke(ctx, Job_GetRelayTokenByChainAndId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) GetClientRelayChainList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ClientRelayChainListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientRelayChainListResp)
	err := c.cc.Invoke(ctx, Job_GetClientRelayChainList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) GetClientRelayTokenList(ctx context.Context, in *ClientRelayTokenListReq, opts ...grpc.CallOption) (*ClientRelayTokenListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientRelayTokenListResp)
	err := c.cc.Invoke(ctx, Job_GetClientRelayTokenList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServer is the server API for Job service.
// All implementations must embed UnimplementedJobServer
// for forward compatibility.
type JobServer interface {
	// group: base
	InitDatabase(context.Context, *Empty) (*BaseResp, error)
	// group: base
	InitRelayTables(context.Context, *Empty) (*BaseResp, error)
	// Task management
	// group: task
	CreateTask(context.Context, *TaskInfo) (*BaseIDResp, error)
	// group: task
	UpdateTask(context.Context, *TaskInfo) (*BaseResp, error)
	// group: task
	GetTaskList(context.Context, *TaskListReq) (*TaskListResp, error)
	// group: task
	GetTaskById(context.Context, *IDReq) (*TaskInfo, error)
	// group: task
	DeleteTask(context.Context, *IDsReq) (*BaseResp, error)
	// TaskLog management
	// group: tasklog
	CreateTaskLog(context.Context, *TaskLogInfo) (*BaseIDResp, error)
	// group: tasklog
	UpdateTaskLog(context.Context, *TaskLogInfo) (*BaseResp, error)
	// group: tasklog
	GetTaskLogList(context.Context, *TaskLogListReq) (*TaskLogListResp, error)
	// group: tasklog
	GetTaskLogById(context.Context, *IDReq) (*TaskLogInfo, error)
	// group: tasklog
	DeleteTaskLog(context.Context, *IDsReq) (*BaseResp, error)
	// RelayChain query
	// group: relay
	GetRelayChainList(context.Context, *RelayChainListReq) (*RelayChainListResp, error)
	// group: relay
	GetRelayChainById(context.Context, *RelayChainIDReq) (*RelayChainInfo, error)
	// RelayToken query
	// group: relay
	GetRelayTokenList(context.Context, *RelayTokenListReq) (*RelayTokenListResp, error)
	// group: relay
	GetRelayTokenByChainAndId(context.Context, *RelayTokenKeyReq) (*RelayTokenInfo, error)
	// Client RelayChain query
	// group: relay
	GetClientRelayChainList(context.Context, *Empty) (*ClientRelayChainListResp, error)
	// Client RelayToken query
	// group: relay
	GetClientRelayTokenList(context.Context, *ClientRelayTokenListReq) (*ClientRelayTokenListResp, error)
	mustEmbedUnimplementedJobServer()
}

// UnimplementedJobServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobServer struct{}

func (UnimplementedJobServer) InitDatabase(context.Context, *Empty) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method InitDatabase not implemented")
}
func (UnimplementedJobServer) InitRelayTables(context.Context, *Empty) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method InitRelayTables not implemented")
}
func (UnimplementedJobServer) CreateTask(context.Context, *TaskInfo) (*BaseIDResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedJobServer) UpdateTask(context.Context, *TaskInfo) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedJobServer) GetTaskList(context.Context, *TaskListReq) (*TaskListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskList not implemented")
}
func (UnimplementedJobServer) GetTaskById(context.Context, *IDReq) (*TaskInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskById not implemented")
}
func (UnimplementedJobServer) DeleteTask(context.Context, *IDsReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedJobServer) CreateTaskLog(context.Context, *TaskLogInfo) (*BaseIDResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTaskLog not implemented")
}
func (UnimplementedJobServer) UpdateTaskLog(context.Context, *TaskLogInfo) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTaskLog not implemented")
}
func (UnimplementedJobServer) GetTaskLogList(context.Context, *TaskLogListReq) (*TaskLogListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskLogList not implemented")
}
func (UnimplementedJobServer) GetTaskLogById(context.Context, *IDReq) (*TaskLogInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskLogById not implemented")
}
func (UnimplementedJobServer) DeleteTaskLog(context.Context, *IDsReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTaskLog not implemented")
}
func (UnimplementedJobServer) GetRelayChainList(context.Context, *RelayChainListReq) (*RelayChainListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelayChainList not implemented")
}
func (UnimplementedJobServer) GetRelayChainById(context.Context, *RelayChainIDReq) (*RelayChainInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelayChainById not implemented")
}
func (UnimplementedJobServer) GetRelayTokenList(context.Context, *RelayTokenListReq) (*RelayTokenListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelayTokenList not implemented")
}
func (UnimplementedJobServer) GetRelayTokenByChainAndId(context.Context, *RelayTokenKeyReq) (*RelayTokenInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelayTokenByChainAndId not implemented")
}
func (UnimplementedJobServer) GetClientRelayChainList(context.Context, *Empty) (*ClientRelayChainListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClientRelayChainList not implemented")
}
func (UnimplementedJobServer) GetClientRelayTokenList(context.Context, *ClientRelayTokenListReq) (*ClientRelayTokenListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClientRelayTokenList not implemented")
}
func (UnimplementedJobServer) mustEmbedUnimplementedJobServer() {}
func (UnimplementedJobServer) testEmbeddedByValue()             {}

// UnsafeJobServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobServer will
// result in compilation errors.
type UnsafeJobServer interface {
	mustEmbedUnimplementedJobServer()
}

func RegisterJobServer(s grpc.ServiceRegistrar, srv JobServer) {
	// If the following call panics, it indicates UnimplementedJobServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Job_ServiceDesc, srv)
}

func _Job_InitDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).InitDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_InitDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).InitDatabase(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_InitRelayTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).InitRelayTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_InitRelayTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).InitRelayTables(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).CreateTask(ctx, req.(*TaskInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).UpdateTask(ctx, req.(*TaskInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_GetTaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).GetTaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_GetTaskList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).GetTaskList(ctx, req.(*TaskListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_GetTaskById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).GetTaskById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_GetTaskById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).GetTaskById(ctx, req.(*IDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).DeleteTask(ctx, req.(*IDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_CreateTaskLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskLogInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).CreateTaskLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_CreateTaskLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).CreateTaskLog(ctx, req.(*TaskLogInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_UpdateTaskLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskLogInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).UpdateTaskLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_UpdateTaskLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).UpdateTaskLog(ctx, req.(*TaskLogInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_GetTaskLogList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskLogListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).GetTaskLogList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_GetTaskLogList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).GetTaskLogList(ctx, req.(*TaskLogListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_GetTaskLogById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).GetTaskLogById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_GetTaskLogById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).GetTaskLogById(ctx, req.(*IDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_DeleteTaskLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).DeleteTaskLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_DeleteTaskLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).DeleteTaskLog(ctx, req.(*IDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_GetRelayChainList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayChainListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).GetRelayChainList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_GetRelayChainList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).GetRelayChainList(ctx, req.(*RelayChainListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_GetRelayChainById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayChainIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).GetRelayChainById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_GetRelayChainById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).GetRelayChainById(ctx, req.(*RelayChainIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_GetRelayTokenList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayTokenListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).GetRelayTokenList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_GetRelayTokenList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).GetRelayTokenList(ctx, req.(*RelayTokenListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_GetRelayTokenByChainAndId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayTokenKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).GetRelayTokenByChainAndId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_GetRelayTokenByChainAndId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).GetRelayTokenByChainAndId(ctx, req.(*RelayTokenKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_GetClientRelayChainList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).GetClientRelayChainList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_GetClientRelayChainList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).GetClientRelayChainList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_GetClientRelayTokenList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRelayTokenListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).GetClientRelayTokenList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_GetClientRelayTokenList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).GetClientRelayTokenList(ctx, req.(*ClientRelayTokenListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Job_ServiceDesc is the grpc.ServiceDesc for Job service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Job_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "job.Job",
	HandlerType: (*JobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "initDatabase",
			Handler:    _Job_InitDatabase_Handler,
		},
		{
			MethodName: "initRelayTables",
			Handler:    _Job_InitRelayTables_Handler,
		},
		{
			MethodName: "createTask",
			Handler:    _Job_CreateTask_Handler,
		},
		{
			MethodName: "updateTask",
			Handler:    _Job_UpdateTask_Handler,
		},
		{
			MethodName: "getTaskList",
			Handler:    _Job_GetTaskList_Handler,
		},
		{
			MethodName: "getTaskById",
			Handler:    _Job_GetTaskById_Handler,
		},
		{
			MethodName: "deleteTask",
			Handler:    _Job_DeleteTask_Handler,
		},
		{
			MethodName: "createTaskLog",
			Handler:    _Job_CreateTaskLog_Handler,
		},
		{
			MethodName: "updateTaskLog",
			Handler:    _Job_UpdateTaskLog_Handler,
		},
		{
			MethodName: "getTaskLogList",
			Handler:    _Job_GetTaskLogList_Handler,
		},
		{
			MethodName: "getTaskLogById",
			Handler:    _Job_GetTaskLogById_Handler,
		},
		{
			MethodName: "deleteTaskLog",
			Handler:    _Job_DeleteTaskLog_Handler,
		},
		{
			MethodName: "getRelayChainList",
			Handler:    _Job_GetRelayChainList_Handler,
		},
		{
			MethodName: "getRelayChainById",
			Handler:    _Job_GetRelayChainById_Handler,
		},
		{
			MethodName: "getRelayTokenList",
			Handler:    _Job_GetRelayTokenList_Handler,
		},
		{
			MethodName: "getRelayTokenByChainAndId",
			Handler:    _Job_GetRelayTokenByChainAndId_Handler,
		},
		{
			MethodName: "getClientRelayChainList",
			Handler:    _Job_GetClientRelayChainList_Handler,
		},
		{
			MethodName: "getClientRelayTokenList",
			Handler:    _Job_GetClientRelayTokenList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job.proto",
}
