// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: job.proto

package server

import (
	"context"

	"github.com/wf-platform/wf-account-job/internal/logic/base"
	"github.com/wf-platform/wf-account-job/internal/logic/relay"
	"github.com/wf-platform/wf-account-job/internal/logic/task"
	"github.com/wf-platform/wf-account-job/internal/logic/tasklog"
	"github.com/wf-platform/wf-account-job/internal/svc"
	"github.com/wf-platform/wf-account-job/types/job"
)

type JobServer struct {
	svcCtx *svc.ServiceContext
	job.UnimplementedJobServer
}

func NewJobServer(svcCtx *svc.ServiceContext) *JobServer {
	return &JobServer{
		svcCtx: svcCtx,
	}
}

// group: base
func (s *JobServer) InitDatabase(ctx context.Context, in *job.Empty) (*job.BaseResp, error) {
	l := base.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}

// group: base
func (s *JobServer) InitRelayTables(ctx context.Context, in *job.Empty) (*job.BaseResp, error) {
	l := base.NewInitRelayTablesLogic(ctx, s.svcCtx)
	return l.InitRelayTables(in)
}

// Task management
func (s *JobServer) CreateTask(ctx context.Context, in *job.TaskInfo) (*job.BaseIDResp, error) {
	l := task.NewCreateTaskLogic(ctx, s.svcCtx)
	return l.CreateTask(in)
}

// group: task
func (s *JobServer) UpdateTask(ctx context.Context, in *job.TaskInfo) (*job.BaseResp, error) {
	l := task.NewUpdateTaskLogic(ctx, s.svcCtx)
	return l.UpdateTask(in)
}

// group: task
func (s *JobServer) GetTaskList(ctx context.Context, in *job.TaskListReq) (*job.TaskListResp, error) {
	l := task.NewGetTaskListLogic(ctx, s.svcCtx)
	return l.GetTaskList(in)
}

// group: task
func (s *JobServer) GetTaskById(ctx context.Context, in *job.IDReq) (*job.TaskInfo, error) {
	l := task.NewGetTaskByIdLogic(ctx, s.svcCtx)
	return l.GetTaskById(in)
}

// group: task
func (s *JobServer) DeleteTask(ctx context.Context, in *job.IDsReq) (*job.BaseResp, error) {
	l := task.NewDeleteTaskLogic(ctx, s.svcCtx)
	return l.DeleteTask(in)
}

// TaskLog management
func (s *JobServer) CreateTaskLog(ctx context.Context, in *job.TaskLogInfo) (*job.BaseIDResp, error) {
	l := tasklog.NewCreateTaskLogLogic(ctx, s.svcCtx)
	return l.CreateTaskLog(in)
}

// group: tasklog
func (s *JobServer) UpdateTaskLog(ctx context.Context, in *job.TaskLogInfo) (*job.BaseResp, error) {
	l := tasklog.NewUpdateTaskLogLogic(ctx, s.svcCtx)
	return l.UpdateTaskLog(in)
}

// group: tasklog
func (s *JobServer) GetTaskLogList(ctx context.Context, in *job.TaskLogListReq) (*job.TaskLogListResp, error) {
	l := tasklog.NewGetTaskLogListLogic(ctx, s.svcCtx)
	return l.GetTaskLogList(in)
}

// group: tasklog
func (s *JobServer) GetTaskLogById(ctx context.Context, in *job.IDReq) (*job.TaskLogInfo, error) {
	l := tasklog.NewGetTaskLogByIdLogic(ctx, s.svcCtx)
	return l.GetTaskLogById(in)
}

// group: tasklog
func (s *JobServer) DeleteTaskLog(ctx context.Context, in *job.IDsReq) (*job.BaseResp, error) {
	l := tasklog.NewDeleteTaskLogLogic(ctx, s.svcCtx)
	return l.DeleteTaskLog(in)
}

// RelayChain query
func (s *JobServer) GetRelayChainList(ctx context.Context, in *job.RelayChainListReq) (*job.RelayChainListResp, error) {
	l := relay.NewGetRelayChainListLogic(ctx, s.svcCtx)
	return l.GetRelayChainList(in)
}

// group: relay
func (s *JobServer) GetRelayChainById(ctx context.Context, in *job.RelayChainIDReq) (*job.RelayChainInfo, error) {
	l := relay.NewGetRelayChainByIdLogic(ctx, s.svcCtx)
	return l.GetRelayChainById(in)
}

// RelayToken query
func (s *JobServer) GetRelayTokenList(ctx context.Context, in *job.RelayTokenListReq) (*job.RelayTokenListResp, error) {
	l := relay.NewGetRelayTokenListLogic(ctx, s.svcCtx)
	return l.GetRelayTokenList(in)
}

// group: relay
func (s *JobServer) GetRelayTokenByChainAndId(ctx context.Context, in *job.RelayTokenKeyReq) (*job.RelayTokenInfo, error) {
	l := relay.NewGetRelayTokenByChainAndIdLogic(ctx, s.svcCtx)
	return l.GetRelayTokenByChainAndId(in)
}

// Client RelayChain query
func (s *JobServer) GetClientRelayChainList(ctx context.Context, in *job.Empty) (*job.ClientRelayChainListResp, error) {
	l := relay.NewGetClientRelayChainListLogic(ctx, s.svcCtx)
	return l.GetClientRelayChainList(in)
}

// Client RelayToken query
func (s *JobServer) GetClientRelayTokenList(ctx context.Context, in *job.ClientRelayTokenListReq) (*job.ClientRelayTokenListResp, error) {
	l := relay.NewGetClientRelayTokenListLogic(ctx, s.svcCtx)
	return l.GetClientRelayTokenList(in)
}
