// Code generated by ent, DO NOT EDIT.

package relaytoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the relaytoken type in the database.
	Label = "relay_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTokenID holds the string denoting the token_id field in the database.
	FieldTokenID = "token_id"
	// FieldChainID holds the string denoting the chain_id field in the database.
	FieldChainID = "chain_id"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSymbol holds the string denoting the symbol field in the database.
	FieldSymbol = "symbol"
	// FieldLogoURL holds the string denoting the logo_url field in the database.
	FieldLogoURL = "logo_url"
	// FieldDecimals holds the string denoting the decimals field in the database.
	FieldDecimals = "decimals"
	// FieldNative holds the string denoting the native field in the database.
	FieldNative = "native"
	// FieldStablecoin holds the string denoting the stablecoin field in the database.
	FieldStablecoin = "stablecoin"
	// FieldSupportsBridging holds the string denoting the supports_bridging field in the database.
	FieldSupportsBridging = "supports_bridging"
	// FieldSupportsPermit holds the string denoting the supports_permit field in the database.
	FieldSupportsPermit = "supports_permit"
	// FieldIsFeatured holds the string denoting the is_featured field in the database.
	FieldIsFeatured = "is_featured"
	// FieldIsSolver holds the string denoting the is_solver field in the database.
	FieldIsSolver = "is_solver"
	// FieldIsErc20 holds the string denoting the is_erc20 field in the database.
	FieldIsErc20 = "is_erc20"
	// FieldSupported holds the string denoting the supported field in the database.
	FieldSupported = "supported"
	// FieldRawData holds the string denoting the raw_data field in the database.
	FieldRawData = "raw_data"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeChain holds the string denoting the chain edge name in mutations.
	EdgeChain = "chain"
	// Table holds the table name of the relaytoken in the database.
	Table = "relay_token"
	// ChainTable is the table that holds the chain relation/edge.
	ChainTable = "relay_token"
	// ChainInverseTable is the table name for the RelayChain entity.
	// It exists in this package in order to avoid circular dependency with the "relaychain" package.
	ChainInverseTable = "relay_chain"
	// ChainColumn is the table column denoting the chain relation/edge.
	ChainColumn = "chain_id"
)

// Columns holds all SQL columns for relaytoken fields.
var Columns = []string{
	FieldID,
	FieldTokenID,
	FieldChainID,
	FieldAddress,
	FieldName,
	FieldSymbol,
	FieldLogoURL,
	FieldDecimals,
	FieldNative,
	FieldStablecoin,
	FieldSupportsBridging,
	FieldSupportsPermit,
	FieldIsFeatured,
	FieldIsSolver,
	FieldIsErc20,
	FieldSupported,
	FieldRawData,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TokenIDValidator is a validator for the "token_id" field. It is called by the builders before save.
	TokenIDValidator func(string) error
	// ChainIDValidator is a validator for the "chain_id" field. It is called by the builders before save.
	ChainIDValidator func(int64) error
	// AddressValidator is a validator for the "address" field. It is called by the builders before save.
	AddressValidator func(string) error
	// SymbolValidator is a validator for the "symbol" field. It is called by the builders before save.
	SymbolValidator func(string) error
	// DecimalsValidator is a validator for the "decimals" field. It is called by the builders before save.
	DecimalsValidator func(int) error
	// DefaultNative holds the default value on creation for the "native" field.
	DefaultNative bool
	// DefaultStablecoin holds the default value on creation for the "stablecoin" field.
	DefaultStablecoin bool
	// DefaultSupportsBridging holds the default value on creation for the "supports_bridging" field.
	DefaultSupportsBridging bool
	// DefaultSupportsPermit holds the default value on creation for the "supports_permit" field.
	DefaultSupportsPermit bool
	// DefaultIsFeatured holds the default value on creation for the "is_featured" field.
	DefaultIsFeatured bool
	// DefaultIsSolver holds the default value on creation for the "is_solver" field.
	DefaultIsSolver bool
	// DefaultIsErc20 holds the default value on creation for the "is_erc20" field.
	DefaultIsErc20 bool
	// DefaultSupported holds the default value on creation for the "supported" field.
	DefaultSupported bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the RelayToken queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTokenID orders the results by the token_id field.
func ByTokenID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenID, opts...).ToFunc()
}

// ByChainID orders the results by the chain_id field.
func ByChainID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChainID, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySymbol orders the results by the symbol field.
func BySymbol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSymbol, opts...).ToFunc()
}

// ByLogoURL orders the results by the logo_url field.
func ByLogoURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogoURL, opts...).ToFunc()
}

// ByDecimals orders the results by the decimals field.
func ByDecimals(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDecimals, opts...).ToFunc()
}

// ByNative orders the results by the native field.
func ByNative(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNative, opts...).ToFunc()
}

// ByStablecoin orders the results by the stablecoin field.
func ByStablecoin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStablecoin, opts...).ToFunc()
}

// BySupportsBridging orders the results by the supports_bridging field.
func BySupportsBridging(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupportsBridging, opts...).ToFunc()
}

// BySupportsPermit orders the results by the supports_permit field.
func BySupportsPermit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupportsPermit, opts...).ToFunc()
}

// ByIsFeatured orders the results by the is_featured field.
func ByIsFeatured(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsFeatured, opts...).ToFunc()
}

// ByIsSolver orders the results by the is_solver field.
func ByIsSolver(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSolver, opts...).ToFunc()
}

// ByIsErc20 orders the results by the is_erc20 field.
func ByIsErc20(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsErc20, opts...).ToFunc()
}

// BySupported orders the results by the supported field.
func BySupported(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupported, opts...).ToFunc()
}

// ByRawData orders the results by the raw_data field.
func ByRawData(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawData, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByChainField orders the results by chain field.
func ByChainField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChainStep(), sql.OrderByField(field, opts...))
	}
}
func newChainStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChainInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChainTable, ChainColumn),
	)
}
