// Code generated by ent, DO NOT EDIT.

package relaytoken

import (
	"github.com/wf-platform/wf-account-job/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLTE(FieldID, id))
}

// TokenID applies equality check predicate on the "token_id" field. It's identical to TokenIDEQ.
func TokenID(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldTokenID, v))
}

// ChainID applies equality check predicate on the "chain_id" field. It's identical to ChainIDEQ.
func ChainID(v int64) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldChainID, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldAddress, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldName, v))
}

// Symbol applies equality check predicate on the "symbol" field. It's identical to SymbolEQ.
func Symbol(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldSymbol, v))
}

// LogoURL applies equality check predicate on the "logo_url" field. It's identical to LogoURLEQ.
func LogoURL(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldLogoURL, v))
}

// Decimals applies equality check predicate on the "decimals" field. It's identical to DecimalsEQ.
func Decimals(v int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldDecimals, v))
}

// Native applies equality check predicate on the "native" field. It's identical to NativeEQ.
func Native(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldNative, v))
}

// Stablecoin applies equality check predicate on the "stablecoin" field. It's identical to StablecoinEQ.
func Stablecoin(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldStablecoin, v))
}

// SupportsBridging applies equality check predicate on the "supports_bridging" field. It's identical to SupportsBridgingEQ.
func SupportsBridging(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldSupportsBridging, v))
}

// SupportsPermit applies equality check predicate on the "supports_permit" field. It's identical to SupportsPermitEQ.
func SupportsPermit(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldSupportsPermit, v))
}

// IsFeatured applies equality check predicate on the "is_featured" field. It's identical to IsFeaturedEQ.
func IsFeatured(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldIsFeatured, v))
}

// IsSolver applies equality check predicate on the "is_solver" field. It's identical to IsSolverEQ.
func IsSolver(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldIsSolver, v))
}

// IsErc20 applies equality check predicate on the "is_erc20" field. It's identical to IsErc20EQ.
func IsErc20(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldIsErc20, v))
}

// Supported applies equality check predicate on the "supported" field. It's identical to SupportedEQ.
func Supported(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldSupported, v))
}

// RawData applies equality check predicate on the "raw_data" field. It's identical to RawDataEQ.
func RawData(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldRawData, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// TokenIDEQ applies the EQ predicate on the "token_id" field.
func TokenIDEQ(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldTokenID, v))
}

// TokenIDNEQ applies the NEQ predicate on the "token_id" field.
func TokenIDNEQ(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldTokenID, v))
}

// TokenIDIn applies the In predicate on the "token_id" field.
func TokenIDIn(vs ...string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldIn(FieldTokenID, vs...))
}

// TokenIDNotIn applies the NotIn predicate on the "token_id" field.
func TokenIDNotIn(vs ...string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNotIn(FieldTokenID, vs...))
}

// TokenIDGT applies the GT predicate on the "token_id" field.
func TokenIDGT(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGT(FieldTokenID, v))
}

// TokenIDGTE applies the GTE predicate on the "token_id" field.
func TokenIDGTE(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGTE(FieldTokenID, v))
}

// TokenIDLT applies the LT predicate on the "token_id" field.
func TokenIDLT(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLT(FieldTokenID, v))
}

// TokenIDLTE applies the LTE predicate on the "token_id" field.
func TokenIDLTE(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLTE(FieldTokenID, v))
}

// TokenIDContains applies the Contains predicate on the "token_id" field.
func TokenIDContains(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldContains(FieldTokenID, v))
}

// TokenIDHasPrefix applies the HasPrefix predicate on the "token_id" field.
func TokenIDHasPrefix(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldHasPrefix(FieldTokenID, v))
}

// TokenIDHasSuffix applies the HasSuffix predicate on the "token_id" field.
func TokenIDHasSuffix(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldHasSuffix(FieldTokenID, v))
}

// TokenIDEqualFold applies the EqualFold predicate on the "token_id" field.
func TokenIDEqualFold(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEqualFold(FieldTokenID, v))
}

// TokenIDContainsFold applies the ContainsFold predicate on the "token_id" field.
func TokenIDContainsFold(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldContainsFold(FieldTokenID, v))
}

// ChainIDEQ applies the EQ predicate on the "chain_id" field.
func ChainIDEQ(v int64) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldChainID, v))
}

// ChainIDNEQ applies the NEQ predicate on the "chain_id" field.
func ChainIDNEQ(v int64) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldChainID, v))
}

// ChainIDIn applies the In predicate on the "chain_id" field.
func ChainIDIn(vs ...int64) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldIn(FieldChainID, vs...))
}

// ChainIDNotIn applies the NotIn predicate on the "chain_id" field.
func ChainIDNotIn(vs ...int64) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNotIn(FieldChainID, vs...))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldContainsFold(FieldAddress, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.RelayToken {
	return predicate.RelayToken(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldContainsFold(FieldName, v))
}

// SymbolEQ applies the EQ predicate on the "symbol" field.
func SymbolEQ(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldSymbol, v))
}

// SymbolNEQ applies the NEQ predicate on the "symbol" field.
func SymbolNEQ(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldSymbol, v))
}

// SymbolIn applies the In predicate on the "symbol" field.
func SymbolIn(vs ...string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldIn(FieldSymbol, vs...))
}

// SymbolNotIn applies the NotIn predicate on the "symbol" field.
func SymbolNotIn(vs ...string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNotIn(FieldSymbol, vs...))
}

// SymbolGT applies the GT predicate on the "symbol" field.
func SymbolGT(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGT(FieldSymbol, v))
}

// SymbolGTE applies the GTE predicate on the "symbol" field.
func SymbolGTE(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGTE(FieldSymbol, v))
}

// SymbolLT applies the LT predicate on the "symbol" field.
func SymbolLT(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLT(FieldSymbol, v))
}

// SymbolLTE applies the LTE predicate on the "symbol" field.
func SymbolLTE(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLTE(FieldSymbol, v))
}

// SymbolContains applies the Contains predicate on the "symbol" field.
func SymbolContains(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldContains(FieldSymbol, v))
}

// SymbolHasPrefix applies the HasPrefix predicate on the "symbol" field.
func SymbolHasPrefix(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldHasPrefix(FieldSymbol, v))
}

// SymbolHasSuffix applies the HasSuffix predicate on the "symbol" field.
func SymbolHasSuffix(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldHasSuffix(FieldSymbol, v))
}

// SymbolEqualFold applies the EqualFold predicate on the "symbol" field.
func SymbolEqualFold(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEqualFold(FieldSymbol, v))
}

// SymbolContainsFold applies the ContainsFold predicate on the "symbol" field.
func SymbolContainsFold(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldContainsFold(FieldSymbol, v))
}

// LogoURLEQ applies the EQ predicate on the "logo_url" field.
func LogoURLEQ(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldLogoURL, v))
}

// LogoURLNEQ applies the NEQ predicate on the "logo_url" field.
func LogoURLNEQ(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldLogoURL, v))
}

// LogoURLIn applies the In predicate on the "logo_url" field.
func LogoURLIn(vs ...string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldIn(FieldLogoURL, vs...))
}

// LogoURLNotIn applies the NotIn predicate on the "logo_url" field.
func LogoURLNotIn(vs ...string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNotIn(FieldLogoURL, vs...))
}

// LogoURLGT applies the GT predicate on the "logo_url" field.
func LogoURLGT(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGT(FieldLogoURL, v))
}

// LogoURLGTE applies the GTE predicate on the "logo_url" field.
func LogoURLGTE(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGTE(FieldLogoURL, v))
}

// LogoURLLT applies the LT predicate on the "logo_url" field.
func LogoURLLT(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLT(FieldLogoURL, v))
}

// LogoURLLTE applies the LTE predicate on the "logo_url" field.
func LogoURLLTE(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLTE(FieldLogoURL, v))
}

// LogoURLContains applies the Contains predicate on the "logo_url" field.
func LogoURLContains(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldContains(FieldLogoURL, v))
}

// LogoURLHasPrefix applies the HasPrefix predicate on the "logo_url" field.
func LogoURLHasPrefix(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldHasPrefix(FieldLogoURL, v))
}

// LogoURLHasSuffix applies the HasSuffix predicate on the "logo_url" field.
func LogoURLHasSuffix(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldHasSuffix(FieldLogoURL, v))
}

// LogoURLIsNil applies the IsNil predicate on the "logo_url" field.
func LogoURLIsNil() predicate.RelayToken {
	return predicate.RelayToken(sql.FieldIsNull(FieldLogoURL))
}

// LogoURLNotNil applies the NotNil predicate on the "logo_url" field.
func LogoURLNotNil() predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNotNull(FieldLogoURL))
}

// LogoURLEqualFold applies the EqualFold predicate on the "logo_url" field.
func LogoURLEqualFold(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEqualFold(FieldLogoURL, v))
}

// LogoURLContainsFold applies the ContainsFold predicate on the "logo_url" field.
func LogoURLContainsFold(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldContainsFold(FieldLogoURL, v))
}

// DecimalsEQ applies the EQ predicate on the "decimals" field.
func DecimalsEQ(v int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldDecimals, v))
}

// DecimalsNEQ applies the NEQ predicate on the "decimals" field.
func DecimalsNEQ(v int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldDecimals, v))
}

// DecimalsIn applies the In predicate on the "decimals" field.
func DecimalsIn(vs ...int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldIn(FieldDecimals, vs...))
}

// DecimalsNotIn applies the NotIn predicate on the "decimals" field.
func DecimalsNotIn(vs ...int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNotIn(FieldDecimals, vs...))
}

// DecimalsGT applies the GT predicate on the "decimals" field.
func DecimalsGT(v int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGT(FieldDecimals, v))
}

// DecimalsGTE applies the GTE predicate on the "decimals" field.
func DecimalsGTE(v int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGTE(FieldDecimals, v))
}

// DecimalsLT applies the LT predicate on the "decimals" field.
func DecimalsLT(v int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLT(FieldDecimals, v))
}

// DecimalsLTE applies the LTE predicate on the "decimals" field.
func DecimalsLTE(v int) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLTE(FieldDecimals, v))
}

// NativeEQ applies the EQ predicate on the "native" field.
func NativeEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldNative, v))
}

// NativeNEQ applies the NEQ predicate on the "native" field.
func NativeNEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldNative, v))
}

// StablecoinEQ applies the EQ predicate on the "stablecoin" field.
func StablecoinEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldStablecoin, v))
}

// StablecoinNEQ applies the NEQ predicate on the "stablecoin" field.
func StablecoinNEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldStablecoin, v))
}

// SupportsBridgingEQ applies the EQ predicate on the "supports_bridging" field.
func SupportsBridgingEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldSupportsBridging, v))
}

// SupportsBridgingNEQ applies the NEQ predicate on the "supports_bridging" field.
func SupportsBridgingNEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldSupportsBridging, v))
}

// SupportsPermitEQ applies the EQ predicate on the "supports_permit" field.
func SupportsPermitEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldSupportsPermit, v))
}

// SupportsPermitNEQ applies the NEQ predicate on the "supports_permit" field.
func SupportsPermitNEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldSupportsPermit, v))
}

// IsFeaturedEQ applies the EQ predicate on the "is_featured" field.
func IsFeaturedEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldIsFeatured, v))
}

// IsFeaturedNEQ applies the NEQ predicate on the "is_featured" field.
func IsFeaturedNEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldIsFeatured, v))
}

// IsSolverEQ applies the EQ predicate on the "is_solver" field.
func IsSolverEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldIsSolver, v))
}

// IsSolverNEQ applies the NEQ predicate on the "is_solver" field.
func IsSolverNEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldIsSolver, v))
}

// IsErc20EQ applies the EQ predicate on the "is_erc20" field.
func IsErc20EQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldIsErc20, v))
}

// IsErc20NEQ applies the NEQ predicate on the "is_erc20" field.
func IsErc20NEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldIsErc20, v))
}

// SupportedEQ applies the EQ predicate on the "supported" field.
func SupportedEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldSupported, v))
}

// SupportedNEQ applies the NEQ predicate on the "supported" field.
func SupportedNEQ(v bool) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldSupported, v))
}

// RawDataEQ applies the EQ predicate on the "raw_data" field.
func RawDataEQ(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldRawData, v))
}

// RawDataNEQ applies the NEQ predicate on the "raw_data" field.
func RawDataNEQ(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldRawData, v))
}

// RawDataIn applies the In predicate on the "raw_data" field.
func RawDataIn(vs ...string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldIn(FieldRawData, vs...))
}

// RawDataNotIn applies the NotIn predicate on the "raw_data" field.
func RawDataNotIn(vs ...string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNotIn(FieldRawData, vs...))
}

// RawDataGT applies the GT predicate on the "raw_data" field.
func RawDataGT(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGT(FieldRawData, v))
}

// RawDataGTE applies the GTE predicate on the "raw_data" field.
func RawDataGTE(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGTE(FieldRawData, v))
}

// RawDataLT applies the LT predicate on the "raw_data" field.
func RawDataLT(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLT(FieldRawData, v))
}

// RawDataLTE applies the LTE predicate on the "raw_data" field.
func RawDataLTE(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLTE(FieldRawData, v))
}

// RawDataContains applies the Contains predicate on the "raw_data" field.
func RawDataContains(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldContains(FieldRawData, v))
}

// RawDataHasPrefix applies the HasPrefix predicate on the "raw_data" field.
func RawDataHasPrefix(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldHasPrefix(FieldRawData, v))
}

// RawDataHasSuffix applies the HasSuffix predicate on the "raw_data" field.
func RawDataHasSuffix(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldHasSuffix(FieldRawData, v))
}

// RawDataIsNil applies the IsNil predicate on the "raw_data" field.
func RawDataIsNil() predicate.RelayToken {
	return predicate.RelayToken(sql.FieldIsNull(FieldRawData))
}

// RawDataNotNil applies the NotNil predicate on the "raw_data" field.
func RawDataNotNil() predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNotNull(FieldRawData))
}

// RawDataEqualFold applies the EqualFold predicate on the "raw_data" field.
func RawDataEqualFold(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEqualFold(FieldRawData, v))
}

// RawDataContainsFold applies the ContainsFold predicate on the "raw_data" field.
func RawDataContainsFold(v string) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldContainsFold(FieldRawData, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RelayToken {
	return predicate.RelayToken(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasChain applies the HasEdge predicate on the "chain" edge.
func HasChain() predicate.RelayToken {
	return predicate.RelayToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChainTable, ChainColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChainWith applies the HasEdge predicate on the "chain" edge with a given conditions (other predicates).
func HasChainWith(preds ...predicate.RelayChain) predicate.RelayToken {
	return predicate.RelayToken(func(s *sql.Selector) {
		step := newChainStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelayToken) predicate.RelayToken {
	return predicate.RelayToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelayToken) predicate.RelayToken {
	return predicate.RelayToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelayToken) predicate.RelayToken {
	return predicate.RelayToken(sql.NotPredicates(p))
}
