// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"wf-account-job/ent/migrate"

	"wf-account-job/ent/relaychain"
	"wf-account-job/ent/relaytoken"
	"wf-account-job/ent/task"
	"wf-account-job/ent/tasklog"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// RelayChain is the client for interacting with the RelayChain builders.
	RelayChain *RelayChainClient
	// RelayToken is the client for interacting with the RelayToken builders.
	RelayToken *RelayTokenClient
	// Task is the client for interacting with the Task builders.
	Task *TaskClient
	// TaskLog is the client for interacting with the TaskLog builders.
	TaskLog *TaskLogClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.RelayChain = NewRelayChainClient(c.config)
	c.RelayToken = NewRelayTokenClient(c.config)
	c.Task = NewTaskClient(c.config)
	c.TaskLog = NewTaskLogClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		RelayChain: NewRelayChainClient(cfg),
		RelayToken: NewRelayTokenClient(cfg),
		Task:       NewTaskClient(cfg),
		TaskLog:    NewTaskLogClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		RelayChain: NewRelayChainClient(cfg),
		RelayToken: NewRelayTokenClient(cfg),
		Task:       NewTaskClient(cfg),
		TaskLog:    NewTaskLogClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		RelayChain.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.RelayChain.Use(hooks...)
	c.RelayToken.Use(hooks...)
	c.Task.Use(hooks...)
	c.TaskLog.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.RelayChain.Intercept(interceptors...)
	c.RelayToken.Intercept(interceptors...)
	c.Task.Intercept(interceptors...)
	c.TaskLog.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *RelayChainMutation:
		return c.RelayChain.mutate(ctx, m)
	case *RelayTokenMutation:
		return c.RelayToken.mutate(ctx, m)
	case *TaskMutation:
		return c.Task.mutate(ctx, m)
	case *TaskLogMutation:
		return c.TaskLog.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// RelayChainClient is a client for the RelayChain schema.
type RelayChainClient struct {
	config
}

// NewRelayChainClient returns a client for the RelayChain from the given config.
func NewRelayChainClient(c config) *RelayChainClient {
	return &RelayChainClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `relaychain.Hooks(f(g(h())))`.
func (c *RelayChainClient) Use(hooks ...Hook) {
	c.hooks.RelayChain = append(c.hooks.RelayChain, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `relaychain.Intercept(f(g(h())))`.
func (c *RelayChainClient) Intercept(interceptors ...Interceptor) {
	c.inters.RelayChain = append(c.inters.RelayChain, interceptors...)
}

// Create returns a builder for creating a RelayChain entity.
func (c *RelayChainClient) Create() *RelayChainCreate {
	mutation := newRelayChainMutation(c.config, OpCreate)
	return &RelayChainCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RelayChain entities.
func (c *RelayChainClient) CreateBulk(builders ...*RelayChainCreate) *RelayChainCreateBulk {
	return &RelayChainCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RelayChainClient) MapCreateBulk(slice any, setFunc func(*RelayChainCreate, int)) *RelayChainCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RelayChainCreateBulk{err: fmt.Errorf("calling to RelayChainClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RelayChainCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RelayChainCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RelayChain.
func (c *RelayChainClient) Update() *RelayChainUpdate {
	mutation := newRelayChainMutation(c.config, OpUpdate)
	return &RelayChainUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RelayChainClient) UpdateOne(_m *RelayChain) *RelayChainUpdateOne {
	mutation := newRelayChainMutation(c.config, OpUpdateOne, withRelayChain(_m))
	return &RelayChainUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RelayChainClient) UpdateOneID(id int64) *RelayChainUpdateOne {
	mutation := newRelayChainMutation(c.config, OpUpdateOne, withRelayChainID(id))
	return &RelayChainUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RelayChain.
func (c *RelayChainClient) Delete() *RelayChainDelete {
	mutation := newRelayChainMutation(c.config, OpDelete)
	return &RelayChainDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RelayChainClient) DeleteOne(_m *RelayChain) *RelayChainDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RelayChainClient) DeleteOneID(id int64) *RelayChainDeleteOne {
	builder := c.Delete().Where(relaychain.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RelayChainDeleteOne{builder}
}

// Query returns a query builder for RelayChain.
func (c *RelayChainClient) Query() *RelayChainQuery {
	return &RelayChainQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRelayChain},
		inters: c.Interceptors(),
	}
}

// Get returns a RelayChain entity by its id.
func (c *RelayChainClient) Get(ctx context.Context, id int64) (*RelayChain, error) {
	return c.Query().Where(relaychain.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RelayChainClient) GetX(ctx context.Context, id int64) *RelayChain {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTokens queries the tokens edge of a RelayChain.
func (c *RelayChainClient) QueryTokens(_m *RelayChain) *RelayTokenQuery {
	query := (&RelayTokenClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(relaychain.Table, relaychain.FieldID, id),
			sqlgraph.To(relaytoken.Table, relaytoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, relaychain.TokensTable, relaychain.TokensColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RelayChainClient) Hooks() []Hook {
	return c.hooks.RelayChain
}

// Interceptors returns the client interceptors.
func (c *RelayChainClient) Interceptors() []Interceptor {
	return c.inters.RelayChain
}

func (c *RelayChainClient) mutate(ctx context.Context, m *RelayChainMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RelayChainCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RelayChainUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RelayChainUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RelayChainDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RelayChain mutation op: %q", m.Op())
	}
}

// RelayTokenClient is a client for the RelayToken schema.
type RelayTokenClient struct {
	config
}

// NewRelayTokenClient returns a client for the RelayToken from the given config.
func NewRelayTokenClient(c config) *RelayTokenClient {
	return &RelayTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `relaytoken.Hooks(f(g(h())))`.
func (c *RelayTokenClient) Use(hooks ...Hook) {
	c.hooks.RelayToken = append(c.hooks.RelayToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `relaytoken.Intercept(f(g(h())))`.
func (c *RelayTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.RelayToken = append(c.inters.RelayToken, interceptors...)
}

// Create returns a builder for creating a RelayToken entity.
func (c *RelayTokenClient) Create() *RelayTokenCreate {
	mutation := newRelayTokenMutation(c.config, OpCreate)
	return &RelayTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RelayToken entities.
func (c *RelayTokenClient) CreateBulk(builders ...*RelayTokenCreate) *RelayTokenCreateBulk {
	return &RelayTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RelayTokenClient) MapCreateBulk(slice any, setFunc func(*RelayTokenCreate, int)) *RelayTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RelayTokenCreateBulk{err: fmt.Errorf("calling to RelayTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RelayTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RelayTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RelayToken.
func (c *RelayTokenClient) Update() *RelayTokenUpdate {
	mutation := newRelayTokenMutation(c.config, OpUpdate)
	return &RelayTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RelayTokenClient) UpdateOne(_m *RelayToken) *RelayTokenUpdateOne {
	mutation := newRelayTokenMutation(c.config, OpUpdateOne, withRelayToken(_m))
	return &RelayTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RelayTokenClient) UpdateOneID(id int) *RelayTokenUpdateOne {
	mutation := newRelayTokenMutation(c.config, OpUpdateOne, withRelayTokenID(id))
	return &RelayTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RelayToken.
func (c *RelayTokenClient) Delete() *RelayTokenDelete {
	mutation := newRelayTokenMutation(c.config, OpDelete)
	return &RelayTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RelayTokenClient) DeleteOne(_m *RelayToken) *RelayTokenDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RelayTokenClient) DeleteOneID(id int) *RelayTokenDeleteOne {
	builder := c.Delete().Where(relaytoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RelayTokenDeleteOne{builder}
}

// Query returns a query builder for RelayToken.
func (c *RelayTokenClient) Query() *RelayTokenQuery {
	return &RelayTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRelayToken},
		inters: c.Interceptors(),
	}
}

// Get returns a RelayToken entity by its id.
func (c *RelayTokenClient) Get(ctx context.Context, id int) (*RelayToken, error) {
	return c.Query().Where(relaytoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RelayTokenClient) GetX(ctx context.Context, id int) *RelayToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChain queries the chain edge of a RelayToken.
func (c *RelayTokenClient) QueryChain(_m *RelayToken) *RelayChainQuery {
	query := (&RelayChainClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(relaytoken.Table, relaytoken.FieldID, id),
			sqlgraph.To(relaychain.Table, relaychain.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, relaytoken.ChainTable, relaytoken.ChainColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RelayTokenClient) Hooks() []Hook {
	return c.hooks.RelayToken
}

// Interceptors returns the client interceptors.
func (c *RelayTokenClient) Interceptors() []Interceptor {
	return c.inters.RelayToken
}

func (c *RelayTokenClient) mutate(ctx context.Context, m *RelayTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RelayTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RelayTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RelayTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RelayTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RelayToken mutation op: %q", m.Op())
	}
}

// TaskClient is a client for the Task schema.
type TaskClient struct {
	config
}

// NewTaskClient returns a client for the Task from the given config.
func NewTaskClient(c config) *TaskClient {
	return &TaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `task.Hooks(f(g(h())))`.
func (c *TaskClient) Use(hooks ...Hook) {
	c.hooks.Task = append(c.hooks.Task, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `task.Intercept(f(g(h())))`.
func (c *TaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.Task = append(c.inters.Task, interceptors...)
}

// Create returns a builder for creating a Task entity.
func (c *TaskClient) Create() *TaskCreate {
	mutation := newTaskMutation(c.config, OpCreate)
	return &TaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Task entities.
func (c *TaskClient) CreateBulk(builders ...*TaskCreate) *TaskCreateBulk {
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskClient) MapCreateBulk(slice any, setFunc func(*TaskCreate, int)) *TaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskCreateBulk{err: fmt.Errorf("calling to TaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Task.
func (c *TaskClient) Update() *TaskUpdate {
	mutation := newTaskMutation(c.config, OpUpdate)
	return &TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskClient) UpdateOne(_m *Task) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTask(_m))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskClient) UpdateOneID(id uint64) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTaskID(id))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Task.
func (c *TaskClient) Delete() *TaskDelete {
	mutation := newTaskMutation(c.config, OpDelete)
	return &TaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskClient) DeleteOne(_m *Task) *TaskDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskClient) DeleteOneID(id uint64) *TaskDeleteOne {
	builder := c.Delete().Where(task.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskDeleteOne{builder}
}

// Query returns a query builder for Task.
func (c *TaskClient) Query() *TaskQuery {
	return &TaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTask},
		inters: c.Interceptors(),
	}
}

// Get returns a Task entity by its id.
func (c *TaskClient) Get(ctx context.Context, id uint64) (*Task, error) {
	return c.Query().Where(task.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskClient) GetX(ctx context.Context, id uint64) *Task {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTaskLogs queries the task_logs edge of a Task.
func (c *TaskClient) QueryTaskLogs(_m *Task) *TaskLogQuery {
	query := (&TaskLogClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(tasklog.Table, tasklog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, task.TaskLogsTable, task.TaskLogsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TaskClient) Hooks() []Hook {
	return c.hooks.Task
}

// Interceptors returns the client interceptors.
func (c *TaskClient) Interceptors() []Interceptor {
	return c.inters.Task
}

func (c *TaskClient) mutate(ctx context.Context, m *TaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Task mutation op: %q", m.Op())
	}
}

// TaskLogClient is a client for the TaskLog schema.
type TaskLogClient struct {
	config
}

// NewTaskLogClient returns a client for the TaskLog from the given config.
func NewTaskLogClient(c config) *TaskLogClient {
	return &TaskLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tasklog.Hooks(f(g(h())))`.
func (c *TaskLogClient) Use(hooks ...Hook) {
	c.hooks.TaskLog = append(c.hooks.TaskLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tasklog.Intercept(f(g(h())))`.
func (c *TaskLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.TaskLog = append(c.inters.TaskLog, interceptors...)
}

// Create returns a builder for creating a TaskLog entity.
func (c *TaskLogClient) Create() *TaskLogCreate {
	mutation := newTaskLogMutation(c.config, OpCreate)
	return &TaskLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TaskLog entities.
func (c *TaskLogClient) CreateBulk(builders ...*TaskLogCreate) *TaskLogCreateBulk {
	return &TaskLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskLogClient) MapCreateBulk(slice any, setFunc func(*TaskLogCreate, int)) *TaskLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskLogCreateBulk{err: fmt.Errorf("calling to TaskLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TaskLog.
func (c *TaskLogClient) Update() *TaskLogUpdate {
	mutation := newTaskLogMutation(c.config, OpUpdate)
	return &TaskLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskLogClient) UpdateOne(_m *TaskLog) *TaskLogUpdateOne {
	mutation := newTaskLogMutation(c.config, OpUpdateOne, withTaskLog(_m))
	return &TaskLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskLogClient) UpdateOneID(id uint64) *TaskLogUpdateOne {
	mutation := newTaskLogMutation(c.config, OpUpdateOne, withTaskLogID(id))
	return &TaskLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TaskLog.
func (c *TaskLogClient) Delete() *TaskLogDelete {
	mutation := newTaskLogMutation(c.config, OpDelete)
	return &TaskLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskLogClient) DeleteOne(_m *TaskLog) *TaskLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskLogClient) DeleteOneID(id uint64) *TaskLogDeleteOne {
	builder := c.Delete().Where(tasklog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskLogDeleteOne{builder}
}

// Query returns a query builder for TaskLog.
func (c *TaskLogClient) Query() *TaskLogQuery {
	return &TaskLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTaskLog},
		inters: c.Interceptors(),
	}
}

// Get returns a TaskLog entity by its id.
func (c *TaskLogClient) Get(ctx context.Context, id uint64) (*TaskLog, error) {
	return c.Query().Where(tasklog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskLogClient) GetX(ctx context.Context, id uint64) *TaskLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTasks queries the tasks edge of a TaskLog.
func (c *TaskLogClient) QueryTasks(_m *TaskLog) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tasklog.Table, tasklog.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tasklog.TasksTable, tasklog.TasksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TaskLogClient) Hooks() []Hook {
	return c.hooks.TaskLog
}

// Interceptors returns the client interceptors.
func (c *TaskLogClient) Interceptors() []Interceptor {
	return c.inters.TaskLog
}

func (c *TaskLogClient) mutate(ctx context.Context, m *TaskLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TaskLog mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		RelayChain, RelayToken, Task, TaskLog []ent.Hook
	}
	inters struct {
		RelayChain, RelayToken, Task, TaskLog []ent.Interceptor
	}
)
