// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/wf-platform/wf-account-job/ent/predicate"
	"github.com/wf-platform/wf-account-job/ent/relaychain"
	"github.com/wf-platform/wf-account-job/ent/relaytoken"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RelayTokenUpdate is the builder for updating RelayToken entities.
type RelayTokenUpdate struct {
	config
	hooks    []Hook
	mutation *RelayTokenMutation
}

// Where appends a list predicates to the RelayTokenUpdate builder.
func (_u *RelayTokenUpdate) Where(ps ...predicate.RelayToken) *RelayTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTokenID sets the "token_id" field.
func (_u *RelayTokenUpdate) SetTokenID(v string) *RelayTokenUpdate {
	_u.mutation.SetTokenID(v)
	return _u
}

// SetNillableTokenID sets the "token_id" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableTokenID(v *string) *RelayTokenUpdate {
	if v != nil {
		_u.SetTokenID(*v)
	}
	return _u
}

// SetChainID sets the "chain_id" field.
func (_u *RelayTokenUpdate) SetChainID(v int64) *RelayTokenUpdate {
	_u.mutation.SetChainID(v)
	return _u
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableChainID(v *int64) *RelayTokenUpdate {
	if v != nil {
		_u.SetChainID(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *RelayTokenUpdate) SetAddress(v string) *RelayTokenUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableAddress(v *string) *RelayTokenUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RelayTokenUpdate) SetName(v string) *RelayTokenUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableName(v *string) *RelayTokenUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *RelayTokenUpdate) ClearName() *RelayTokenUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *RelayTokenUpdate) SetSymbol(v string) *RelayTokenUpdate {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableSymbol(v *string) *RelayTokenUpdate {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetLogoURL sets the "logo_url" field.
func (_u *RelayTokenUpdate) SetLogoURL(v string) *RelayTokenUpdate {
	_u.mutation.SetLogoURL(v)
	return _u
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableLogoURL(v *string) *RelayTokenUpdate {
	if v != nil {
		_u.SetLogoURL(*v)
	}
	return _u
}

// ClearLogoURL clears the value of the "logo_url" field.
func (_u *RelayTokenUpdate) ClearLogoURL() *RelayTokenUpdate {
	_u.mutation.ClearLogoURL()
	return _u
}

// SetDecimals sets the "decimals" field.
func (_u *RelayTokenUpdate) SetDecimals(v int) *RelayTokenUpdate {
	_u.mutation.ResetDecimals()
	_u.mutation.SetDecimals(v)
	return _u
}

// SetNillableDecimals sets the "decimals" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableDecimals(v *int) *RelayTokenUpdate {
	if v != nil {
		_u.SetDecimals(*v)
	}
	return _u
}

// AddDecimals adds value to the "decimals" field.
func (_u *RelayTokenUpdate) AddDecimals(v int) *RelayTokenUpdate {
	_u.mutation.AddDecimals(v)
	return _u
}

// SetNative sets the "native" field.
func (_u *RelayTokenUpdate) SetNative(v bool) *RelayTokenUpdate {
	_u.mutation.SetNative(v)
	return _u
}

// SetNillableNative sets the "native" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableNative(v *bool) *RelayTokenUpdate {
	if v != nil {
		_u.SetNative(*v)
	}
	return _u
}

// SetStablecoin sets the "stablecoin" field.
func (_u *RelayTokenUpdate) SetStablecoin(v bool) *RelayTokenUpdate {
	_u.mutation.SetStablecoin(v)
	return _u
}

// SetNillableStablecoin sets the "stablecoin" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableStablecoin(v *bool) *RelayTokenUpdate {
	if v != nil {
		_u.SetStablecoin(*v)
	}
	return _u
}

// SetSupportsBridging sets the "supports_bridging" field.
func (_u *RelayTokenUpdate) SetSupportsBridging(v bool) *RelayTokenUpdate {
	_u.mutation.SetSupportsBridging(v)
	return _u
}

// SetNillableSupportsBridging sets the "supports_bridging" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableSupportsBridging(v *bool) *RelayTokenUpdate {
	if v != nil {
		_u.SetSupportsBridging(*v)
	}
	return _u
}

// SetSupportsPermit sets the "supports_permit" field.
func (_u *RelayTokenUpdate) SetSupportsPermit(v bool) *RelayTokenUpdate {
	_u.mutation.SetSupportsPermit(v)
	return _u
}

// SetNillableSupportsPermit sets the "supports_permit" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableSupportsPermit(v *bool) *RelayTokenUpdate {
	if v != nil {
		_u.SetSupportsPermit(*v)
	}
	return _u
}

// SetIsFeatured sets the "is_featured" field.
func (_u *RelayTokenUpdate) SetIsFeatured(v bool) *RelayTokenUpdate {
	_u.mutation.SetIsFeatured(v)
	return _u
}

// SetNillableIsFeatured sets the "is_featured" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableIsFeatured(v *bool) *RelayTokenUpdate {
	if v != nil {
		_u.SetIsFeatured(*v)
	}
	return _u
}

// SetIsSolver sets the "is_solver" field.
func (_u *RelayTokenUpdate) SetIsSolver(v bool) *RelayTokenUpdate {
	_u.mutation.SetIsSolver(v)
	return _u
}

// SetNillableIsSolver sets the "is_solver" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableIsSolver(v *bool) *RelayTokenUpdate {
	if v != nil {
		_u.SetIsSolver(*v)
	}
	return _u
}

// SetIsErc20 sets the "is_erc20" field.
func (_u *RelayTokenUpdate) SetIsErc20(v bool) *RelayTokenUpdate {
	_u.mutation.SetIsErc20(v)
	return _u
}

// SetNillableIsErc20 sets the "is_erc20" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableIsErc20(v *bool) *RelayTokenUpdate {
	if v != nil {
		_u.SetIsErc20(*v)
	}
	return _u
}

// SetSupported sets the "supported" field.
func (_u *RelayTokenUpdate) SetSupported(v bool) *RelayTokenUpdate {
	_u.mutation.SetSupported(v)
	return _u
}

// SetNillableSupported sets the "supported" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableSupported(v *bool) *RelayTokenUpdate {
	if v != nil {
		_u.SetSupported(*v)
	}
	return _u
}

// SetRawData sets the "raw_data" field.
func (_u *RelayTokenUpdate) SetRawData(v string) *RelayTokenUpdate {
	_u.mutation.SetRawData(v)
	return _u
}

// SetNillableRawData sets the "raw_data" field if the given value is not nil.
func (_u *RelayTokenUpdate) SetNillableRawData(v *string) *RelayTokenUpdate {
	if v != nil {
		_u.SetRawData(*v)
	}
	return _u
}

// ClearRawData clears the value of the "raw_data" field.
func (_u *RelayTokenUpdate) ClearRawData() *RelayTokenUpdate {
	_u.mutation.ClearRawData()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelayTokenUpdate) SetUpdatedAt(v time.Time) *RelayTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChain sets the "chain" edge to the RelayChain entity.
func (_u *RelayTokenUpdate) SetChain(v *RelayChain) *RelayTokenUpdate {
	return _u.SetChainID(v.ID)
}

// Mutation returns the RelayTokenMutation object of the builder.
func (_u *RelayTokenUpdate) Mutation() *RelayTokenMutation {
	return _u.mutation
}

// ClearChain clears the "chain" edge to the RelayChain entity.
func (_u *RelayTokenUpdate) ClearChain() *RelayTokenUpdate {
	_u.mutation.ClearChain()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RelayTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelayTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RelayTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelayTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelayTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := relaytoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelayTokenUpdate) check() error {
	if v, ok := _u.mutation.TokenID(); ok {
		if err := relaytoken.TokenIDValidator(v); err != nil {
			return &ValidationError{Name: "token_id", err: fmt.Errorf(`ent: validator failed for field "RelayToken.token_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChainID(); ok {
		if err := relaytoken.ChainIDValidator(v); err != nil {
			return &ValidationError{Name: "chain_id", err: fmt.Errorf(`ent: validator failed for field "RelayToken.chain_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := relaytoken.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "RelayToken.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Symbol(); ok {
		if err := relaytoken.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "RelayToken.symbol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Decimals(); ok {
		if err := relaytoken.DecimalsValidator(v); err != nil {
			return &ValidationError{Name: "decimals", err: fmt.Errorf(`ent: validator failed for field "RelayToken.decimals": %w`, err)}
		}
	}
	if _u.mutation.ChainCleared() && len(_u.mutation.ChainIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RelayToken.chain"`)
	}
	return nil
}

func (_u *RelayTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relaytoken.Table, relaytoken.Columns, sqlgraph.NewFieldSpec(relaytoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenID(); ok {
		_spec.SetField(relaytoken.FieldTokenID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(relaytoken.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(relaytoken.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(relaytoken.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(relaytoken.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogoURL(); ok {
		_spec.SetField(relaytoken.FieldLogoURL, field.TypeString, value)
	}
	if _u.mutation.LogoURLCleared() {
		_spec.ClearField(relaytoken.FieldLogoURL, field.TypeString)
	}
	if value, ok := _u.mutation.Decimals(); ok {
		_spec.SetField(relaytoken.FieldDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDecimals(); ok {
		_spec.AddField(relaytoken.FieldDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Native(); ok {
		_spec.SetField(relaytoken.FieldNative, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Stablecoin(); ok {
		_spec.SetField(relaytoken.FieldStablecoin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SupportsBridging(); ok {
		_spec.SetField(relaytoken.FieldSupportsBridging, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SupportsPermit(); ok {
		_spec.SetField(relaytoken.FieldSupportsPermit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsFeatured(); ok {
		_spec.SetField(relaytoken.FieldIsFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSolver(); ok {
		_spec.SetField(relaytoken.FieldIsSolver, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsErc20(); ok {
		_spec.SetField(relaytoken.FieldIsErc20, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Supported(); ok {
		_spec.SetField(relaytoken.FieldSupported, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RawData(); ok {
		_spec.SetField(relaytoken.FieldRawData, field.TypeString, value)
	}
	if _u.mutation.RawDataCleared() {
		_spec.ClearField(relaytoken.FieldRawData, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relaytoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChainCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relaytoken.ChainTable,
			Columns: []string{relaytoken.ChainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaychain.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChainIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relaytoken.ChainTable,
			Columns: []string{relaytoken.ChainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaychain.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relaytoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RelayTokenUpdateOne is the builder for updating a single RelayToken entity.
type RelayTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RelayTokenMutation
}

// SetTokenID sets the "token_id" field.
func (_u *RelayTokenUpdateOne) SetTokenID(v string) *RelayTokenUpdateOne {
	_u.mutation.SetTokenID(v)
	return _u
}

// SetNillableTokenID sets the "token_id" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableTokenID(v *string) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetTokenID(*v)
	}
	return _u
}

// SetChainID sets the "chain_id" field.
func (_u *RelayTokenUpdateOne) SetChainID(v int64) *RelayTokenUpdateOne {
	_u.mutation.SetChainID(v)
	return _u
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableChainID(v *int64) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetChainID(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *RelayTokenUpdateOne) SetAddress(v string) *RelayTokenUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableAddress(v *string) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RelayTokenUpdateOne) SetName(v string) *RelayTokenUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableName(v *string) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *RelayTokenUpdateOne) ClearName() *RelayTokenUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *RelayTokenUpdateOne) SetSymbol(v string) *RelayTokenUpdateOne {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableSymbol(v *string) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetLogoURL sets the "logo_url" field.
func (_u *RelayTokenUpdateOne) SetLogoURL(v string) *RelayTokenUpdateOne {
	_u.mutation.SetLogoURL(v)
	return _u
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableLogoURL(v *string) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetLogoURL(*v)
	}
	return _u
}

// ClearLogoURL clears the value of the "logo_url" field.
func (_u *RelayTokenUpdateOne) ClearLogoURL() *RelayTokenUpdateOne {
	_u.mutation.ClearLogoURL()
	return _u
}

// SetDecimals sets the "decimals" field.
func (_u *RelayTokenUpdateOne) SetDecimals(v int) *RelayTokenUpdateOne {
	_u.mutation.ResetDecimals()
	_u.mutation.SetDecimals(v)
	return _u
}

// SetNillableDecimals sets the "decimals" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableDecimals(v *int) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetDecimals(*v)
	}
	return _u
}

// AddDecimals adds value to the "decimals" field.
func (_u *RelayTokenUpdateOne) AddDecimals(v int) *RelayTokenUpdateOne {
	_u.mutation.AddDecimals(v)
	return _u
}

// SetNative sets the "native" field.
func (_u *RelayTokenUpdateOne) SetNative(v bool) *RelayTokenUpdateOne {
	_u.mutation.SetNative(v)
	return _u
}

// SetNillableNative sets the "native" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableNative(v *bool) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetNative(*v)
	}
	return _u
}

// SetStablecoin sets the "stablecoin" field.
func (_u *RelayTokenUpdateOne) SetStablecoin(v bool) *RelayTokenUpdateOne {
	_u.mutation.SetStablecoin(v)
	return _u
}

// SetNillableStablecoin sets the "stablecoin" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableStablecoin(v *bool) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetStablecoin(*v)
	}
	return _u
}

// SetSupportsBridging sets the "supports_bridging" field.
func (_u *RelayTokenUpdateOne) SetSupportsBridging(v bool) *RelayTokenUpdateOne {
	_u.mutation.SetSupportsBridging(v)
	return _u
}

// SetNillableSupportsBridging sets the "supports_bridging" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableSupportsBridging(v *bool) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetSupportsBridging(*v)
	}
	return _u
}

// SetSupportsPermit sets the "supports_permit" field.
func (_u *RelayTokenUpdateOne) SetSupportsPermit(v bool) *RelayTokenUpdateOne {
	_u.mutation.SetSupportsPermit(v)
	return _u
}

// SetNillableSupportsPermit sets the "supports_permit" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableSupportsPermit(v *bool) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetSupportsPermit(*v)
	}
	return _u
}

// SetIsFeatured sets the "is_featured" field.
func (_u *RelayTokenUpdateOne) SetIsFeatured(v bool) *RelayTokenUpdateOne {
	_u.mutation.SetIsFeatured(v)
	return _u
}

// SetNillableIsFeatured sets the "is_featured" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableIsFeatured(v *bool) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetIsFeatured(*v)
	}
	return _u
}

// SetIsSolver sets the "is_solver" field.
func (_u *RelayTokenUpdateOne) SetIsSolver(v bool) *RelayTokenUpdateOne {
	_u.mutation.SetIsSolver(v)
	return _u
}

// SetNillableIsSolver sets the "is_solver" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableIsSolver(v *bool) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetIsSolver(*v)
	}
	return _u
}

// SetIsErc20 sets the "is_erc20" field.
func (_u *RelayTokenUpdateOne) SetIsErc20(v bool) *RelayTokenUpdateOne {
	_u.mutation.SetIsErc20(v)
	return _u
}

// SetNillableIsErc20 sets the "is_erc20" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableIsErc20(v *bool) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetIsErc20(*v)
	}
	return _u
}

// SetSupported sets the "supported" field.
func (_u *RelayTokenUpdateOne) SetSupported(v bool) *RelayTokenUpdateOne {
	_u.mutation.SetSupported(v)
	return _u
}

// SetNillableSupported sets the "supported" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableSupported(v *bool) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetSupported(*v)
	}
	return _u
}

// SetRawData sets the "raw_data" field.
func (_u *RelayTokenUpdateOne) SetRawData(v string) *RelayTokenUpdateOne {
	_u.mutation.SetRawData(v)
	return _u
}

// SetNillableRawData sets the "raw_data" field if the given value is not nil.
func (_u *RelayTokenUpdateOne) SetNillableRawData(v *string) *RelayTokenUpdateOne {
	if v != nil {
		_u.SetRawData(*v)
	}
	return _u
}

// ClearRawData clears the value of the "raw_data" field.
func (_u *RelayTokenUpdateOne) ClearRawData() *RelayTokenUpdateOne {
	_u.mutation.ClearRawData()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelayTokenUpdateOne) SetUpdatedAt(v time.Time) *RelayTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChain sets the "chain" edge to the RelayChain entity.
func (_u *RelayTokenUpdateOne) SetChain(v *RelayChain) *RelayTokenUpdateOne {
	return _u.SetChainID(v.ID)
}

// Mutation returns the RelayTokenMutation object of the builder.
func (_u *RelayTokenUpdateOne) Mutation() *RelayTokenMutation {
	return _u.mutation
}

// ClearChain clears the "chain" edge to the RelayChain entity.
func (_u *RelayTokenUpdateOne) ClearChain() *RelayTokenUpdateOne {
	_u.mutation.ClearChain()
	return _u
}

// Where appends a list predicates to the RelayTokenUpdate builder.
func (_u *RelayTokenUpdateOne) Where(ps ...predicate.RelayToken) *RelayTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RelayTokenUpdateOne) Select(field string, fields ...string) *RelayTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RelayToken entity.
func (_u *RelayTokenUpdateOne) Save(ctx context.Context) (*RelayToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelayTokenUpdateOne) SaveX(ctx context.Context) *RelayToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RelayTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelayTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelayTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := relaytoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelayTokenUpdateOne) check() error {
	if v, ok := _u.mutation.TokenID(); ok {
		if err := relaytoken.TokenIDValidator(v); err != nil {
			return &ValidationError{Name: "token_id", err: fmt.Errorf(`ent: validator failed for field "RelayToken.token_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChainID(); ok {
		if err := relaytoken.ChainIDValidator(v); err != nil {
			return &ValidationError{Name: "chain_id", err: fmt.Errorf(`ent: validator failed for field "RelayToken.chain_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := relaytoken.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "RelayToken.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Symbol(); ok {
		if err := relaytoken.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "RelayToken.symbol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Decimals(); ok {
		if err := relaytoken.DecimalsValidator(v); err != nil {
			return &ValidationError{Name: "decimals", err: fmt.Errorf(`ent: validator failed for field "RelayToken.decimals": %w`, err)}
		}
	}
	if _u.mutation.ChainCleared() && len(_u.mutation.ChainIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RelayToken.chain"`)
	}
	return nil
}

func (_u *RelayTokenUpdateOne) sqlSave(ctx context.Context) (_node *RelayToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relaytoken.Table, relaytoken.Columns, sqlgraph.NewFieldSpec(relaytoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RelayToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relaytoken.FieldID)
		for _, f := range fields {
			if !relaytoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != relaytoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenID(); ok {
		_spec.SetField(relaytoken.FieldTokenID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(relaytoken.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(relaytoken.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(relaytoken.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(relaytoken.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogoURL(); ok {
		_spec.SetField(relaytoken.FieldLogoURL, field.TypeString, value)
	}
	if _u.mutation.LogoURLCleared() {
		_spec.ClearField(relaytoken.FieldLogoURL, field.TypeString)
	}
	if value, ok := _u.mutation.Decimals(); ok {
		_spec.SetField(relaytoken.FieldDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDecimals(); ok {
		_spec.AddField(relaytoken.FieldDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Native(); ok {
		_spec.SetField(relaytoken.FieldNative, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Stablecoin(); ok {
		_spec.SetField(relaytoken.FieldStablecoin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SupportsBridging(); ok {
		_spec.SetField(relaytoken.FieldSupportsBridging, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SupportsPermit(); ok {
		_spec.SetField(relaytoken.FieldSupportsPermit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsFeatured(); ok {
		_spec.SetField(relaytoken.FieldIsFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSolver(); ok {
		_spec.SetField(relaytoken.FieldIsSolver, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsErc20(); ok {
		_spec.SetField(relaytoken.FieldIsErc20, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Supported(); ok {
		_spec.SetField(relaytoken.FieldSupported, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RawData(); ok {
		_spec.SetField(relaytoken.FieldRawData, field.TypeString, value)
	}
	if _u.mutation.RawDataCleared() {
		_spec.ClearField(relaytoken.FieldRawData, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relaytoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChainCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relaytoken.ChainTable,
			Columns: []string{relaytoken.ChainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaychain.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChainIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relaytoken.ChainTable,
			Columns: []string{relaytoken.ChainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaychain.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RelayToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relaytoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
