// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wf-account-job/ent/predicate"
	"wf-account-job/ent/relaychain"
	"wf-account-job/ent/relaytoken"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RelayChainUpdate is the builder for updating RelayChain entities.
type RelayChainUpdate struct {
	config
	hooks    []Hook
	mutation *RelayChainMutation
}

// Where appends a list predicates to the RelayChainUpdate builder.
func (_u *RelayChainUpdate) Where(ps ...predicate.RelayChain) *RelayChainUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *RelayChainUpdate) SetSlug(v string) *RelayChainUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableSlug(v *string) *RelayChainUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *RelayChainUpdate) ClearSlug() *RelayChainUpdate {
	_u.mutation.ClearSlug()
	return _u
}

// SetName sets the "name" field.
func (_u *RelayChainUpdate) SetName(v string) *RelayChainUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableName(v *string) *RelayChainUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLogoURL sets the "logo_url" field.
func (_u *RelayChainUpdate) SetLogoURL(v string) *RelayChainUpdate {
	_u.mutation.SetLogoURL(v)
	return _u
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableLogoURL(v *string) *RelayChainUpdate {
	if v != nil {
		_u.SetLogoURL(*v)
	}
	return _u
}

// ClearLogoURL clears the value of the "logo_url" field.
func (_u *RelayChainUpdate) ClearLogoURL() *RelayChainUpdate {
	_u.mutation.ClearLogoURL()
	return _u
}

// SetType sets the "type" field.
func (_u *RelayChainUpdate) SetType(v string) *RelayChainUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableType(v *string) *RelayChainUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetVMType sets the "vm_type" field.
func (_u *RelayChainUpdate) SetVMType(v string) *RelayChainUpdate {
	_u.mutation.SetVMType(v)
	return _u
}

// SetNillableVMType sets the "vm_type" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableVMType(v *string) *RelayChainUpdate {
	if v != nil {
		_u.SetVMType(*v)
	}
	return _u
}

// ClearVMType clears the value of the "vm_type" field.
func (_u *RelayChainUpdate) ClearVMType() *RelayChainUpdate {
	_u.mutation.ClearVMType()
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *RelayChainUpdate) SetProtocol(v string) *RelayChainUpdate {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableProtocol(v *string) *RelayChainUpdate {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// ClearProtocol clears the value of the "protocol" field.
func (_u *RelayChainUpdate) ClearProtocol() *RelayChainUpdate {
	_u.mutation.ClearProtocol()
	return _u
}

// SetBaseChainID sets the "base_chain_id" field.
func (_u *RelayChainUpdate) SetBaseChainID(v string) *RelayChainUpdate {
	_u.mutation.SetBaseChainID(v)
	return _u
}

// SetNillableBaseChainID sets the "base_chain_id" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableBaseChainID(v *string) *RelayChainUpdate {
	if v != nil {
		_u.SetBaseChainID(*v)
	}
	return _u
}

// ClearBaseChainID clears the value of the "base_chain_id" field.
func (_u *RelayChainUpdate) ClearBaseChainID() *RelayChainUpdate {
	_u.mutation.ClearBaseChainID()
	return _u
}

// SetExplorerURL sets the "explorer_url" field.
func (_u *RelayChainUpdate) SetExplorerURL(v string) *RelayChainUpdate {
	_u.mutation.SetExplorerURL(v)
	return _u
}

// SetNillableExplorerURL sets the "explorer_url" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableExplorerURL(v *string) *RelayChainUpdate {
	if v != nil {
		_u.SetExplorerURL(*v)
	}
	return _u
}

// ClearExplorerURL clears the value of the "explorer_url" field.
func (_u *RelayChainUpdate) ClearExplorerURL() *RelayChainUpdate {
	_u.mutation.ClearExplorerURL()
	return _u
}

// SetExplorerName sets the "explorer_name" field.
func (_u *RelayChainUpdate) SetExplorerName(v string) *RelayChainUpdate {
	_u.mutation.SetExplorerName(v)
	return _u
}

// SetNillableExplorerName sets the "explorer_name" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableExplorerName(v *string) *RelayChainUpdate {
	if v != nil {
		_u.SetExplorerName(*v)
	}
	return _u
}

// ClearExplorerName clears the value of the "explorer_name" field.
func (_u *RelayChainUpdate) ClearExplorerName() *RelayChainUpdate {
	_u.mutation.ClearExplorerName()
	return _u
}

// SetRPCURL sets the "rpc_url" field.
func (_u *RelayChainUpdate) SetRPCURL(v string) *RelayChainUpdate {
	_u.mutation.SetRPCURL(v)
	return _u
}

// SetNillableRPCURL sets the "rpc_url" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableRPCURL(v *string) *RelayChainUpdate {
	if v != nil {
		_u.SetRPCURL(*v)
	}
	return _u
}

// ClearRPCURL clears the value of the "rpc_url" field.
func (_u *RelayChainUpdate) ClearRPCURL() *RelayChainUpdate {
	_u.mutation.ClearRPCURL()
	return _u
}

// SetWsRPCURL sets the "ws_rpc_url" field.
func (_u *RelayChainUpdate) SetWsRPCURL(v string) *RelayChainUpdate {
	_u.mutation.SetWsRPCURL(v)
	return _u
}

// SetNillableWsRPCURL sets the "ws_rpc_url" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableWsRPCURL(v *string) *RelayChainUpdate {
	if v != nil {
		_u.SetWsRPCURL(*v)
	}
	return _u
}

// ClearWsRPCURL clears the value of the "ws_rpc_url" field.
func (_u *RelayChainUpdate) ClearWsRPCURL() *RelayChainUpdate {
	_u.mutation.ClearWsRPCURL()
	return _u
}

// SetNativeSymbol sets the "native_symbol" field.
func (_u *RelayChainUpdate) SetNativeSymbol(v string) *RelayChainUpdate {
	_u.mutation.SetNativeSymbol(v)
	return _u
}

// SetNillableNativeSymbol sets the "native_symbol" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableNativeSymbol(v *string) *RelayChainUpdate {
	if v != nil {
		_u.SetNativeSymbol(*v)
	}
	return _u
}

// ClearNativeSymbol clears the value of the "native_symbol" field.
func (_u *RelayChainUpdate) ClearNativeSymbol() *RelayChainUpdate {
	_u.mutation.ClearNativeSymbol()
	return _u
}

// SetNativeDecimals sets the "native_decimals" field.
func (_u *RelayChainUpdate) SetNativeDecimals(v int) *RelayChainUpdate {
	_u.mutation.ResetNativeDecimals()
	_u.mutation.SetNativeDecimals(v)
	return _u
}

// SetNillableNativeDecimals sets the "native_decimals" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableNativeDecimals(v *int) *RelayChainUpdate {
	if v != nil {
		_u.SetNativeDecimals(*v)
	}
	return _u
}

// AddNativeDecimals adds value to the "native_decimals" field.
func (_u *RelayChainUpdate) AddNativeDecimals(v int) *RelayChainUpdate {
	_u.mutation.AddNativeDecimals(v)
	return _u
}

// SetDepositEnabled sets the "deposit_enabled" field.
func (_u *RelayChainUpdate) SetDepositEnabled(v bool) *RelayChainUpdate {
	_u.mutation.SetDepositEnabled(v)
	return _u
}

// SetNillableDepositEnabled sets the "deposit_enabled" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableDepositEnabled(v *bool) *RelayChainUpdate {
	if v != nil {
		_u.SetDepositEnabled(*v)
	}
	return _u
}

// SetTokenSupport sets the "token_support" field.
func (_u *RelayChainUpdate) SetTokenSupport(v string) *RelayChainUpdate {
	_u.mutation.SetTokenSupport(v)
	return _u
}

// SetNillableTokenSupport sets the "token_support" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableTokenSupport(v *string) *RelayChainUpdate {
	if v != nil {
		_u.SetTokenSupport(*v)
	}
	return _u
}

// ClearTokenSupport clears the value of the "token_support" field.
func (_u *RelayChainUpdate) ClearTokenSupport() *RelayChainUpdate {
	_u.mutation.ClearTokenSupport()
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *RelayChainUpdate) SetDisabled(v bool) *RelayChainUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableDisabled(v *bool) *RelayChainUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetSupported sets the "supported" field.
func (_u *RelayChainUpdate) SetSupported(v bool) *RelayChainUpdate {
	_u.mutation.SetSupported(v)
	return _u
}

// SetNillableSupported sets the "supported" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableSupported(v *bool) *RelayChainUpdate {
	if v != nil {
		_u.SetSupported(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RelayChainUpdate) SetEnabled(v bool) *RelayChainUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableEnabled(v *bool) *RelayChainUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetRawData sets the "raw_data" field.
func (_u *RelayChainUpdate) SetRawData(v string) *RelayChainUpdate {
	_u.mutation.SetRawData(v)
	return _u
}

// SetNillableRawData sets the "raw_data" field if the given value is not nil.
func (_u *RelayChainUpdate) SetNillableRawData(v *string) *RelayChainUpdate {
	if v != nil {
		_u.SetRawData(*v)
	}
	return _u
}

// ClearRawData clears the value of the "raw_data" field.
func (_u *RelayChainUpdate) ClearRawData() *RelayChainUpdate {
	_u.mutation.ClearRawData()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelayChainUpdate) SetUpdatedAt(v time.Time) *RelayChainUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTokenIDs adds the "tokens" edge to the RelayToken entity by IDs.
func (_u *RelayChainUpdate) AddTokenIDs(ids ...int) *RelayChainUpdate {
	_u.mutation.AddTokenIDs(ids...)
	return _u
}

// AddTokens adds the "tokens" edges to the RelayToken entity.
func (_u *RelayChainUpdate) AddTokens(v ...*RelayToken) *RelayChainUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTokenIDs(ids...)
}

// Mutation returns the RelayChainMutation object of the builder.
func (_u *RelayChainUpdate) Mutation() *RelayChainMutation {
	return _u.mutation
}

// ClearTokens clears all "tokens" edges to the RelayToken entity.
func (_u *RelayChainUpdate) ClearTokens() *RelayChainUpdate {
	_u.mutation.ClearTokens()
	return _u
}

// RemoveTokenIDs removes the "tokens" edge to RelayToken entities by IDs.
func (_u *RelayChainUpdate) RemoveTokenIDs(ids ...int) *RelayChainUpdate {
	_u.mutation.RemoveTokenIDs(ids...)
	return _u
}

// RemoveTokens removes "tokens" edges to RelayToken entities.
func (_u *RelayChainUpdate) RemoveTokens(v ...*RelayToken) *RelayChainUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTokenIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RelayChainUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelayChainUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RelayChainUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelayChainUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelayChainUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := relaychain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelayChainUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := relaychain.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RelayChain.name": %w`, err)}
		}
	}
	return nil
}

func (_u *RelayChainUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relaychain.Table, relaychain.Columns, sqlgraph.NewFieldSpec(relaychain.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(relaychain.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(relaychain.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(relaychain.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogoURL(); ok {
		_spec.SetField(relaychain.FieldLogoURL, field.TypeString, value)
	}
	if _u.mutation.LogoURLCleared() {
		_spec.ClearField(relaychain.FieldLogoURL, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(relaychain.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.VMType(); ok {
		_spec.SetField(relaychain.FieldVMType, field.TypeString, value)
	}
	if _u.mutation.VMTypeCleared() {
		_spec.ClearField(relaychain.FieldVMType, field.TypeString)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(relaychain.FieldProtocol, field.TypeString, value)
	}
	if _u.mutation.ProtocolCleared() {
		_spec.ClearField(relaychain.FieldProtocol, field.TypeString)
	}
	if value, ok := _u.mutation.BaseChainID(); ok {
		_spec.SetField(relaychain.FieldBaseChainID, field.TypeString, value)
	}
	if _u.mutation.BaseChainIDCleared() {
		_spec.ClearField(relaychain.FieldBaseChainID, field.TypeString)
	}
	if value, ok := _u.mutation.ExplorerURL(); ok {
		_spec.SetField(relaychain.FieldExplorerURL, field.TypeString, value)
	}
	if _u.mutation.ExplorerURLCleared() {
		_spec.ClearField(relaychain.FieldExplorerURL, field.TypeString)
	}
	if value, ok := _u.mutation.ExplorerName(); ok {
		_spec.SetField(relaychain.FieldExplorerName, field.TypeString, value)
	}
	if _u.mutation.ExplorerNameCleared() {
		_spec.ClearField(relaychain.FieldExplorerName, field.TypeString)
	}
	if value, ok := _u.mutation.RPCURL(); ok {
		_spec.SetField(relaychain.FieldRPCURL, field.TypeString, value)
	}
	if _u.mutation.RPCURLCleared() {
		_spec.ClearField(relaychain.FieldRPCURL, field.TypeString)
	}
	if value, ok := _u.mutation.WsRPCURL(); ok {
		_spec.SetField(relaychain.FieldWsRPCURL, field.TypeString, value)
	}
	if _u.mutation.WsRPCURLCleared() {
		_spec.ClearField(relaychain.FieldWsRPCURL, field.TypeString)
	}
	if value, ok := _u.mutation.NativeSymbol(); ok {
		_spec.SetField(relaychain.FieldNativeSymbol, field.TypeString, value)
	}
	if _u.mutation.NativeSymbolCleared() {
		_spec.ClearField(relaychain.FieldNativeSymbol, field.TypeString)
	}
	if value, ok := _u.mutation.NativeDecimals(); ok {
		_spec.SetField(relaychain.FieldNativeDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNativeDecimals(); ok {
		_spec.AddField(relaychain.FieldNativeDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DepositEnabled(); ok {
		_spec.SetField(relaychain.FieldDepositEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TokenSupport(); ok {
		_spec.SetField(relaychain.FieldTokenSupport, field.TypeString, value)
	}
	if _u.mutation.TokenSupportCleared() {
		_spec.ClearField(relaychain.FieldTokenSupport, field.TypeString)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(relaychain.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Supported(); ok {
		_spec.SetField(relaychain.FieldSupported, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(relaychain.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RawData(); ok {
		_spec.SetField(relaychain.FieldRawData, field.TypeString, value)
	}
	if _u.mutation.RawDataCleared() {
		_spec.ClearField(relaychain.FieldRawData, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relaychain.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaychain.TokensTable,
			Columns: []string{relaychain.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaytoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTokensIDs(); len(nodes) > 0 && !_u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaychain.TokensTable,
			Columns: []string{relaychain.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaytoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaychain.TokensTable,
			Columns: []string{relaychain.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaytoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relaychain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RelayChainUpdateOne is the builder for updating a single RelayChain entity.
type RelayChainUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RelayChainMutation
}

// SetSlug sets the "slug" field.
func (_u *RelayChainUpdateOne) SetSlug(v string) *RelayChainUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableSlug(v *string) *RelayChainUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *RelayChainUpdateOne) ClearSlug() *RelayChainUpdateOne {
	_u.mutation.ClearSlug()
	return _u
}

// SetName sets the "name" field.
func (_u *RelayChainUpdateOne) SetName(v string) *RelayChainUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableName(v *string) *RelayChainUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLogoURL sets the "logo_url" field.
func (_u *RelayChainUpdateOne) SetLogoURL(v string) *RelayChainUpdateOne {
	_u.mutation.SetLogoURL(v)
	return _u
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableLogoURL(v *string) *RelayChainUpdateOne {
	if v != nil {
		_u.SetLogoURL(*v)
	}
	return _u
}

// ClearLogoURL clears the value of the "logo_url" field.
func (_u *RelayChainUpdateOne) ClearLogoURL() *RelayChainUpdateOne {
	_u.mutation.ClearLogoURL()
	return _u
}

// SetType sets the "type" field.
func (_u *RelayChainUpdateOne) SetType(v string) *RelayChainUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableType(v *string) *RelayChainUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetVMType sets the "vm_type" field.
func (_u *RelayChainUpdateOne) SetVMType(v string) *RelayChainUpdateOne {
	_u.mutation.SetVMType(v)
	return _u
}

// SetNillableVMType sets the "vm_type" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableVMType(v *string) *RelayChainUpdateOne {
	if v != nil {
		_u.SetVMType(*v)
	}
	return _u
}

// ClearVMType clears the value of the "vm_type" field.
func (_u *RelayChainUpdateOne) ClearVMType() *RelayChainUpdateOne {
	_u.mutation.ClearVMType()
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *RelayChainUpdateOne) SetProtocol(v string) *RelayChainUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableProtocol(v *string) *RelayChainUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// ClearProtocol clears the value of the "protocol" field.
func (_u *RelayChainUpdateOne) ClearProtocol() *RelayChainUpdateOne {
	_u.mutation.ClearProtocol()
	return _u
}

// SetBaseChainID sets the "base_chain_id" field.
func (_u *RelayChainUpdateOne) SetBaseChainID(v string) *RelayChainUpdateOne {
	_u.mutation.SetBaseChainID(v)
	return _u
}

// SetNillableBaseChainID sets the "base_chain_id" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableBaseChainID(v *string) *RelayChainUpdateOne {
	if v != nil {
		_u.SetBaseChainID(*v)
	}
	return _u
}

// ClearBaseChainID clears the value of the "base_chain_id" field.
func (_u *RelayChainUpdateOne) ClearBaseChainID() *RelayChainUpdateOne {
	_u.mutation.ClearBaseChainID()
	return _u
}

// SetExplorerURL sets the "explorer_url" field.
func (_u *RelayChainUpdateOne) SetExplorerURL(v string) *RelayChainUpdateOne {
	_u.mutation.SetExplorerURL(v)
	return _u
}

// SetNillableExplorerURL sets the "explorer_url" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableExplorerURL(v *string) *RelayChainUpdateOne {
	if v != nil {
		_u.SetExplorerURL(*v)
	}
	return _u
}

// ClearExplorerURL clears the value of the "explorer_url" field.
func (_u *RelayChainUpdateOne) ClearExplorerURL() *RelayChainUpdateOne {
	_u.mutation.ClearExplorerURL()
	return _u
}

// SetExplorerName sets the "explorer_name" field.
func (_u *RelayChainUpdateOne) SetExplorerName(v string) *RelayChainUpdateOne {
	_u.mutation.SetExplorerName(v)
	return _u
}

// SetNillableExplorerName sets the "explorer_name" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableExplorerName(v *string) *RelayChainUpdateOne {
	if v != nil {
		_u.SetExplorerName(*v)
	}
	return _u
}

// ClearExplorerName clears the value of the "explorer_name" field.
func (_u *RelayChainUpdateOne) ClearExplorerName() *RelayChainUpdateOne {
	_u.mutation.ClearExplorerName()
	return _u
}

// SetRPCURL sets the "rpc_url" field.
func (_u *RelayChainUpdateOne) SetRPCURL(v string) *RelayChainUpdateOne {
	_u.mutation.SetRPCURL(v)
	return _u
}

// SetNillableRPCURL sets the "rpc_url" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableRPCURL(v *string) *RelayChainUpdateOne {
	if v != nil {
		_u.SetRPCURL(*v)
	}
	return _u
}

// ClearRPCURL clears the value of the "rpc_url" field.
func (_u *RelayChainUpdateOne) ClearRPCURL() *RelayChainUpdateOne {
	_u.mutation.ClearRPCURL()
	return _u
}

// SetWsRPCURL sets the "ws_rpc_url" field.
func (_u *RelayChainUpdateOne) SetWsRPCURL(v string) *RelayChainUpdateOne {
	_u.mutation.SetWsRPCURL(v)
	return _u
}

// SetNillableWsRPCURL sets the "ws_rpc_url" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableWsRPCURL(v *string) *RelayChainUpdateOne {
	if v != nil {
		_u.SetWsRPCURL(*v)
	}
	return _u
}

// ClearWsRPCURL clears the value of the "ws_rpc_url" field.
func (_u *RelayChainUpdateOne) ClearWsRPCURL() *RelayChainUpdateOne {
	_u.mutation.ClearWsRPCURL()
	return _u
}

// SetNativeSymbol sets the "native_symbol" field.
func (_u *RelayChainUpdateOne) SetNativeSymbol(v string) *RelayChainUpdateOne {
	_u.mutation.SetNativeSymbol(v)
	return _u
}

// SetNillableNativeSymbol sets the "native_symbol" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableNativeSymbol(v *string) *RelayChainUpdateOne {
	if v != nil {
		_u.SetNativeSymbol(*v)
	}
	return _u
}

// ClearNativeSymbol clears the value of the "native_symbol" field.
func (_u *RelayChainUpdateOne) ClearNativeSymbol() *RelayChainUpdateOne {
	_u.mutation.ClearNativeSymbol()
	return _u
}

// SetNativeDecimals sets the "native_decimals" field.
func (_u *RelayChainUpdateOne) SetNativeDecimals(v int) *RelayChainUpdateOne {
	_u.mutation.ResetNativeDecimals()
	_u.mutation.SetNativeDecimals(v)
	return _u
}

// SetNillableNativeDecimals sets the "native_decimals" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableNativeDecimals(v *int) *RelayChainUpdateOne {
	if v != nil {
		_u.SetNativeDecimals(*v)
	}
	return _u
}

// AddNativeDecimals adds value to the "native_decimals" field.
func (_u *RelayChainUpdateOne) AddNativeDecimals(v int) *RelayChainUpdateOne {
	_u.mutation.AddNativeDecimals(v)
	return _u
}

// SetDepositEnabled sets the "deposit_enabled" field.
func (_u *RelayChainUpdateOne) SetDepositEnabled(v bool) *RelayChainUpdateOne {
	_u.mutation.SetDepositEnabled(v)
	return _u
}

// SetNillableDepositEnabled sets the "deposit_enabled" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableDepositEnabled(v *bool) *RelayChainUpdateOne {
	if v != nil {
		_u.SetDepositEnabled(*v)
	}
	return _u
}

// SetTokenSupport sets the "token_support" field.
func (_u *RelayChainUpdateOne) SetTokenSupport(v string) *RelayChainUpdateOne {
	_u.mutation.SetTokenSupport(v)
	return _u
}

// SetNillableTokenSupport sets the "token_support" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableTokenSupport(v *string) *RelayChainUpdateOne {
	if v != nil {
		_u.SetTokenSupport(*v)
	}
	return _u
}

// ClearTokenSupport clears the value of the "token_support" field.
func (_u *RelayChainUpdateOne) ClearTokenSupport() *RelayChainUpdateOne {
	_u.mutation.ClearTokenSupport()
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *RelayChainUpdateOne) SetDisabled(v bool) *RelayChainUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableDisabled(v *bool) *RelayChainUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetSupported sets the "supported" field.
func (_u *RelayChainUpdateOne) SetSupported(v bool) *RelayChainUpdateOne {
	_u.mutation.SetSupported(v)
	return _u
}

// SetNillableSupported sets the "supported" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableSupported(v *bool) *RelayChainUpdateOne {
	if v != nil {
		_u.SetSupported(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RelayChainUpdateOne) SetEnabled(v bool) *RelayChainUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableEnabled(v *bool) *RelayChainUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetRawData sets the "raw_data" field.
func (_u *RelayChainUpdateOne) SetRawData(v string) *RelayChainUpdateOne {
	_u.mutation.SetRawData(v)
	return _u
}

// SetNillableRawData sets the "raw_data" field if the given value is not nil.
func (_u *RelayChainUpdateOne) SetNillableRawData(v *string) *RelayChainUpdateOne {
	if v != nil {
		_u.SetRawData(*v)
	}
	return _u
}

// ClearRawData clears the value of the "raw_data" field.
func (_u *RelayChainUpdateOne) ClearRawData() *RelayChainUpdateOne {
	_u.mutation.ClearRawData()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelayChainUpdateOne) SetUpdatedAt(v time.Time) *RelayChainUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTokenIDs adds the "tokens" edge to the RelayToken entity by IDs.
func (_u *RelayChainUpdateOne) AddTokenIDs(ids ...int) *RelayChainUpdateOne {
	_u.mutation.AddTokenIDs(ids...)
	return _u
}

// AddTokens adds the "tokens" edges to the RelayToken entity.
func (_u *RelayChainUpdateOne) AddTokens(v ...*RelayToken) *RelayChainUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTokenIDs(ids...)
}

// Mutation returns the RelayChainMutation object of the builder.
func (_u *RelayChainUpdateOne) Mutation() *RelayChainMutation {
	return _u.mutation
}

// ClearTokens clears all "tokens" edges to the RelayToken entity.
func (_u *RelayChainUpdateOne) ClearTokens() *RelayChainUpdateOne {
	_u.mutation.ClearTokens()
	return _u
}

// RemoveTokenIDs removes the "tokens" edge to RelayToken entities by IDs.
func (_u *RelayChainUpdateOne) RemoveTokenIDs(ids ...int) *RelayChainUpdateOne {
	_u.mutation.RemoveTokenIDs(ids...)
	return _u
}

// RemoveTokens removes "tokens" edges to RelayToken entities.
func (_u *RelayChainUpdateOne) RemoveTokens(v ...*RelayToken) *RelayChainUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTokenIDs(ids...)
}

// Where appends a list predicates to the RelayChainUpdate builder.
func (_u *RelayChainUpdateOne) Where(ps ...predicate.RelayChain) *RelayChainUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RelayChainUpdateOne) Select(field string, fields ...string) *RelayChainUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RelayChain entity.
func (_u *RelayChainUpdateOne) Save(ctx context.Context) (*RelayChain, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelayChainUpdateOne) SaveX(ctx context.Context) *RelayChain {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RelayChainUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelayChainUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelayChainUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := relaychain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelayChainUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := relaychain.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RelayChain.name": %w`, err)}
		}
	}
	return nil
}

func (_u *RelayChainUpdateOne) sqlSave(ctx context.Context) (_node *RelayChain, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relaychain.Table, relaychain.Columns, sqlgraph.NewFieldSpec(relaychain.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RelayChain.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relaychain.FieldID)
		for _, f := range fields {
			if !relaychain.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != relaychain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(relaychain.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(relaychain.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(relaychain.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogoURL(); ok {
		_spec.SetField(relaychain.FieldLogoURL, field.TypeString, value)
	}
	if _u.mutation.LogoURLCleared() {
		_spec.ClearField(relaychain.FieldLogoURL, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(relaychain.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.VMType(); ok {
		_spec.SetField(relaychain.FieldVMType, field.TypeString, value)
	}
	if _u.mutation.VMTypeCleared() {
		_spec.ClearField(relaychain.FieldVMType, field.TypeString)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(relaychain.FieldProtocol, field.TypeString, value)
	}
	if _u.mutation.ProtocolCleared() {
		_spec.ClearField(relaychain.FieldProtocol, field.TypeString)
	}
	if value, ok := _u.mutation.BaseChainID(); ok {
		_spec.SetField(relaychain.FieldBaseChainID, field.TypeString, value)
	}
	if _u.mutation.BaseChainIDCleared() {
		_spec.ClearField(relaychain.FieldBaseChainID, field.TypeString)
	}
	if value, ok := _u.mutation.ExplorerURL(); ok {
		_spec.SetField(relaychain.FieldExplorerURL, field.TypeString, value)
	}
	if _u.mutation.ExplorerURLCleared() {
		_spec.ClearField(relaychain.FieldExplorerURL, field.TypeString)
	}
	if value, ok := _u.mutation.ExplorerName(); ok {
		_spec.SetField(relaychain.FieldExplorerName, field.TypeString, value)
	}
	if _u.mutation.ExplorerNameCleared() {
		_spec.ClearField(relaychain.FieldExplorerName, field.TypeString)
	}
	if value, ok := _u.mutation.RPCURL(); ok {
		_spec.SetField(relaychain.FieldRPCURL, field.TypeString, value)
	}
	if _u.mutation.RPCURLCleared() {
		_spec.ClearField(relaychain.FieldRPCURL, field.TypeString)
	}
	if value, ok := _u.mutation.WsRPCURL(); ok {
		_spec.SetField(relaychain.FieldWsRPCURL, field.TypeString, value)
	}
	if _u.mutation.WsRPCURLCleared() {
		_spec.ClearField(relaychain.FieldWsRPCURL, field.TypeString)
	}
	if value, ok := _u.mutation.NativeSymbol(); ok {
		_spec.SetField(relaychain.FieldNativeSymbol, field.TypeString, value)
	}
	if _u.mutation.NativeSymbolCleared() {
		_spec.ClearField(relaychain.FieldNativeSymbol, field.TypeString)
	}
	if value, ok := _u.mutation.NativeDecimals(); ok {
		_spec.SetField(relaychain.FieldNativeDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNativeDecimals(); ok {
		_spec.AddField(relaychain.FieldNativeDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DepositEnabled(); ok {
		_spec.SetField(relaychain.FieldDepositEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TokenSupport(); ok {
		_spec.SetField(relaychain.FieldTokenSupport, field.TypeString, value)
	}
	if _u.mutation.TokenSupportCleared() {
		_spec.ClearField(relaychain.FieldTokenSupport, field.TypeString)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(relaychain.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Supported(); ok {
		_spec.SetField(relaychain.FieldSupported, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(relaychain.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RawData(); ok {
		_spec.SetField(relaychain.FieldRawData, field.TypeString, value)
	}
	if _u.mutation.RawDataCleared() {
		_spec.ClearField(relaychain.FieldRawData, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relaychain.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaychain.TokensTable,
			Columns: []string{relaychain.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaytoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTokensIDs(); len(nodes) > 0 && !_u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaychain.TokensTable,
			Columns: []string{relaychain.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaytoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaychain.TokensTable,
			Columns: []string{relaychain.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaytoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RelayChain{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relaychain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
