// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/wf-platform/wf-account-job/ent/relaychain"
	"github.com/wf-platform/wf-account-job/ent/relaytoken"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RelayTokenCreate is the builder for creating a RelayToken entity.
type RelayTokenCreate struct {
	config
	mutation *RelayTokenMutation
	hooks    []Hook
}

// SetTokenID sets the "token_id" field.
func (_c *RelayTokenCreate) SetTokenID(v string) *RelayTokenCreate {
	_c.mutation.SetTokenID(v)
	return _c
}

// SetChainID sets the "chain_id" field.
func (_c *RelayTokenCreate) SetChainID(v int64) *RelayTokenCreate {
	_c.mutation.SetChainID(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *RelayTokenCreate) SetAddress(v string) *RelayTokenCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RelayTokenCreate) SetName(v string) *RelayTokenCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *RelayTokenCreate) SetNillableName(v *string) *RelayTokenCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetSymbol sets the "symbol" field.
func (_c *RelayTokenCreate) SetSymbol(v string) *RelayTokenCreate {
	_c.mutation.SetSymbol(v)
	return _c
}

// SetLogoURL sets the "logo_url" field.
func (_c *RelayTokenCreate) SetLogoURL(v string) *RelayTokenCreate {
	_c.mutation.SetLogoURL(v)
	return _c
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_c *RelayTokenCreate) SetNillableLogoURL(v *string) *RelayTokenCreate {
	if v != nil {
		_c.SetLogoURL(*v)
	}
	return _c
}

// SetDecimals sets the "decimals" field.
func (_c *RelayTokenCreate) SetDecimals(v int) *RelayTokenCreate {
	_c.mutation.SetDecimals(v)
	return _c
}

// SetNative sets the "native" field.
func (_c *RelayTokenCreate) SetNative(v bool) *RelayTokenCreate {
	_c.mutation.SetNative(v)
	return _c
}

// SetNillableNative sets the "native" field if the given value is not nil.
func (_c *RelayTokenCreate) SetNillableNative(v *bool) *RelayTokenCreate {
	if v != nil {
		_c.SetNative(*v)
	}
	return _c
}

// SetStablecoin sets the "stablecoin" field.
func (_c *RelayTokenCreate) SetStablecoin(v bool) *RelayTokenCreate {
	_c.mutation.SetStablecoin(v)
	return _c
}

// SetNillableStablecoin sets the "stablecoin" field if the given value is not nil.
func (_c *RelayTokenCreate) SetNillableStablecoin(v *bool) *RelayTokenCreate {
	if v != nil {
		_c.SetStablecoin(*v)
	}
	return _c
}

// SetSupportsBridging sets the "supports_bridging" field.
func (_c *RelayTokenCreate) SetSupportsBridging(v bool) *RelayTokenCreate {
	_c.mutation.SetSupportsBridging(v)
	return _c
}

// SetNillableSupportsBridging sets the "supports_bridging" field if the given value is not nil.
func (_c *RelayTokenCreate) SetNillableSupportsBridging(v *bool) *RelayTokenCreate {
	if v != nil {
		_c.SetSupportsBridging(*v)
	}
	return _c
}

// SetSupportsPermit sets the "supports_permit" field.
func (_c *RelayTokenCreate) SetSupportsPermit(v bool) *RelayTokenCreate {
	_c.mutation.SetSupportsPermit(v)
	return _c
}

// SetNillableSupportsPermit sets the "supports_permit" field if the given value is not nil.
func (_c *RelayTokenCreate) SetNillableSupportsPermit(v *bool) *RelayTokenCreate {
	if v != nil {
		_c.SetSupportsPermit(*v)
	}
	return _c
}

// SetIsFeatured sets the "is_featured" field.
func (_c *RelayTokenCreate) SetIsFeatured(v bool) *RelayTokenCreate {
	_c.mutation.SetIsFeatured(v)
	return _c
}

// SetNillableIsFeatured sets the "is_featured" field if the given value is not nil.
func (_c *RelayTokenCreate) SetNillableIsFeatured(v *bool) *RelayTokenCreate {
	if v != nil {
		_c.SetIsFeatured(*v)
	}
	return _c
}

// SetIsSolver sets the "is_solver" field.
func (_c *RelayTokenCreate) SetIsSolver(v bool) *RelayTokenCreate {
	_c.mutation.SetIsSolver(v)
	return _c
}

// SetNillableIsSolver sets the "is_solver" field if the given value is not nil.
func (_c *RelayTokenCreate) SetNillableIsSolver(v *bool) *RelayTokenCreate {
	if v != nil {
		_c.SetIsSolver(*v)
	}
	return _c
}

// SetIsErc20 sets the "is_erc20" field.
func (_c *RelayTokenCreate) SetIsErc20(v bool) *RelayTokenCreate {
	_c.mutation.SetIsErc20(v)
	return _c
}

// SetNillableIsErc20 sets the "is_erc20" field if the given value is not nil.
func (_c *RelayTokenCreate) SetNillableIsErc20(v *bool) *RelayTokenCreate {
	if v != nil {
		_c.SetIsErc20(*v)
	}
	return _c
}

// SetSupported sets the "supported" field.
func (_c *RelayTokenCreate) SetSupported(v bool) *RelayTokenCreate {
	_c.mutation.SetSupported(v)
	return _c
}

// SetNillableSupported sets the "supported" field if the given value is not nil.
func (_c *RelayTokenCreate) SetNillableSupported(v *bool) *RelayTokenCreate {
	if v != nil {
		_c.SetSupported(*v)
	}
	return _c
}

// SetRawData sets the "raw_data" field.
func (_c *RelayTokenCreate) SetRawData(v string) *RelayTokenCreate {
	_c.mutation.SetRawData(v)
	return _c
}

// SetNillableRawData sets the "raw_data" field if the given value is not nil.
func (_c *RelayTokenCreate) SetNillableRawData(v *string) *RelayTokenCreate {
	if v != nil {
		_c.SetRawData(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RelayTokenCreate) SetCreatedAt(v time.Time) *RelayTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RelayTokenCreate) SetNillableCreatedAt(v *time.Time) *RelayTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RelayTokenCreate) SetUpdatedAt(v time.Time) *RelayTokenCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RelayTokenCreate) SetNillableUpdatedAt(v *time.Time) *RelayTokenCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetChain sets the "chain" edge to the RelayChain entity.
func (_c *RelayTokenCreate) SetChain(v *RelayChain) *RelayTokenCreate {
	return _c.SetChainID(v.ID)
}

// Mutation returns the RelayTokenMutation object of the builder.
func (_c *RelayTokenCreate) Mutation() *RelayTokenMutation {
	return _c.mutation
}

// Save creates the RelayToken in the database.
func (_c *RelayTokenCreate) Save(ctx context.Context) (*RelayToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RelayTokenCreate) SaveX(ctx context.Context) *RelayToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelayTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelayTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RelayTokenCreate) defaults() {
	if _, ok := _c.mutation.Native(); !ok {
		v := relaytoken.DefaultNative
		_c.mutation.SetNative(v)
	}
	if _, ok := _c.mutation.Stablecoin(); !ok {
		v := relaytoken.DefaultStablecoin
		_c.mutation.SetStablecoin(v)
	}
	if _, ok := _c.mutation.SupportsBridging(); !ok {
		v := relaytoken.DefaultSupportsBridging
		_c.mutation.SetSupportsBridging(v)
	}
	if _, ok := _c.mutation.SupportsPermit(); !ok {
		v := relaytoken.DefaultSupportsPermit
		_c.mutation.SetSupportsPermit(v)
	}
	if _, ok := _c.mutation.IsFeatured(); !ok {
		v := relaytoken.DefaultIsFeatured
		_c.mutation.SetIsFeatured(v)
	}
	if _, ok := _c.mutation.IsSolver(); !ok {
		v := relaytoken.DefaultIsSolver
		_c.mutation.SetIsSolver(v)
	}
	if _, ok := _c.mutation.IsErc20(); !ok {
		v := relaytoken.DefaultIsErc20
		_c.mutation.SetIsErc20(v)
	}
	if _, ok := _c.mutation.Supported(); !ok {
		v := relaytoken.DefaultSupported
		_c.mutation.SetSupported(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := relaytoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := relaytoken.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RelayTokenCreate) check() error {
	if _, ok := _c.mutation.TokenID(); !ok {
		return &ValidationError{Name: "token_id", err: errors.New(`ent: missing required field "RelayToken.token_id"`)}
	}
	if v, ok := _c.mutation.TokenID(); ok {
		if err := relaytoken.TokenIDValidator(v); err != nil {
			return &ValidationError{Name: "token_id", err: fmt.Errorf(`ent: validator failed for field "RelayToken.token_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChainID(); !ok {
		return &ValidationError{Name: "chain_id", err: errors.New(`ent: missing required field "RelayToken.chain_id"`)}
	}
	if v, ok := _c.mutation.ChainID(); ok {
		if err := relaytoken.ChainIDValidator(v); err != nil {
			return &ValidationError{Name: "chain_id", err: fmt.Errorf(`ent: validator failed for field "RelayToken.chain_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "RelayToken.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := relaytoken.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "RelayToken.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Symbol(); !ok {
		return &ValidationError{Name: "symbol", err: errors.New(`ent: missing required field "RelayToken.symbol"`)}
	}
	if v, ok := _c.mutation.Symbol(); ok {
		if err := relaytoken.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "RelayToken.symbol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Decimals(); !ok {
		return &ValidationError{Name: "decimals", err: errors.New(`ent: missing required field "RelayToken.decimals"`)}
	}
	if v, ok := _c.mutation.Decimals(); ok {
		if err := relaytoken.DecimalsValidator(v); err != nil {
			return &ValidationError{Name: "decimals", err: fmt.Errorf(`ent: validator failed for field "RelayToken.decimals": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Native(); !ok {
		return &ValidationError{Name: "native", err: errors.New(`ent: missing required field "RelayToken.native"`)}
	}
	if _, ok := _c.mutation.Stablecoin(); !ok {
		return &ValidationError{Name: "stablecoin", err: errors.New(`ent: missing required field "RelayToken.stablecoin"`)}
	}
	if _, ok := _c.mutation.SupportsBridging(); !ok {
		return &ValidationError{Name: "supports_bridging", err: errors.New(`ent: missing required field "RelayToken.supports_bridging"`)}
	}
	if _, ok := _c.mutation.SupportsPermit(); !ok {
		return &ValidationError{Name: "supports_permit", err: errors.New(`ent: missing required field "RelayToken.supports_permit"`)}
	}
	if _, ok := _c.mutation.IsFeatured(); !ok {
		return &ValidationError{Name: "is_featured", err: errors.New(`ent: missing required field "RelayToken.is_featured"`)}
	}
	if _, ok := _c.mutation.IsSolver(); !ok {
		return &ValidationError{Name: "is_solver", err: errors.New(`ent: missing required field "RelayToken.is_solver"`)}
	}
	if _, ok := _c.mutation.IsErc20(); !ok {
		return &ValidationError{Name: "is_erc20", err: errors.New(`ent: missing required field "RelayToken.is_erc20"`)}
	}
	if _, ok := _c.mutation.Supported(); !ok {
		return &ValidationError{Name: "supported", err: errors.New(`ent: missing required field "RelayToken.supported"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RelayToken.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RelayToken.updated_at"`)}
	}
	if len(_c.mutation.ChainIDs()) == 0 {
		return &ValidationError{Name: "chain", err: errors.New(`ent: missing required edge "RelayToken.chain"`)}
	}
	return nil
}

func (_c *RelayTokenCreate) sqlSave(ctx context.Context) (*RelayToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RelayTokenCreate) createSpec() (*RelayToken, *sqlgraph.CreateSpec) {
	var (
		_node = &RelayToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(relaytoken.Table, sqlgraph.NewFieldSpec(relaytoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TokenID(); ok {
		_spec.SetField(relaytoken.FieldTokenID, field.TypeString, value)
		_node.TokenID = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(relaytoken.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(relaytoken.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Symbol(); ok {
		_spec.SetField(relaytoken.FieldSymbol, field.TypeString, value)
		_node.Symbol = value
	}
	if value, ok := _c.mutation.LogoURL(); ok {
		_spec.SetField(relaytoken.FieldLogoURL, field.TypeString, value)
		_node.LogoURL = value
	}
	if value, ok := _c.mutation.Decimals(); ok {
		_spec.SetField(relaytoken.FieldDecimals, field.TypeInt, value)
		_node.Decimals = value
	}
	if value, ok := _c.mutation.Native(); ok {
		_spec.SetField(relaytoken.FieldNative, field.TypeBool, value)
		_node.Native = value
	}
	if value, ok := _c.mutation.Stablecoin(); ok {
		_spec.SetField(relaytoken.FieldStablecoin, field.TypeBool, value)
		_node.Stablecoin = value
	}
	if value, ok := _c.mutation.SupportsBridging(); ok {
		_spec.SetField(relaytoken.FieldSupportsBridging, field.TypeBool, value)
		_node.SupportsBridging = value
	}
	if value, ok := _c.mutation.SupportsPermit(); ok {
		_spec.SetField(relaytoken.FieldSupportsPermit, field.TypeBool, value)
		_node.SupportsPermit = value
	}
	if value, ok := _c.mutation.IsFeatured(); ok {
		_spec.SetField(relaytoken.FieldIsFeatured, field.TypeBool, value)
		_node.IsFeatured = value
	}
	if value, ok := _c.mutation.IsSolver(); ok {
		_spec.SetField(relaytoken.FieldIsSolver, field.TypeBool, value)
		_node.IsSolver = value
	}
	if value, ok := _c.mutation.IsErc20(); ok {
		_spec.SetField(relaytoken.FieldIsErc20, field.TypeBool, value)
		_node.IsErc20 = value
	}
	if value, ok := _c.mutation.Supported(); ok {
		_spec.SetField(relaytoken.FieldSupported, field.TypeBool, value)
		_node.Supported = value
	}
	if value, ok := _c.mutation.RawData(); ok {
		_spec.SetField(relaytoken.FieldRawData, field.TypeString, value)
		_node.RawData = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(relaytoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(relaytoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ChainIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relaytoken.ChainTable,
			Columns: []string{relaytoken.ChainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaychain.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChainID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RelayTokenCreateBulk is the builder for creating many RelayToken entities in bulk.
type RelayTokenCreateBulk struct {
	config
	err      error
	builders []*RelayTokenCreate
}

// Save creates the RelayToken entities in the database.
func (_c *RelayTokenCreateBulk) Save(ctx context.Context) ([]*RelayToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RelayToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RelayTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RelayTokenCreateBulk) SaveX(ctx context.Context) []*RelayToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelayTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelayTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
