// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"github.com/wf-platform/wf-account-job/ent/relaychain"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Relay chain table | Relay 链信息表
type RelayChain struct {
	config `json:"-"`
	// ID of the ent.
	// Relay chain id | Relay 返回的链 ID
	ID int64 `json:"id,omitempty"`
	// Relay original chain slug | Relay 原始链标识
	Slug string `json:"slug,omitempty"`
	// Chain display name | 链展示名称
	Name string `json:"name,omitempty"`
	// Chain logo URL | 链 logo 地址
	LogoURL string `json:"logo_url,omitempty"`
	// Chain type | 链类型
	Type string `json:"type,omitempty"`
	// Relay vmType | Relay 返回的 vmType
	VMType string `json:"vm_type,omitempty"`
	// Relay protocol | Relay 返回的 protocol
	Protocol string `json:"protocol,omitempty"`
	// Relay baseChainId | Relay 返回的 baseChainId
	BaseChainID string `json:"base_chain_id,omitempty"`
	// Explorer URL | 区块浏览器地址
	ExplorerURL string `json:"explorer_url,omitempty"`
	// Explorer name | 区块浏览器名称
	ExplorerName string `json:"explorer_name,omitempty"`
	// HTTP RPC URL | HTTP RPC 地址
	RPCURL string `json:"rpc_url,omitempty"`
	// WebSocket RPC URL | WebSocket RPC 地址
	WsRPCURL string `json:"ws_rpc_url,omitempty"`
	// Native token symbol | 原生币符号
	NativeSymbol string `json:"native_symbol,omitempty"`
	// Native token decimals | 原生币精度
	NativeDecimals int `json:"native_decimals,omitempty"`
	// Whether Relay deposit is enabled | Relay 是否允许该链充值
	DepositEnabled bool `json:"deposit_enabled,omitempty"`
	// Relay token support strategy | Relay 返回的 token 支持策略
	TokenSupport string `json:"token_support,omitempty"`
	// Whether Relay disabled this chain | Relay 是否已禁用该链
	Disabled bool `json:"disabled,omitempty"`
	// Whether Relay still supports this chain | Relay 当前是否还支持这条链
	Supported bool `json:"supported,omitempty"`
	// Whether platform enables this chain | 平台是否启用这条链
	Enabled bool `json:"enabled,omitempty"`
	// Raw Relay chain payload | Relay 原始返回数据
	RawData string `json:"raw_data,omitempty"`
	// Create time | 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update time | 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelayChainQuery when eager-loading is set.
	Edges        RelayChainEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RelayChainEdges holds the relations/edges for other nodes in the graph.
type RelayChainEdges struct {
	// Tokens holds the value of the tokens edge.
	Tokens []*RelayToken `json:"tokens,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TokensOrErr returns the Tokens value or an error if the edge
// was not loaded in eager-loading.
func (e RelayChainEdges) TokensOrErr() ([]*RelayToken, error) {
	if e.loadedTypes[0] {
		return e.Tokens, nil
	}
	return nil, &NotLoadedError{edge: "tokens"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelayChain) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relaychain.FieldDepositEnabled, relaychain.FieldDisabled, relaychain.FieldSupported, relaychain.FieldEnabled:
			values[i] = new(sql.NullBool)
		case relaychain.FieldID, relaychain.FieldNativeDecimals:
			values[i] = new(sql.NullInt64)
		case relaychain.FieldSlug, relaychain.FieldName, relaychain.FieldLogoURL, relaychain.FieldType, relaychain.FieldVMType, relaychain.FieldProtocol, relaychain.FieldBaseChainID, relaychain.FieldExplorerURL, relaychain.FieldExplorerName, relaychain.FieldRPCURL, relaychain.FieldWsRPCURL, relaychain.FieldNativeSymbol, relaychain.FieldTokenSupport, relaychain.FieldRawData:
			values[i] = new(sql.NullString)
		case relaychain.FieldCreatedAt, relaychain.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelayChain fields.
func (_m *RelayChain) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relaychain.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case relaychain.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case relaychain.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case relaychain.FieldLogoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logo_url", values[i])
			} else if value.Valid {
				_m.LogoURL = value.String
			}
		case relaychain.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case relaychain.FieldVMType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vm_type", values[i])
			} else if value.Valid {
				_m.VMType = value.String
			}
		case relaychain.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = value.String
			}
		case relaychain.FieldBaseChainID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_chain_id", values[i])
			} else if value.Valid {
				_m.BaseChainID = value.String
			}
		case relaychain.FieldExplorerURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field explorer_url", values[i])
			} else if value.Valid {
				_m.ExplorerURL = value.String
			}
		case relaychain.FieldExplorerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field explorer_name", values[i])
			} else if value.Valid {
				_m.ExplorerName = value.String
			}
		case relaychain.FieldRPCURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rpc_url", values[i])
			} else if value.Valid {
				_m.RPCURL = value.String
			}
		case relaychain.FieldWsRPCURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ws_rpc_url", values[i])
			} else if value.Valid {
				_m.WsRPCURL = value.String
			}
		case relaychain.FieldNativeSymbol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field native_symbol", values[i])
			} else if value.Valid {
				_m.NativeSymbol = value.String
			}
		case relaychain.FieldNativeDecimals:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field native_decimals", values[i])
			} else if value.Valid {
				_m.NativeDecimals = int(value.Int64)
			}
		case relaychain.FieldDepositEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field deposit_enabled", values[i])
			} else if value.Valid {
				_m.DepositEnabled = value.Bool
			}
		case relaychain.FieldTokenSupport:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_support", values[i])
			} else if value.Valid {
				_m.TokenSupport = value.String
			}
		case relaychain.FieldDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field disabled", values[i])
			} else if value.Valid {
				_m.Disabled = value.Bool
			}
		case relaychain.FieldSupported:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field supported", values[i])
			} else if value.Valid {
				_m.Supported = value.Bool
			}
		case relaychain.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case relaychain.FieldRawData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_data", values[i])
			} else if value.Valid {
				_m.RawData = value.String
			}
		case relaychain.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case relaychain.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelayChain.
// This includes values selected through modifiers, order, etc.
func (_m *RelayChain) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTokens queries the "tokens" edge of the RelayChain entity.
func (_m *RelayChain) QueryTokens() *RelayTokenQuery {
	return NewRelayChainClient(_m.config).QueryTokens(_m)
}

// Update returns a builder for updating this RelayChain.
// Note that you need to call RelayChain.Unwrap() before calling this method if this RelayChain
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RelayChain) Update() *RelayChainUpdateOne {
	return NewRelayChainClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RelayChain entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RelayChain) Unwrap() *RelayChain {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelayChain is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RelayChain) String() string {
	var builder strings.Builder
	builder.WriteString("RelayChain(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("logo_url=")
	builder.WriteString(_m.LogoURL)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("vm_type=")
	builder.WriteString(_m.VMType)
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(_m.Protocol)
	builder.WriteString(", ")
	builder.WriteString("base_chain_id=")
	builder.WriteString(_m.BaseChainID)
	builder.WriteString(", ")
	builder.WriteString("explorer_url=")
	builder.WriteString(_m.ExplorerURL)
	builder.WriteString(", ")
	builder.WriteString("explorer_name=")
	builder.WriteString(_m.ExplorerName)
	builder.WriteString(", ")
	builder.WriteString("rpc_url=")
	builder.WriteString(_m.RPCURL)
	builder.WriteString(", ")
	builder.WriteString("ws_rpc_url=")
	builder.WriteString(_m.WsRPCURL)
	builder.WriteString(", ")
	builder.WriteString("native_symbol=")
	builder.WriteString(_m.NativeSymbol)
	builder.WriteString(", ")
	builder.WriteString("native_decimals=")
	builder.WriteString(fmt.Sprintf("%v", _m.NativeDecimals))
	builder.WriteString(", ")
	builder.WriteString("deposit_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.DepositEnabled))
	builder.WriteString(", ")
	builder.WriteString("token_support=")
	builder.WriteString(_m.TokenSupport)
	builder.WriteString(", ")
	builder.WriteString("disabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Disabled))
	builder.WriteString(", ")
	builder.WriteString("supported=")
	builder.WriteString(fmt.Sprintf("%v", _m.Supported))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("raw_data=")
	builder.WriteString(_m.RawData)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RelayChains is a parsable slice of RelayChain.
type RelayChains []*RelayChain
