// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wf-account-job/ent/relaychain"
	"wf-account-job/ent/relaytoken"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RelayChainCreate is the builder for creating a RelayChain entity.
type RelayChainCreate struct {
	config
	mutation *RelayChainMutation
	hooks    []Hook
}

// SetSlug sets the "slug" field.
func (_c *RelayChainCreate) SetSlug(v string) *RelayChainCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableSlug(v *string) *RelayChainCreate {
	if v != nil {
		_c.SetSlug(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *RelayChainCreate) SetName(v string) *RelayChainCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetLogoURL sets the "logo_url" field.
func (_c *RelayChainCreate) SetLogoURL(v string) *RelayChainCreate {
	_c.mutation.SetLogoURL(v)
	return _c
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableLogoURL(v *string) *RelayChainCreate {
	if v != nil {
		_c.SetLogoURL(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *RelayChainCreate) SetType(v string) *RelayChainCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableType(v *string) *RelayChainCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetVMType sets the "vm_type" field.
func (_c *RelayChainCreate) SetVMType(v string) *RelayChainCreate {
	_c.mutation.SetVMType(v)
	return _c
}

// SetNillableVMType sets the "vm_type" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableVMType(v *string) *RelayChainCreate {
	if v != nil {
		_c.SetVMType(*v)
	}
	return _c
}

// SetProtocol sets the "protocol" field.
func (_c *RelayChainCreate) SetProtocol(v string) *RelayChainCreate {
	_c.mutation.SetProtocol(v)
	return _c
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableProtocol(v *string) *RelayChainCreate {
	if v != nil {
		_c.SetProtocol(*v)
	}
	return _c
}

// SetBaseChainID sets the "base_chain_id" field.
func (_c *RelayChainCreate) SetBaseChainID(v string) *RelayChainCreate {
	_c.mutation.SetBaseChainID(v)
	return _c
}

// SetNillableBaseChainID sets the "base_chain_id" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableBaseChainID(v *string) *RelayChainCreate {
	if v != nil {
		_c.SetBaseChainID(*v)
	}
	return _c
}

// SetExplorerURL sets the "explorer_url" field.
func (_c *RelayChainCreate) SetExplorerURL(v string) *RelayChainCreate {
	_c.mutation.SetExplorerURL(v)
	return _c
}

// SetNillableExplorerURL sets the "explorer_url" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableExplorerURL(v *string) *RelayChainCreate {
	if v != nil {
		_c.SetExplorerURL(*v)
	}
	return _c
}

// SetExplorerName sets the "explorer_name" field.
func (_c *RelayChainCreate) SetExplorerName(v string) *RelayChainCreate {
	_c.mutation.SetExplorerName(v)
	return _c
}

// SetNillableExplorerName sets the "explorer_name" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableExplorerName(v *string) *RelayChainCreate {
	if v != nil {
		_c.SetExplorerName(*v)
	}
	return _c
}

// SetRPCURL sets the "rpc_url" field.
func (_c *RelayChainCreate) SetRPCURL(v string) *RelayChainCreate {
	_c.mutation.SetRPCURL(v)
	return _c
}

// SetNillableRPCURL sets the "rpc_url" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableRPCURL(v *string) *RelayChainCreate {
	if v != nil {
		_c.SetRPCURL(*v)
	}
	return _c
}

// SetWsRPCURL sets the "ws_rpc_url" field.
func (_c *RelayChainCreate) SetWsRPCURL(v string) *RelayChainCreate {
	_c.mutation.SetWsRPCURL(v)
	return _c
}

// SetNillableWsRPCURL sets the "ws_rpc_url" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableWsRPCURL(v *string) *RelayChainCreate {
	if v != nil {
		_c.SetWsRPCURL(*v)
	}
	return _c
}

// SetNativeSymbol sets the "native_symbol" field.
func (_c *RelayChainCreate) SetNativeSymbol(v string) *RelayChainCreate {
	_c.mutation.SetNativeSymbol(v)
	return _c
}

// SetNillableNativeSymbol sets the "native_symbol" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableNativeSymbol(v *string) *RelayChainCreate {
	if v != nil {
		_c.SetNativeSymbol(*v)
	}
	return _c
}

// SetNativeDecimals sets the "native_decimals" field.
func (_c *RelayChainCreate) SetNativeDecimals(v int) *RelayChainCreate {
	_c.mutation.SetNativeDecimals(v)
	return _c
}

// SetNillableNativeDecimals sets the "native_decimals" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableNativeDecimals(v *int) *RelayChainCreate {
	if v != nil {
		_c.SetNativeDecimals(*v)
	}
	return _c
}

// SetDepositEnabled sets the "deposit_enabled" field.
func (_c *RelayChainCreate) SetDepositEnabled(v bool) *RelayChainCreate {
	_c.mutation.SetDepositEnabled(v)
	return _c
}

// SetNillableDepositEnabled sets the "deposit_enabled" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableDepositEnabled(v *bool) *RelayChainCreate {
	if v != nil {
		_c.SetDepositEnabled(*v)
	}
	return _c
}

// SetTokenSupport sets the "token_support" field.
func (_c *RelayChainCreate) SetTokenSupport(v string) *RelayChainCreate {
	_c.mutation.SetTokenSupport(v)
	return _c
}

// SetNillableTokenSupport sets the "token_support" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableTokenSupport(v *string) *RelayChainCreate {
	if v != nil {
		_c.SetTokenSupport(*v)
	}
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *RelayChainCreate) SetDisabled(v bool) *RelayChainCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableDisabled(v *bool) *RelayChainCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetSupported sets the "supported" field.
func (_c *RelayChainCreate) SetSupported(v bool) *RelayChainCreate {
	_c.mutation.SetSupported(v)
	return _c
}

// SetNillableSupported sets the "supported" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableSupported(v *bool) *RelayChainCreate {
	if v != nil {
		_c.SetSupported(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *RelayChainCreate) SetEnabled(v bool) *RelayChainCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableEnabled(v *bool) *RelayChainCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRawData sets the "raw_data" field.
func (_c *RelayChainCreate) SetRawData(v string) *RelayChainCreate {
	_c.mutation.SetRawData(v)
	return _c
}

// SetNillableRawData sets the "raw_data" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableRawData(v *string) *RelayChainCreate {
	if v != nil {
		_c.SetRawData(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RelayChainCreate) SetCreatedAt(v time.Time) *RelayChainCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableCreatedAt(v *time.Time) *RelayChainCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RelayChainCreate) SetUpdatedAt(v time.Time) *RelayChainCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RelayChainCreate) SetNillableUpdatedAt(v *time.Time) *RelayChainCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RelayChainCreate) SetID(v int64) *RelayChainCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddTokenIDs adds the "tokens" edge to the RelayToken entity by IDs.
func (_c *RelayChainCreate) AddTokenIDs(ids ...int) *RelayChainCreate {
	_c.mutation.AddTokenIDs(ids...)
	return _c
}

// AddTokens adds the "tokens" edges to the RelayToken entity.
func (_c *RelayChainCreate) AddTokens(v ...*RelayToken) *RelayChainCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTokenIDs(ids...)
}

// Mutation returns the RelayChainMutation object of the builder.
func (_c *RelayChainCreate) Mutation() *RelayChainMutation {
	return _c.mutation
}

// Save creates the RelayChain in the database.
func (_c *RelayChainCreate) Save(ctx context.Context) (*RelayChain, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RelayChainCreate) SaveX(ctx context.Context) *RelayChain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelayChainCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelayChainCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RelayChainCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := relaychain.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.NativeDecimals(); !ok {
		v := relaychain.DefaultNativeDecimals
		_c.mutation.SetNativeDecimals(v)
	}
	if _, ok := _c.mutation.DepositEnabled(); !ok {
		v := relaychain.DefaultDepositEnabled
		_c.mutation.SetDepositEnabled(v)
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		v := relaychain.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
	if _, ok := _c.mutation.Supported(); !ok {
		v := relaychain.DefaultSupported
		_c.mutation.SetSupported(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := relaychain.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := relaychain.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := relaychain.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RelayChainCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RelayChain.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := relaychain.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RelayChain.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "RelayChain.type"`)}
	}
	if _, ok := _c.mutation.NativeDecimals(); !ok {
		return &ValidationError{Name: "native_decimals", err: errors.New(`ent: missing required field "RelayChain.native_decimals"`)}
	}
	if _, ok := _c.mutation.DepositEnabled(); !ok {
		return &ValidationError{Name: "deposit_enabled", err: errors.New(`ent: missing required field "RelayChain.deposit_enabled"`)}
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		return &ValidationError{Name: "disabled", err: errors.New(`ent: missing required field "RelayChain.disabled"`)}
	}
	if _, ok := _c.mutation.Supported(); !ok {
		return &ValidationError{Name: "supported", err: errors.New(`ent: missing required field "RelayChain.supported"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "RelayChain.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RelayChain.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RelayChain.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := relaychain.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "RelayChain.id": %w`, err)}
		}
	}
	return nil
}

func (_c *RelayChainCreate) sqlSave(ctx context.Context) (*RelayChain, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RelayChainCreate) createSpec() (*RelayChain, *sqlgraph.CreateSpec) {
	var (
		_node = &RelayChain{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(relaychain.Table, sqlgraph.NewFieldSpec(relaychain.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(relaychain.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(relaychain.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.LogoURL(); ok {
		_spec.SetField(relaychain.FieldLogoURL, field.TypeString, value)
		_node.LogoURL = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(relaychain.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.VMType(); ok {
		_spec.SetField(relaychain.FieldVMType, field.TypeString, value)
		_node.VMType = value
	}
	if value, ok := _c.mutation.Protocol(); ok {
		_spec.SetField(relaychain.FieldProtocol, field.TypeString, value)
		_node.Protocol = value
	}
	if value, ok := _c.mutation.BaseChainID(); ok {
		_spec.SetField(relaychain.FieldBaseChainID, field.TypeString, value)
		_node.BaseChainID = value
	}
	if value, ok := _c.mutation.ExplorerURL(); ok {
		_spec.SetField(relaychain.FieldExplorerURL, field.TypeString, value)
		_node.ExplorerURL = value
	}
	if value, ok := _c.mutation.ExplorerName(); ok {
		_spec.SetField(relaychain.FieldExplorerName, field.TypeString, value)
		_node.ExplorerName = value
	}
	if value, ok := _c.mutation.RPCURL(); ok {
		_spec.SetField(relaychain.FieldRPCURL, field.TypeString, value)
		_node.RPCURL = value
	}
	if value, ok := _c.mutation.WsRPCURL(); ok {
		_spec.SetField(relaychain.FieldWsRPCURL, field.TypeString, value)
		_node.WsRPCURL = value
	}
	if value, ok := _c.mutation.NativeSymbol(); ok {
		_spec.SetField(relaychain.FieldNativeSymbol, field.TypeString, value)
		_node.NativeSymbol = value
	}
	if value, ok := _c.mutation.NativeDecimals(); ok {
		_spec.SetField(relaychain.FieldNativeDecimals, field.TypeInt, value)
		_node.NativeDecimals = value
	}
	if value, ok := _c.mutation.DepositEnabled(); ok {
		_spec.SetField(relaychain.FieldDepositEnabled, field.TypeBool, value)
		_node.DepositEnabled = value
	}
	if value, ok := _c.mutation.TokenSupport(); ok {
		_spec.SetField(relaychain.FieldTokenSupport, field.TypeString, value)
		_node.TokenSupport = value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(relaychain.FieldDisabled, field.TypeBool, value)
		_node.Disabled = value
	}
	if value, ok := _c.mutation.Supported(); ok {
		_spec.SetField(relaychain.FieldSupported, field.TypeBool, value)
		_node.Supported = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(relaychain.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.RawData(); ok {
		_spec.SetField(relaychain.FieldRawData, field.TypeString, value)
		_node.RawData = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(relaychain.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(relaychain.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaychain.TokensTable,
			Columns: []string{relaychain.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaytoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RelayChainCreateBulk is the builder for creating many RelayChain entities in bulk.
type RelayChainCreateBulk struct {
	config
	err      error
	builders []*RelayChainCreate
}

// Save creates the RelayChain entities in the database.
func (_c *RelayChainCreateBulk) Save(ctx context.Context) ([]*RelayChain, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RelayChain, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RelayChainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RelayChainCreateBulk) SaveX(ctx context.Context) []*RelayChain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelayChainCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelayChainCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
