// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"wf-account-job/ent/predicate"
	"wf-account-job/ent/relaytoken"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RelayTokenDelete is the builder for deleting a RelayToken entity.
type RelayTokenDelete struct {
	config
	hooks    []Hook
	mutation *RelayTokenMutation
}

// Where appends a list predicates to the RelayTokenDelete builder.
func (_d *RelayTokenDelete) Where(ps ...predicate.RelayToken) *RelayTokenDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RelayTokenDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RelayTokenDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RelayTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(relaytoken.Table, sqlgraph.NewFieldSpec(relaytoken.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RelayTokenDeleteOne is the builder for deleting a single RelayToken entity.
type RelayTokenDeleteOne struct {
	_d *RelayTokenDelete
}

// Where appends a list predicates to the RelayTokenDelete builder.
func (_d *RelayTokenDeleteOne) Where(ps ...predicate.RelayToken) *RelayTokenDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RelayTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{relaytoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RelayTokenDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
