// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (_m *TaskUpdate) SetNotNilUpdatedAt(value *time.Time) *TaskUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskUpdateOne) SetNotNilUpdatedAt(value *time.Time) *TaskUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskCreate) SetNotNilUpdatedAt(value *time.Time) *TaskCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskUpdate) SetNotNilStatus(value *uint8) *TaskUpdate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskUpdateOne) SetNotNilStatus(value *uint8) *TaskUpdateOne {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskCreate) SetNotNilStatus(value *uint8) *TaskCreate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskUpdate) SetNotNilName(value *string) *TaskUpdate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskUpdateOne) SetNotNilName(value *string) *TaskUpdateOne {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskCreate) SetNotNilName(value *string) *TaskCreate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskUpdate) SetNotNilTaskGroup(value *string) *TaskUpdate {
	if value != nil {
		return _m.SetTaskGroup(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskUpdateOne) SetNotNilTaskGroup(value *string) *TaskUpdateOne {
	if value != nil {
		return _m.SetTaskGroup(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskCreate) SetNotNilTaskGroup(value *string) *TaskCreate {
	if value != nil {
		return _m.SetTaskGroup(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskUpdate) SetNotNilCronExpression(value *string) *TaskUpdate {
	if value != nil {
		return _m.SetCronExpression(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskUpdateOne) SetNotNilCronExpression(value *string) *TaskUpdateOne {
	if value != nil {
		return _m.SetCronExpression(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskCreate) SetNotNilCronExpression(value *string) *TaskCreate {
	if value != nil {
		return _m.SetCronExpression(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskUpdate) SetNotNilPattern(value *string) *TaskUpdate {
	if value != nil {
		return _m.SetPattern(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskUpdateOne) SetNotNilPattern(value *string) *TaskUpdateOne {
	if value != nil {
		return _m.SetPattern(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskCreate) SetNotNilPattern(value *string) *TaskCreate {
	if value != nil {
		return _m.SetPattern(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskUpdate) SetNotNilPayload(value *string) *TaskUpdate {
	if value != nil {
		return _m.SetPayload(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskUpdateOne) SetNotNilPayload(value *string) *TaskUpdateOne {
	if value != nil {
		return _m.SetPayload(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskCreate) SetNotNilPayload(value *string) *TaskCreate {
	if value != nil {
		return _m.SetPayload(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskLogUpdate) SetNotNilFinishedAt(value *time.Time) *TaskLogUpdate {
	if value != nil {
		return _m.SetFinishedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskLogUpdateOne) SetNotNilFinishedAt(value *time.Time) *TaskLogUpdateOne {
	if value != nil {
		return _m.SetFinishedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskLogCreate) SetNotNilFinishedAt(value *time.Time) *TaskLogCreate {
	if value != nil {
		return _m.SetFinishedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskLogUpdate) SetNotNilResult(value *uint8) *TaskLogUpdate {
	if value != nil {
		return _m.SetResult(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskLogUpdateOne) SetNotNilResult(value *uint8) *TaskLogUpdateOne {
	if value != nil {
		return _m.SetResult(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *TaskLogCreate) SetNotNilResult(value *uint8) *TaskLogCreate {
	if value != nil {
		return _m.SetResult(*value)
	}
	return _m
}
